### ISSUE TITLE
multiple after_authenticate_job

### ISSUE THREAD

**Issue by hakimihamdan88** [ohmybrew/laravel-shopify#100]
can we have after_authenticate_job in array to support multiple jobs?

**Comment by tobiasdalhof** [comment]
Hmm... whats wrong with calling other jobs inside AfterAuthJob?

**Comment by hakimihamdan88** [comment]
1. certain jobs need to be set inline option (true or false).
2. easy to track as all shopify jobs in one place (shopify-app.php)

**Comment by tobiasdalhof** [comment]
That doesn't make sense to me, what are you trying to archive?

**Comment by ohmybrew** [comment]
You can inline the main job and then dispatch other jobs for later inside that job.
