### ISSUE TITLE
Proxy Shopify app

### ISSUE THREAD

**Issue by ricoxor** [ohmybrew/laravel-shopify#101]
Hello,

Now on the Extentions menu in Shopify app there is Embedded app instead of Proxy ! https://puu.sh/BuAcA/cd7f73f350.png

I got a problem, when I accept the scopes the first time i'm redirected to the **domain of the app** and not **my-store.com/admin/apps/my-apps**. What should I do ? Make a condition on my HomeController, if URL contain domain redirect to **my-store.com/admin/apps/my-apps** ?
If I do that, I'm sure sure name of the app in the URL will stay the same for all shops ?

**Edit : I tried to redirection and it doesn't work.**

Thank you

**Comment by ohmybrew** [comment]
Are you using a custom home view?

**Comment by ricoxor** [comment]
Actually no, I just did this : 

web.php : 
`Route::get( '/', 'HomeController@index')->middleware(['auth.shop', 'billable'])->name('home');`

HomeController.php : 
```
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;
use OhMyBrew\ShopifyApp\Facades\ShopifyApp;

class HomeController extends Controller
{
    public function index()
    {
        echo 1;
    }
}

```

**Comment by ohmybrew** [comment]
You're missing all ESDK JS then. See the [default view code](https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/resources/views/layouts/default.blade.php#L21)

If you extend the layout file it should be fine.
