### ISSUE TITLE
Tracking traffic source from paid advertising

### ISSUE THREAD

**Issue by ncpope** [ohmybrew/laravel-shopify#109]
Is there any way that you guys can think to track traffic referral source for first time installs?

I was considering paid advertising but I can't be entirely sure where the installs are coming from. Is my only hope to check google analytics and compare that against typical installation rates? 

I know this isn't entirely related to the package, I just thought someone might be able to shed some insight. I figured I might be able to pick the brains of other people who are in the trenches and maybe there is a way to do it. I kind of doubt it's possible but I am hopeful 👍

**Comment by ptcampbell** [comment]
You'll get some insights from Google Analytics but the most obvious method would be to append a referral string to the URL you use in your advertisements.

**Comment by ohmybrew** [comment]
Im no GA expert or anything, but if you had GA installed on the installation page, used a unique query string on the url, wouldn't you be able to tell in the GA logs? Or even setup a campaign?

**Comment by ohmybrew** [comment]
@ncpope Any tips you've uncovered? If so let me know..might be useful for the wiki too if someone else has similar questions for it

**Comment by ncpope** [comment]
@ohmybrew The most helpful thing I have discovered is that google analytics is actually able to track the clicks on the "Add App" button.

On your google analytics sidebar you can click on Behavior -> Events -> Overview and get information on how often people are attempting to install your app.

I don't think there is a way to tie this to a specific store. However, you are able to segment visitors to your app page by their source if you use segmentation. This is probably the closest we can get to seeing how effective an advertising campaign is.
