### ISSUE TITLE
\App\Jobs\AfterAuthenticateJob::class not found and If apps uninstalled and re install, charge status still canceled

### ISSUE THREAD

**Issue by serkandyck** [ohmybrew/laravel-shopify#111]
Hello, thanks for this awesome packages i try added After Authenticate job for my project, i following wiki but im getting error Not found class,
my env
`AFTER_AUTHENTICATE_JOB=\App\Jobs\AfterAuthenticateJob::class 
  AFTER_AUTHENTICATE_JOB_INLINE=false`

my  App\Jobs\AfterAuthenticateJob.php
[AfterAuthenticateJob.php](https://gist.github.com/serkandyck/10aa11c6a6e7888afb3bfe54fb948918)

And other issue has if apps first installed billing with trial, everything ok, after apps uninstalled uninstall webhook fired apps token null, charge status canceled everything ok, if install app retry charge status still canceled

**Comment by tobiasdalhof** [comment]
Thats my AfterAuthenticateJob configuration:

```php
    /*
    |--------------------------------------------------------------------------
    | After Authenticate Job
    |--------------------------------------------------------------------------
    |
    | This option is for firing a job after a shop has been authenticated.
    | This, like webhooks and scripttag jobs, will fire every time a shop
    | authenticates, not just once.
    |
    */

    'after_authenticate_job' => [
            'job' => \App\Jobs\AfterAuthenticateJob::class,
            'inline' => true // False = execute inline, true = dispatch job for later
    ],
```

**Comment by serkandyck** [comment]
@tobiasdalhof yep its working

**Comment by ohmybrew** [comment]
@serkandyck  You would need to use a string for env `AFTER_AUTHENTICATE_JOB`,

For billing status will continue to remain cancelled, they should get presented with a new charge to accept.

**Comment by serkandyck** [comment]
@ohmybrew i try at string same error,  if direct using `'job' => \App\Jobs\AfterAuthenticateJob::class,` its work.

**Comment by ohmybrew** [comment]
@serkandyck Great, will I close the ticket for now?
