### ISSUE TITLE
How do I use the navigation in an embedded app?

### ISSUE THREAD

**Issue by demoskp** [ohmybrew/laravel-shopify#112]
![embedded app navigation](https://user-images.githubusercontent.com/26207421/46337094-a1c58980-c624-11e8-937d-c2da4c5c0701.PNG)

I would like to have each page name in my app header as well as change my logo on the header. Finally I would also like to action buttons like Save like they can be seen in the image I attached, I haven't found them anywhere in the docs. Does anyone know where that can be changed? 

I would really appreciate any guidance.

Thanks.

**Comment by brianakidd** [comment]
If you are using React on the frontend, you can use Polaris embedded app: [https://polaris.shopify.com/components/get-started#using-embedded-components](url).

If not React, you can use the embedded app SDK: [https://help.shopify.com/en/api/embedded-apps/embedded-app-sdk/getting-started](url)

**Comment by ohmybrew** [comment]
Yup as @brianakidd mentioned both methods will work. If esdk, the main layout file of the app has a scripts section. You can tie into it on your views to add the ESDK js to display the title, dropdowns, etc.

**Comment by demoskp** [comment]
Many thanks to both, this has helped a lot.
