### ISSUE TITLE
shopify authenticate problem!

### ISSUE THREAD

**Issue by Boni619** [ohmybrew/laravel-shopify#113]
hi,I am trying to use this package for creating a shopify app i did all the steps eventually i got this error.
hope you give me some solutions.
![selection_001](https://user-images.githubusercontent.com/28540285/46456443-8301f700-c7cc-11e8-8d40-582b2eb72fc7.png)

**Comment by ohmybrew** [comment]
Commenting out the route in routes/web.php will show the success page for the package. You can make your own via

Route::get('/', 'somecontroller@someaction')->middleware(['auth.shop'])->name('home');

**Comment by ohmybrew** [comment]
Updated wiki for install to assist in this, [example provided as well](https://github.com/ohmybrew/laravel-shopify/wiki/Installation#routing).

**Comment by Boni619** [comment]
Thank you @ohmybrew for your valuable solutions but i found my solutions another way i edit my dot env file and change http://localhost to https://localhost and it works!

**Comment by bernier** [comment]
How do you call the authenticate page?

I have this

`Route::get('/authenticate', function () {
    return view('authenticate');
})->middleware(['auth.shop'])->name('authenticate');`

But I get a 404
authenticate.blade.php has the same content as welcome.blade.php provided in your example

Thanks
