### ISSUE TITLE
Charge creates error with freemium shop

### ISSUE THREAD

**Issue by fyroc** [ohmybrew/laravel-shopify#114]
I'm trying to create a way to automatically charge users when they hit their limit of emails. Right now the Shop is freemium and you're only charged when you run out of emails.

The issue I am coming across is this error:

```
ErrorException (E_NOTICE)
Trying to get property 'type' of non-object

/path/to/laravel/vendor/ohmybrew/laravel-shopify/src/ShopifyApp/Traits/BillingControllerTrait.php
   
 public function usageCharge()
    {
        $shop = ShopifyApp::shop();
        $lastCharge = $this->getLastCharge($shop);
 
        >>>>>>> THIS LINE IS THE ERROR  >>>> if ($lastCharge->type !== Charge::CHARGE_RECURRING) {
            // Charge is not recurring
            return view('shopify-app::billing.error', ['message' => 'Can only create usage charges for recurring charge']);
        }
 
        // Get the input values needed
        $data = request()->only(['price', 'description', 'redirect', 'signature']);
        $signature = $data['signature'];
        unset($data['signature']);
 
```

**Comment by fyroc** [comment]
Also, issue #2.

The charge demo is only to create a link and the user has to manually click that link. Is there a way to automatically charge someone via a controller action instead? Right now I'm redirecting them to that charge route but I would like it a bit more seamless.

**Comment by ohmybrew** [comment]
If they're freemium, they have no recurring charge, usage charges require a recurring charge.

For Part 2... possible... theres a lot involved in that usageCharge method. Not sure where I'd stick something like that? Would it be part of the Shop model, the facade? Unsure there... what about an AJAX call to the route?

**Comment by fyroc** [comment]
So there is no way to have a usage charge without a recurring charge? Is that a Shopify rule or a rule with this package? Do you know a way around this?

**Comment by ohmybrew** [comment]
Shopify thing. You can make a recurring plan of 0.00$ and do strictly usage
charges that way.

On Oct. 4, 2018 14:33, "Cory Fail" <notifications@github.com> wrote:

So there is no way to have a usage charge without a recurring charge? Is
that a Shopify rule or a rule with this package? Do you know a way around
this?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/ohmybrew/laravel-shopify/issues/114#issuecomment-427095311>,
or mute the thread

**Comment by fyroc** [comment]
I ended up just created a $0.00 plan and then I copied the usageCharge method to my `Shop` model and modified it a bit.

Thanks!
