### ISSUE TITLE
Redirecting from Billing Page using Polaris does not embed back into frame

### ISSUE THREAD

**Issue by fyroc** [ohmybrew/laravel-shopify#117]
If you are using React/Polaris, on the initial app install I notice that once you accept the billing screen, the app is no longer embedded. It redirects you to the home screen, but it removes the embed from the site.

**Comment by brianakidd** [comment]
@fyroc Within your AppProvider component, set `foreceRedirect="true"` - it will temporarily reload the page outside of the iframe but will be redirected back within the iframe.

**Comment by ohmybrew** [comment]
Never used Polaris yet.. what's needed for it to work correctly? I can definately add it to the wiki and install.

**Comment by tobiasdalhof** [comment]
@ohmybrew 

> forceRedirect
> boolean
> Forces a redirect to the relative admin path when not rendered in an iframe

https://polaris.shopify.com/components/structure/app-provider

I wouldn't add this to the docs since this is not package related. Just my opinion.. 😺

**Comment by fyroc** [comment]
> @fyroc Within your AppProvider component, set `foreceRedirect="true"` - it will temporarily reload the page outside of the iframe but will be redirected back within the iframe.

That's what I wanted, thank you.

**Comment by fyroc** [comment]
> @ohmybrew
> 
> > forceRedirect
> > boolean
> > Forces a redirect to the relative admin path when not rendered in an iframe
> 
> https://polaris.shopify.com/components/structure/app-provider
> 
> I wouldn't add this to the docs since this is not package related. Just my opinion.. 😺

Agreed. I was actually going to make a repo with a boilerplate including this package and Polaris

**Comment by kouloughli-hemza** [comment]
> > @ohmybrew
> > > forceRedirect
> > > boolean
> > > Forces a redirect to the relative admin path when not rendered in an iframe
> > 
> > 
> > https://polaris.shopify.com/components/structure/app-provider
> > I wouldn't add this to the docs since this is not package related. Just my opinion.. smiley_cat
> 
> Agreed. I was actually going to make a repo with a boilerplate including this package and Polaris

Im Sorry for reopening the issue , 
but im just curios about using Polaris,
are you using React as separate frontend or you just use laravel ui ?
im trying to use this package as REST api , and React as frontend for my app ,but always fails , im sure im missing something during authentication process with appBridge ,
always get error on shopify admin saying : 

There’s no page at this address
Check the URL and try again, or use the search bar to find what you need.
