### ISSUE TITLE
Updating api scopes

### ISSUE THREAD

**Issue by mabrodeur** [ohmybrew/laravel-shopify#120]
Hi,

I have an app that is installed in some stores and now that I'm adding new features, I need to update the api scopes to be able to use these new features.

What would be the way to add api_scopes when the app is already installed? Is there a way to retrigger this? I do not want to make them uninstall/re-install because they might lose their data.

Thanks

**Comment by mabrodeur** [comment]
Well it was fast, I managed to make it work by re-triggering the authenticate with the new scopes.
It then brought me to the page where the user has to accept the new permissions.

Is there a way I could force people to re-authenticate in the app in some way?

**Comment by ohmybrew** [comment]
Simply changing the scopes will make the auth screen re-show since the initial auth always goes through the whole auth process. As far as forcing.. no I don't think so because the session is stored on the browser. Only way is to maybe send them to the auth route with a link.

**Comment by mabrodeur** [comment]
Yes maybe a link would do it. Maybe I could show a message like "An app update is ready! To access new features please update your app by following this link" or something.

I guess we can close this "issue".

Thanks!

**Comment by assasin71** [comment]
changing env doesnt work for me.. the app is not reprompting for the auth process

**Comment by unplugged216** [comment]
Same here. This is not refreshing scopes automatically.

**Comment by unplugged216** [comment]
> Simply changing the scopes will make the auth screen re-show since the initial auth always goes through the whole auth process. As far as forcing.. no I don't think so because the session is stored on the browser. Only way is to maybe send them to the auth route with a link.

This seems to not be working. Anything special that needs to be done? I have added new scopes that require re-auth and no prompt is provided.

**Comment by unplugged216** [comment]
> changing env doesnt work for me.. the app is not reprompting for the auth process i have tried both .env file and shopify-app config

Did you ever find a solution?

**Comment by assasin71** [comment]
> > changing env doesnt work for me.. the app is not reprompting for the auth process i have tried both .env file and shopify-app config
> 
> Did you ever find a solution?

yea about that i gave up on this library and switched to nodejs express js shopify-api .. which worked as expected 
https://github.com/Shopify/shopify-api-node 

if u prefer php u can use this 
https://github.com/Shopify/shopify-api-php

im not exactly sure what the issue is with this library but i tried but was short on time and had to make a choice

regards

**Comment by unplugged216** [comment]
> > > changing env doesnt work for me.. the app is not reprompting for the auth process i have tried both .env file and shopify-app config
> > 
> > 
> > Did you ever find a solution?
> 
> yea about that i gave up on this library and switched to nodejs express js shopify-api .. which worked as expected https://github.com/Shopify/shopify-api-node
> 
> if u prefer php u can use this https://github.com/Shopify/shopify-api-php
> 
> im not exactly sure what the issue is with this library but i tried but was short on time and had to make a choice
> 
> regards

Thank you for getting back to me. Well what a shame. Ill check those out. 

Thank you.
