### ISSUE TITLE
Session is getting lost when using API routes

### ISSUE THREAD

**Issue by fyroc** [ohmybrew/laravel-shopify#121]
I created a new app and I'm getting this error every time the app is accessed on first session start. It looks like during authentication. 

URL Error is happening on:
`https://AppURL/authenticate?code=f40a05a3ef31b404b8969595a257880e&hmac=691e1010df083da9aef530396302d606342e502a0c7c35eb135abb1221233e9d&shop=shopName.myshopify.com&timestamp=1539045117`

Error:
```
Client error: `POST https://shopName.myshopify.com/admin/webhooks.json` resulted in a `400 Bad Request` response: {"errors":{"webhook":"expected Array to be a Hash"}}
```

Error file and line:
`laravel/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php` on  Line 113

**Comment by ohmybrew** [comment]
Its expecting a Ruby hash?? Can I see your config for the webhook?

Its sending the proper request as per docs.

> $api->rest('POST', '/admin/webhooks.json', ['webhook' => $webhook]);

Where `$webhook` would be something like:

```php
['topic' => 'orders/create', 'address' => 'https://some-app.com/webhook/orders-create']
```

**Comment by fyroc** [comment]
Here is my API route:

```
Route::get('/orders', 'OrderController@index')->name('order.index');
```

Order Controller
```
public function index()
    {
        $shop = ShopifyApp::shop();

        dd($shop);

        $orders_array = $shop->api()->request(
            'GET',
            '/admin/orders.json'
        )->body->orders;

        $orders = collect($orders_array);

        return response()->json($orders, 200);
    }
```

Notice my dump? When I hit `/api/orders` it should output the current logged in Shop right? I am just getting 'NULL' returned.

(I might just be doing something wrong)

**Comment by ohmybrew** [comment]
`ShopifyApp::shop` (line 43 of ShopifyApp.php) looks for the session of the shop. I guess its not present for some reason...

Try:

`Route::get('/orders', 'OrderController@index')->name('order.index')->middleware(['auth.shop']);`

**Comment by fyroc** [comment]
> `ShopifyApp::shop` (line 43 of ShopifyApp.php) looks for the session of the shop. I guess its not present for some reason...
> 
> Try:
> 
> `Route::get('/orders', 'OrderController@index')->name('order.index')->middleware(['auth.shop']);`

Did not work. All the middleware does is redirect me to `/login` since the session doesn't exist.

**Comment by ohmybrew** [comment]
Why doesn't the session exist? Is this a fresh route the user would visit (like a Shopify admin link)?

**Comment by fyroc** [comment]
That's a very good question, the session should exist. Unless I'm missing something. It is not a fresh route. I login to the app via Apps in shopify, the `ShopifyApp::shop` object exists. I then go to `/api/orders` and the session is not there. Is it because I am trying to call `/api/orders` in my browser directly and the session is somehow being lost?

**Comment by ohmybrew** [comment]
The session cookie would be tied to the domain and it's set to expire on
close (not sure if that means by close of tab or browser itself). I'm
guessing the cookie is being lost. If you show {{ session('shopify_domain')
}} in the initial view, you'll see the shop domain, dd this in your order
controller and I bet it's blank... But if you're viewing it in the same tab
it should still exist.

**Comment by fyroc** [comment]
@ohmybrew The session is getting lost in the same tab as well as if I call the API function via AJAX.

**Comment by ohmybrew** [comment]
Ah.. ajax call. Not sure there.. can you post the code you use for a ajax
call? I know of a work around for it but it's not secure... Sending "?shop=
xx.myshopify.com" and setting shopify_domain session in the controller. But
I'd rather it use the original cookie, just need to see why the browsers
not sending it with the request.

**Comment by fyroc** [comment]
I have honestly no idea.

**Comment by ohmybrew** [comment]
I found these tips on SO, care to give a try?

"I had a similar issue, doing a a post-request same origin axios with
default configuration sent the auth-cookie, same setup as cors from other
domain axios did not send the auth-cookie until I set the configuration to
axios.defaults.withCredentials = true.
Would be better to have same behaviour on both types of request.."

And

"I had the same problem with post not sending cookies!

I solved my problem by doing

axios("http://mysite.com/api/things/", {
  method: "post",
  data: someJsonData,
  withCredentials: true
})


"

Also this tidbit...
https://github.com/axios/axios/issues/191#issuecomment-311069164

Which suggests, Access-Control-Allow-Credentials: true

Header must be present for cookies to persist.

**Comment by ohmybrew** [comment]
Comment won't format above for some reason, try adding that header first if possible, if not, try the `axios.defaults.withCredentials = true` method

**Comment by fyroc** [comment]
Is it an axios issue if the cookies are lost when hitting the API URL directly?

**Comment by ohmybrew** [comment]
No it wouldn't be. Is the "laravel_session" cookie (cant remember the exact name) present when you visit directly? shopify_domain session being blank means its definately lost, and I don't know why.

The ONLY place I tell the session to kill itself is in AuthShop middleware when things like the shop domain dont match, or missing access token in DB, etc. So I dont think its specific to this package.

Going to play around with AJAX calls on my end and see whats up as well.

**Comment by fyroc** [comment]
I also played around with some middlewareGroups in the Kernal.php with no luck

**Comment by fyroc** [comment]
My last ditch effort is to just use the web API with a blank layout and view. That seems a little hackly though.

**Comment by fyroc** [comment]
I fixed it.

```
'api' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Session\Middleware\StartSession::class,
            'throttle:60,1',
            'bindings',
        ],
```

This needed to be added in Kernal. Be sure throttle and bindings are AFTER the middleware.

**Comment by ohmybrew** [comment]
@fyroc https://imgur.com/a/jbyuajn

Logging in via Apps page as you did, then visiting a route I had in routes/web.php seemed to work.

Doing a standard XHR request (2nd pic) seemed to work as well.

Not sure whats up :/

**Comment by ohmybrew** [comment]
Ah just seen your reply, you were using the API middleware with Laravel? So:

```
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Session\Middleware\StartSession::class,
```

Is required for it to work?

**Comment by fyroc** [comment]
Yes, those are required to keep your session and cookies with the API routes

**Comment by ohmybrew** [comment]
Thanks I think I'll make a wiki doc for this. Any other tips to add?

**Comment by fyroc** [comment]
Yeah, learning react isn't fun.

**Comment by ohmybrew** [comment]
😎

**Comment by ohmybrew** [comment]
FYI, for future reference to anyone, I've made it a [doc](https://github.com/ohmybrew/laravel-shopify/wiki/Shop-Access-Through-API-Routes).

Thanks @fyroc
