### ISSUE TITLE
API Scope merchant reapproval

### ISSUE THREAD

**Issue by fyroc** [ohmybrew/laravel-shopify#124]
Is there a way to handle the approval of a newly added API Scope of an existing Shop?

For example, I need to add a new feature that requires a new API Scope. If an existing Shop that has not approved that scope hits that feature it will throw this error `This action requires merchant approval for scope_name scope`.

**Comment by tobiasdalhof** [comment]
Have you checked #120?

**Comment by fyroc** [comment]
I did not see that, thanks. I also have seen that if you removed the API Token from the DB, it forces them to reauth. Is there any negative side effects to this?

**Comment by ohmybrew** [comment]
I don't think there's any bad effects as they're just approving what's on the screen and a new token is issued for that

**Comment by unplugged216** [comment]
> I don't think there's any bad effects as they're just approving what's on the screen and a new token is issued for that

So, this didnt work either. The app kept on chugging. not even a bump.
