### ISSUE TITLE
Proxy app - Undefined index: Signature in IFrame

### ISSUE THREAD

**Issue by nfunwigabga** [ohmybrew/laravel-shopify#125]
I created a proxy app with the 
```php
Route::get('/proxy', function(){
    return view('frontend')->withContentHeaders(['Content-Type' => 'application/liquid']);
})->middleware('auth.proxy');
```
and in my view, I have a simple `p` tag
```html
<p>This is my app in an Iframe</p>
```
Now I can view this page when I visit my proxy url. But I am trying to render this as an iframe in my shopify store as follows:
```html
<iframe src="https://my-proxy-url/proxy" width="602" height="502" frameborder="0" scrolling="no" name="myInlineFrame"></iframe>
```
I get the error `Undefined index: signature`, which I understand is because I do not have the signature in the iframe src. How does this get passed in the iframe?

**Comment by ohmybrew** [comment]
Proxy apps are meant to be used through Shopify's proxy pages. You'll find the proxy section in your app dashboard in the partner screen. Using an iframe will not work, you simply need to show a standard route through an iframe.
