### ISSUE TITLE
Resolve Shop model from config in AppUninstalledJob

### ISSUE THREAD

**Issue by awebartisan** [ohmybrew/laravel-shopify#128]
Currently, in AppUninstalledJob.php, base model of package (Shop) is directly being used to find the shop.

`use OhMyBrew\ShopifyApp\Models\Shop;`

Kindly resolve it using the `shopify-app.php` inside config as we can override it in most of the cases.

Problem faced: Events on the extended Shop model are not fired, for example Shop Delete event.

**Comment by ohmybrew** [comment]
Yup overlooked this one, I'll update it to use config.
