### ISSUE TITLE
Proxy response downloads the file instead of parsing

### ISSUE THREAD

**Issue by nfunwigabga** [ohmybrew/laravel-shopify#130]
I have set up a proxy URL `http://mysite.com/proxy` and returning the response with application/liquid content:
```php
return response('Hello World', 200)->withHeaders(['Content-Type' => 'application/liquid']);
```
When I visit the proxy url, I expect Shopify to load the response in the `content_for_layout` section in the theme. However, what I actually get is a file download dialogue.

**Comment by ohmybrew** [comment]
Are you visiting this URL *IN* your Shopify store or directly accessing it?

**Comment by nfunwigabga** [comment]
I am visiting it in my Shopify store.

**Comment by ohmybrew** [comment]
A quick google suggests it's a server configuration issue. I don't think I'd be able to figure this out for you.. can you do a curl request to your endpoint and grab all the headers and put them here?

Also confirm no redirect happens. It must be a clean one-way 200 response.

**Comment by nfunwigabga** [comment]
Here:
`curl -I https://mystore.myshopify.com/apps/map`
```
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 18 Oct 2018 23:56:01 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
X-Sorting-Hat-PodId: 68
X-Sorting-Hat-PodId-Cached: 0
X-Sorting-Hat-ShopId: 6246432837
X-Sorting-Hat-PrivacyLevel: default
X-Sorting-Hat-FeatureSet: default
X-Sorting-Hat-Section: pod
X-Sorting-Hat-ShopId-Cached: 0
Set-Cookie: _shopify_y=1068c6ae-49e0-47ed-a627-f14b170edce5; path=/; expires=Sun, 18 Oct 2020 11:34:25 -0000
X-Download-Options: noopen
X-Dc: chi2,chi2
Via: 1.1 vegur
Location: http://myapp.com/proxy?shop=gabs-stage.myshopify.com&path_prefix=%2Fapps%2Fmap&timestamp=1539906961&signature=9e6a0eaeefbac9ab0fec71121353ccbf489e187d0bb939c666fbccaec6104046
X-XSS-Protection: 1; mode=block
X-Permitted-Cross-Domain-Policies: none
X-Content-Type-Options: nosniff
X-Request-ID: eaa539ae-ff69-4738-8223-b412220acd6e
Set-Cookie: secure_customer_sig=; path=/; expires=Mon, 18 Oct 2038 23:56:01 -0000; secure; HttpOnly
Set-Cookie: cart_sig=; path=/; expires=Thu, 01 Nov 2018 23:56:01 -0000; HttpOnly
X-Content-Type-Options: nosniff
```

**Comment by ohmybrew** [comment]
Sorry I mean can you curl your proxy url on Laravel, not Shopify side

**Comment by nfunwigabga** [comment]
Thanks for taking time to look into it. Will continue to investigate from my end.

**Comment by hakimihamdan88** [comment]
@nfunwigabga any solution?

**Comment by nfunwigabga** [comment]
@ohmybrew was right...it was a server configuration issue. I am not sure exactly what configuration caused the issue, but when I deployed my app to Digital Ocean using laravel forge, it worked with no issues.

**Comment by andrewscofield** [comment]
Having same issue on both local machine and on my host. 100% has to do with setting the `Content-Type` header to `application/liquid`. If I remove that it works as expected. Even changing it to a more standard `application/javascript` make it not download as a file. Anybody have any idea why this would happen? My curl output is basically what @nfunwigabga posted above.

**Comment by skillmatic-co** [comment]
Also having the same issue. I am using Docker.
