### ISSUE TITLE
Question: Redirect to Shopify page with success/error message

### ISSUE THREAD

**Issue by bilfeldt** [ohmybrew/laravel-shopify#136]
I am wondering if it's possible to redirect to a Shopify page from a controller? And if it possible to add a message (success/error/info) to the session?

Say for example that we set up an `Admin link` in the App Extension section:
<img width="969" alt="screenshot 2018-11-06 10 46 35" src="https://user-images.githubusercontent.com/30228807/48056090-5a956000-e1b1-11e8-87fc-bf5d4602828d.png">

This will implement an action in the order page which points to any route we specify:
<img width="665" alt="screenshot 2018-11-06 10 49 01" src="https://user-images.githubusercontent.com/30228807/48056240-a34d1900-e1b1-11e8-9e45-bca96300348b.png">

If this route is pointed to a controller which would update the order and redirect back to the order page with either a popup success message like the example below showing the success message

> Line items have been fulfilled

<img width="927" alt="screenshot 2018-11-06 10 52 02" src="https://user-images.githubusercontent.com/30228807/48056936-202cc280-e1b3-11e8-8268-83aa306fe33a.png">

or by showing a sticky success message in the top of the screen like this:
<img width="935" alt="screenshot 2018-11-06 16 03 47" src="https://user-images.githubusercontent.com/30228807/48072817-ac53df80-e1dd-11e8-9088-44544132b6a5.png">

If this is possible and anyboy have some information about this, then I will happily add it to the documentation.

**Comment by bilfeldt** [comment]
@ohmybrew thank you for the answer. I could not find any documentation about this anywhere, but your answer clarifies this.

Maybe the handling of `Admin link` should be added to the documentation ([How to information](https://github.com/ohmybrew/laravel-shopify/wiki#how-tos--information)) and there this could be mentioned as a side note?

Otherwise, it could be beneficial to include this in a section about templates and how to use the Shopify theme?

**Comment by ohmybrew** [comment]
Possibly, I think it's better left to Shopify's own documentation for this since it would just be a repeat.
