### ISSUE TITLE
Base Shop model in WebhookInstaller Job

### ISSUE THREAD

**Issue by awebartisan** [ohmybrew/laravel-shopify#139]
`use OhMyBrew\ShopifyApp\Models\Shop;`
above Shop model is being used in `WebhookInstallerJob.php` which causes issue when using with Trait `ShopModelTrait`.

**Comment by awebartisan** [comment]
Similarly, `ScriptTagInstaller.php`.

**Comment by ohmybrew** [comment]
Solved with your PR #140 , will issue patch release tonight. Thank you.
