### ISSUE TITLE
Problem with webhooks

### ISSUE THREAD

**Issue by mabrodeur** [ohmybrew/laravel-shopify#14]
Hi,

I'm trying to setup webhooks and I'm experiencing problems.
Laravel 5.5
I used your command from the wiki : ``php artisan shopify-app:make:webhook ProductsUpdateJob products/update`` and the file ProductsUpdateJob is there in the App/Jobs folder.

Also added the webhook in the shopify-app.php as mentioned.
```
'webhooks' => [
    [
        'topic' => 'products/update',
        'address' => 'https://xxxxxxx/webhook/products-update'
    ],
],
```

If I make a get request on /admin/webhooks.json, the webhook is correctly installed.

If I update a product on Shopify, nothing happens. I put a log in my ProductsUpdateJob and it never executes.

I also tried to use Insomnia to make a POST request with shopify header and everything, but I only get an error 419 Unknown status with "The page has expired due to inactivity. Please refresh and try again."

It seems like the route doesn't work because nothing seems to get executed.

I might be doing something wrong. Can you help me debug this please? Can't figure it out.

Thanks

**Comment by ohmybrew** [comment]
419 is an odd status for sure. Its working for me on an app. But I'll double check and get back to you.

**Comment by ohmybrew** [comment]
Hey, so I found the issue for this. The webhook route needs to move to Laravel's API grouping. I just did this, and gave it a whirl through Valet, all went fine and webhook got executed.

Just pushed v2.0.1 to account for this. Route is moved to API group. Re-publishing the vendor files to get the new route grouping should solve your issue (config/shopify-app.php).

**Comment by mabrodeur** [comment]
Updated to 2.0.1 and it is indeed working!
Thanks a lot

**Comment by ohmybrew** [comment]
Thats great to hear. Thank you for submitting the issue. I'll go ahead and close it off for now!
