### ISSUE TITLE
Preferred hosting and deployment 

### ISSUE THREAD

**Issue by keyurshah** [ohmybrew/laravel-shopify#141]
Sorry, this is not an issue, can close or delete later. I’m curious as to what your preferred hosting provider and provisioning method you currently prefer. Researching different solutions at the moment. 

Thanks!

**Comment by hakimihamdan88** [comment]
laravel forge or runcloud.io for deployment tool. easy

**Comment by ohmybrew** [comment]
Heroku as well for something quick (although expensive)
