### ISSUE TITLE
Spelling Errors in Plan Create query 

### ISSUE THREAD

**Issue by dhruv728462** [ohmybrew/laravel-shopify#142]
Hey i have just found that on create billable page (link given below). you have written wrong spelling in query.

link : https://github.com/ohmybrew/laravel-shopify/wiki/Creating-a-Billable-App

"VALUSE " should be "VALUES" and "trials_days" should be "trial_days".

Thank You.

**Comment by ncpope** [comment]
Fixed: https://github.com/ohmybrew/laravel-shopify/wiki/Creating-a-Billable-App

**Comment by ohmybrew** [comment]
Thanks! Closing.
