### ISSUE TITLE
how to check paid plan or not?

### ISSUE THREAD

**Issue by sprebel** [ohmybrew/laravel-shopify#143]
how check customer on paid plan or on free trial?

**Comment by ohmybrew** [comment]
Thought I had this in the wiki but appears not, I'll have to add it.

$shop->isFreemium() for freemium
$shop->plan, if null then they are not on a plan
$shop->charges()->whereIn('type', [Charge::CHARGE_RECURRING, Charge::CHARGE_ONETIME])->orderBy('created_at', 'desc')->first()->isActiveTrial(); to determine if the last one time or recurring charge on the shop is in an active trial period

**Comment by sprebel** [comment]
ok, thank you.
