### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by fyroc** [ohmybrew/laravel-shopify#146]
I have received the dreaded 429 error for the first time, and want to figure out a way to avoid it.

I have read up on both: https://github.com/ohmybrew/Basic-Shopify-API#rate-limiting
and: https://github.com/ohmybrew/laravel-shopify/wiki/Usage#rate-limiting

but I'm still not quite sure how to implement this feature. Can you give an example within `laravel-shopify`?

**Comment by tuimz** [comment]
Hard to say without seeing some code. But things like requests in loops will add to the limit fairly quickly.

**Comment by fyroc** [comment]
@tuimz There are requests in loops but that's only because my app is order based and my users need to be able to update multiple orders at once. I did come up with a solution that will remove a bit of API requests. Instead of storing data in metafields like I planned, I'm just going to strictly use my own database to store and retrieve the information and actually charge Shops for access to our own API if they need custom order integration.

**Comment by fyroc** [comment]
I fixed this by rewriting my own code
