### ISSUE TITLE
Session expired - re-authenticating

### ISSUE THREAD

**Issue by jamie-brown** [ohmybrew/laravel-shopify#147]
Hey there, 

Thank you for this great package. 

I'm currently integrating this into an existing Laravel project that utilises Laravel Spark. I have everything set-up and working perfectly. 

The only thing I have noticed is that if the session expires (I manually cleared the cookie to test this scenario) it borks as my project requires an authenticated user for all my routes.

I want to provide ease of use to my Shopify users by autologging them in if they come from the App. However, the only way I see me being able to do this is creating a custom middleware and checking if the shop parameter exists in the URL and then logging in from that. But this poses a security risk right?  The hmac gets passed through too. Is there any extra validation I can do with this to make it more secure?

Many Thanks, Jamie

**Comment by tuimz** [comment]
You can validate that the request actually comes from Shopify using the hmac that is in the headers with the request.

**Comment by jamie-brown** [comment]
From what I see in the link, the AuthProxy middleware grabs a signature from the query parameters, unsets it and then compares this signature against a locally generated Hmac. 

However the signature parameter doesn't exist in my request, just a hmac, locale, timestamp and shop.

I've tried replicating this in my middleware and changing bits around but thus far cannot get the hmacs to match.

**Comment by jamie-brown** [comment]
Ok I got this working, but I needed to change a couple of things: 

Firstly in the createHmac method within ShopifyApp.
Instead of:
```
      if ($buildQuery) {
            //Query params must be sorted and compiled
            ksort($data);
            $queryCompiled = [];
            foreach ($data as $key => $value) {
                $queryCompiled[] = "{$key}=".(is_array($value) ? implode($value, ',') : $value);
            }
            $data = implode($queryCompiled, '');
        }
```

I condensed it down to just:

```
if ($buildQuery) {
      $data = urldecode(http_build_query($data));
}
```

And within my won Middleware, I replicated AuthProxy but swapped out the 'signature' parameter for 'hmac' as 'signature' never gets passed through.

**Comment by jamie-brown** [comment]
This is not to say it needs to be fixed on the ShopifyApp class, because the tests fail with this change. I will just create something for my own edgecase.

**Comment by smartssa** [comment]
Also having this issue where the hmac on the root of the site is not being verified after sessions are cleared/expired on the server. However, instead of potentially breaking ShopifyApp I put the workaround in the middleware and passed `false` to the createHmac method. My middleware is this:

	public function handle( $request, Closure $next ) {
		// Grab the query parameters we need, remove signature since its not part of the signature calculation
		$query     = $request->query->all();
		if (isset($query['hmac'])) {

			$signature = $query['hmac'];
			unset( $query['hmac'] );

			$data = http_build_query( $query );
			$data = urldecode( $data );

			// Build a local signature
			$signatureLocal = ShopifyApp::createHmac( [ 'data' => $data, 'buildQuery' => false ] );
			if ( $signature === $signatureLocal && isset( $query['shop'] ) ) {
				// Save shop domain to session
				Session::put( 'shopify_domain', ShopifyApp::sanitizeShopDomain( $request->get( 'shop' ) ) );
			}
		}

		// All good, process proxy request
		return $next( $request );
	}

And then I pass all requests through the hmac verifier (if hmac is there, otherwise it'll ignore it) and then allow auth.shop to do its normal thing.
