### ISSUE TITLE
Webhook error: Invalid topic specified

### ISSUE THREAD

**Issue by vishal-px** [ohmybrew/laravel-shopify#149]
HI @ohmybrew,
I'm using version 4.2 and my project on HTTPS and I'm working on webhooks.
I just created 5 webhooks and from all this the **app/uninstalled**, **orders/create**, **orders/cancelled**, **refunds/create** are working fine.

Webhooks: 
```
'webhooks' => [
            [
                'topic'   => 'app/uninstalled',
                'address' => env('APP_URL') . '/webhook/app-uninstalled',
            ],
            [
                'topic' => 'orders/create',
                'address' => env('APP_URL').'/webhook/orders-create',
            ],
            [
                'topic' => 'orders/cancelled',
                'address' => env('APP_URL').'/webhook/orders-cancelled',
            ],
            [
                'topic' => 'refunds/create',
                'address' => env('APP_URL').'/webhook/refunds-create',
            ],
            [
                'topic' => 'fulfillments/create',
                'address' => env('APP_URL').'/webhook/fulfillments-create',
            ],
    ],
```
 And lastly I created **fulfillments/create** webhook and try to execute script, but in laravel.log file its throws me error .

Error: 
```
Client error: `POST https://SHOP-DOMAIN/admin/webhooks.json` resulted in a `422 Unprocessable Entity` response:
{"errors":{"topic":["Invalid topic specified. Topics allowed: app\/uninstalled, carts\/create, carts\/update, checkouts\ (truncated...)
```

And when I do the comment to **fulfillments/create** webhook and after flusing session, again I execute the script then its don't show any error in laravel.log file.

Topics from shopify documentation: [open](https://prnt.sc/lrtu7r)
There is an issue with this **TOPIC: fulfillments/create** I can't trace it will you please help.
Thanks.

**Comment by ncpope** [comment]
@vishal-px does the api scopes of your app include `read_fulfillments` and possibly `write_fulfillments`?

**Comment by vishal-px** [comment]
HI @ohmybrew 

Thanks for the help after adding scopes my problem solved.
