### ISSUE TITLE
How to display the current store and the products of that shore?

### ISSUE THREAD

**Issue by online217** [ohmybrew/laravel-shopify#15]
Hello, Thank you for this app. I successfully installed in my local.

But I can't find how to display the current store logged and the products of it.

Can you provide a sample?

Thank you,

Best Regards,

Ronard

**Comment by brianakidd** [comment]
Hi Ronard,

Once the store installs your app, the shop domain and an API token will be stored in the shops database table.  You can use this token to access the shop's data using the Shopify Admin API.  Here's a link:  https://help.shopify.com/api/reference

This package does all of the heavy lifting and now you can focus on your app requirements.  Hope this helps.

**Comment by mabrodeur** [comment]
In your controller you can go like this:

```
$shop = ShopifyApp::shop();
$response = $shop->api()->request('GET', '/admin/products.json');
$products = $response->body;
```

**Comment by online217** [comment]
Hello @brianakidd @mabrodeur, 

Thank you for the response it helps a lot.

**Comment by online217** [comment]
Done. Thank you.

**Comment by pasartap** [comment]
Hi guys, appreciate your help please.

I am trying to do the same thing but my $shop object is null. I followed exactly the statements provided by @mabrodeur. 

I also added the line:
use \OhMyBrew\ShopifyApp\Facades\ShopifyApp;
at the top.

Do I need to somehow initialize the $shop object myself or am I missing something here?

**Comment by ohmybrew** [comment]
@pasartap Did your shop pass through the auth route? (try clicking on the app again in admin and make sure the auth path in Shopify App settings points to /authenticate)

`$shop = ShopifyApp::shop();` after including the facade should load the shop.

Can you spit out what `session('shopify_domain')` value is? See if its filled or empty?

Also, is this route you're accessing using the `auth.shop` middleware?
