### ISSUE TITLE
Extending AppUninstalledJob

### ISSUE THREAD

**Issue by fyroc** [ohmybrew/laravel-shopify#150]
I've extended the AppUninstalledJob by referencing the Wiki.. however, none of my own Job is working. The packages functions are firing correctly, but the extended one is not.

I'm assuming that I just add to the handle?

 ```
class AppUninstalledJob extends \OhMyBrew\ShopifyApp\Jobs\AppUninstalledJob
{
    public function handle()
    {
        if (!$this->shop) {
            return false;
        }
        if ($this->shop->newsletter) {
            $this->shop->newsletter = 0;
            $this->shop->save();
        }

        return true;
    }
}
```

**Comment by ohmybrew** [comment]
The webhook controller looks in App/Jobs. This would be standard object inheritance, so your handle should override the base class handle.

Are you saying the orginal class' handle is firing but not yours?

**Comment by fyroc** [comment]
That's exactly what I'm saying

**Comment by ohmybrew** [comment]
I'm reading over the code for the trait and I don't see how that's not working ha.

You even copied it over and didn't do an extend?

**Comment by fyroc** [comment]
I copied it almost line by line, removed the extend as well. Could it be a cache issue? I wouldn't think so.

I'm upgrading the package now just to see if it solves anything.

**Comment by ohmybrew** [comment]
I doubt that will solve anything. The webhook controller trait is the same
in that version and newest. I don't think it's cache either because if you
look at the webhook controller trait, it looks for App\Jobs\(webhook
type)Job, and just does a new instance of it and calls handle.

**Comment by fyroc** [comment]
I probably just need to restart my listener 🤦

**Comment by ohmybrew** [comment]
You solved it?

**Comment by fyroc** [comment]
I did. There was 2 issues... I don't have access to the Shopify API to grab the Shop's email on Uninstall and I forgot to actually restart the Queue listener

**Comment by ohmybrew** [comment]
Ah good digging, going to make a note of this for others in the wiki incase
someone has an issue. Which queue were you using?

**Comment by ohmybrew** [comment]
Funny enough I just ran into this as well.. ha will close issue and make note in wiki!

**Comment by fyroc** [comment]
I'm using the DB driver and Forge to run the listener. Just to note, to get around not having access to the API on uninstall, I'm storing the email in the Shop table and then clearing it when they uninstall
