### ISSUE TITLE
Help needed - what to do when introducing new webhhoks?

### ISSUE THREAD

**Issue by amosmos** [ohmybrew/laravel-shopify#156]
Hi,

Any suggestion on how to re-run the webhook installer?
What is the best practice in this case regarding stores that already installed the app?

I think that if the merchant clicks on the app in the apps section of the shopify admin, and they don't have the cookie in their session, they will go through the auth process and reinstall the webhooks?

Also - if I remove a webhook, will it be deleted from the shop? If not - do you think we should change the webhook installer script to first delete all webhooks from the shop and then install the app's webhook?

Thanks!

**Comment by ohmybrew** [comment]
Closing for #157 , a service will be created for this.

**Comment by amosmos** [comment]
THANKS!
