### ISSUE TITLE
Webhook installer existence check

### ISSUE THREAD

**Issue by amosmos** [ohmybrew/laravel-shopify#157]
Hi,

I believe the webhook installer checks for existence of each needed webhook by looking at the address field and looking for that address in the shop's existing webhooks.

I believe this means that if we just change the event trigger of the webhhook in config, the webhook will not be installed on the new event.

I may be wrong of course, didn't test it.

Thanks!
Amos

**Comment by ohmybrew** [comment]
I believe it only checks the address off the top of my head but good idea on the topic I should probably add this in as well.

**Comment by ohmybrew** [comment]
So shopify_app gem checks for topic, I check for address. In either case, it may be better for me to move this to a service so someone can fire a method like "destoryWebhooks" and "createWebhooks" so if your webhooks change, you can fire the serve at some point (or a offline job).

**Comment by amosmos** [comment]
Great! Not sure how this would work but I'll wait for you to introduce it first :-)

**Comment by ohmybrew** [comment]
It wouldnt be something automatic, it would have to be independently called as how shopify_app does.

**Comment by ohmybrew** [comment]
Tests are done, passed.

Will do some physical tests and push a minor release if all is good..

**Comment by ohmybrew** [comment]
Sorry computer had issues , will be confirming tomrrow night. But given the unit tests pass Im sure it'll be fine!

**Comment by ohmybrew** [comment]
I won't be putting it into the package to do that (destroy and recreate), because depending on the setup of the persons app it could run inline and fail due to whatever reason, I try to not run API calls during such things.

But you could create an after authenticate job with these methods in it and it will do it at every login, I just won't build it in this way.. too afraid of the issues that could follow :)

**Comment by amosmos** [comment]
I agree with you.

THANKS!

**Comment by ohmybrew** [comment]
Closing per v5.1.0 now has the service.

**Comment by armandohg** [comment]
I think this is not valid anymore, right?

So, how can new webhooks be created to an existing shop?

**Comment by osiset** [comment]
@armandohg You can use the action or direct.

```
use Osiset\ShopifyApp\Actions\DispatchWebhooks;

.....

$action = $this->app->make(DispatchWebhooks::class);
$action($shop->getId(), true); // true means fire inline, false means dispatch to queue
```

If you'd like to directly pass in webhooks instead

```
use Osiset\ShopifyApp\Actions\CreateWebhooks;

....

$action = $this->app->make(CreateWebhooks::class);
$action(
    $shop->getId(), 
    [
            [
                'topic' => 'orders/create',
                'address' => 'https://some-app.com/webhook/orders-create'
            ],
    ]
);
```

**Comment by bastos71** [comment]
Hello there ! It would be nice to write a command that trigger Webhooks sync, don't you think ? 
For example, if we work with continuous integration (and that's my case), we only have to add the command to your deploy steps.

What do you think about it @osiset  ?
