### ISSUE TITLE
App's resources middleware

### ISSUE THREAD

**Issue by amosmos** [ohmybrew/laravel-shopify#158]
Hi,

I was thinking about adding a middleware for customer's facing resources.

What I mean is that the current AuthShop and Billable middleware are meant for routes that are viewed from the Shopify admin - if there is no shop model then the authentication process starts and if there is no billing then the billing consent process starts.

But what about routes that are viewed by the Shop's users?

In my methods I added `abort_unless($shop->plan||$shop->isGrandfathered(),403);`, so perhaps something like this can be added?

Thanks,
Amos

**Comment by ohmybrew** [comment]
Not sure I fully follow. If they're not viewing from proxy or admin, then you can just look the shop model up and do your abort_unless. Maybe you can provide some context?

**Comment by amosmos** [comment]
Yes, that's what I'm doing, but I thought it would be better if there was a middleware for that :-)

**Comment by ohmybrew** [comment]
Ah I see, that wouldn't be a good job for a middleware, simply accessing it is just fine as you're doing :)

**Comment by amosmos** [comment]
The reason I think it should be a middleware is because:

a) it's repetitive - you have to do this in every call to your app (that is not from the admin or a webhook).

b) you already have a shop.auth middleware, and what I'm asking about is exactly the same except for non-admin requests

c) it's very similar to laravel's native 'auth' middleware, except meant for shops and not users.

Amos

**Comment by ohmybrew** [comment]
Thats true, I think its not necessary for the package however. Someone can easily create their own middleware with their own needs :)
