### ISSUE TITLE
Webhook auth question

### ISSUE THREAD

**Issue by amosmos** [ohmybrew/laravel-shopify#159]
Hi,

Regarding webhook authentication middleware - I looked at the code and saw it's checking the hmac, but am not sure if it is also checking the shop is actually installed.

I might be wrong of course, just checking.

Thanks!
Amos

**Comment by ohmybrew** [comment]
It does not actually. I am unsure if it's needed as once uninstalled the webhooks and script tags will be removed, checking the rails counterpart, I don't see them checking the shop as well but hard to tell on mobile, do you think this case would happen?

**Comment by ohmybrew** [comment]
Ill skip on this one, other libs seem to not do this as the webhooks should delete fairly quickly.

**Comment by amosmos** [comment]
The issue here is what if a hacker gets the webhhook URLs and installs them manually on his shop?

**Comment by ncpope** [comment]
In that case the webhook would be deleted off of that single shop. All of the other webhooks on other shops would be unaffected.

**Comment by ncpope** [comment]
> Not sure I get it. How will it be deleted?

If a webhook fails often enough it will be removed automatically from the store by Shopify.

> Regarding webhook authentication middleware - I looked at the code and saw it's checking the hmac, but am not sure if it is also checking the shop is actually installed.

The webhook middleware is to validate that the request originated from Shopify not from a shop. When a webhook is sent to your app it is because a certain event happened on a shop and Shopify then tells all of the apps who have subscribed to that webhook about the event and passes along additional information.

**Comment by amosmos** [comment]
Yeah I know, just thought this package can include the necessary tool that checks for me that not only the request actually originated from Shopify, but also that it was sent from a shop that actually installed the app.
Something like the auth webhook.
This is a similar question I had in issue #158.

> If a webhook fails often enough it will be removed automatically from the store by Shopify.

I am not sure the webhook will fail... Sometimes the app's logic doesn't need to know the shop name. Imagine for example an app that has no configuration for the merchant.

Hope I'm clear, will be happy to explain further.

**Comment by ohmybrew** [comment]
Hmm I'm trying to understand the need for it still. The Rails and Django versions of Shopify packages do not check the shop, they only validate the hmac.

The only way the webhook would be fired would be if a shop was installed.

Even if someone knew your webhook endpoint they'd need to know you apps secret key to be able to compile a valid hmac string. If they don't know it, it will always fail validation. So I think you're safe :)

**Comment by amosmos** [comment]
Oh I didn't know that for an app webhook to work you need the app secret key. Ok then it's covered :-)

Thanks!
