### ISSUE TITLE
Non-embedded app issue

### ISSUE THREAD

**Issue by pasartap** [ohmybrew/laravel-shopify#16]
Hi there, is it possible to make the app not embedded in the Shopify admin? I tried disabling the **Embed in Shopify admin** setting but when I load the app the following occurs:

1. A new window is opened.
2. The index page loads for less than a second.
3. Some redirect happens and now the Shopify 404 page is shown.

Below is the URI generated:
https://pasartap-dev.myshopify.com/admin/apps/e1ef58708fea1eee57e4b47ba6635a05/?hmac=b79e691545e56d13d4273f50f4a20cee2bb8ff414314fae465292a95d0058fc1&shop=pasartap-dev.myshopify.com&timestamp=1520584470

Appreciate any help, thanks.

Razaly

**Comment by ohmybrew** [comment]
Hey

This package doesn't have support for the legacy method. I'll have to see what I can do to add the support in, shouldn't be much. I think essentially because the ESDK JS is in the layout file it's attempting to redirect and load your app into the iframe.

I'll check it out this week and see what I can do to add the support.

**Comment by ohmybrew** [comment]
@pasartap [v2.1.0](https://github.com/ohmybrew/laravel-shopify/releases/tag/v2.1.0) should fix your issue. Update to 2.1.0 then added `SHOPIFY_ESDK_ENABLED=0` to your environment and it should work as expected.

**Comment by ohmybrew** [comment]
I believe this issue should be fine now. I'll close for now. If it is not, feel free to open but in my tests (code and physical) this new addition works as expected :)

**Comment by pasartap** [comment]
Thanks!

**Comment by alexmksolution** [comment]
Hi, does this support non-embed app?
If yes, is there any guide to do it?

Thank you

**Comment by manpreet396** [comment]
Hi Tyler,
(https://github.com/osiset/laravel-shopify/issues/16#issuecomment-372130638)
This is not working in latest version, Can you please help me to solve this.
