### ISSUE TITLE
Error in Billing during app install 

### ISSUE THREAD

**Issue by JDSHINDE** [ohmybrew/laravel-shopify#162]
![screencapture-c30db2e5-ngrok-io-billing-2019-01-02-12_52_15](https://user-images.githubusercontent.com/46311508/50583173-bddbff80-0e8d-11e9-8e83-c3e9c98051db.png)

Error in billing process during the app installation

**Comment by fyroc** [comment]
You need to have Freemium enabled or a Plan with the `on_install` boolean to true.

https://github.com/ohmybrew/laravel-shopify/wiki/Creating-a-Billable-App#creating-plans

**Comment by JDSHINDE** [comment]
thanks, @fyroc its works. i did SHOPIFY_BILLING_ENABLED=0 and its work
