### ISSUE TITLE
How to solve "Refused to display in a frame because it set 'X-Frame-Options' to 'deny'" for Apache server

### ISSUE THREAD

**Issue by dhruv728462** [ohmybrew/laravel-shopify#166]
Hey I have developed a shopify app but there is one error due to that my app haven't accepted. The error is 
"Refused to display in a frame because it set 'X-Frame-Options' to 'deny'" i have seen that in documentation you have written for nginx server to comment the following line - 

add_header X-Frame-Options "SAMEORIGIN";

i have tried to do in Apache server by making .htaccess file but that's not working. can you tell me how to resolve this for Apache server.

**Comment by ohmybrew** [comment]
This package attempts to modify the headers, if this does not work then yes you need to use config.

`Header append X-FRAME-OPTIONS "SAMEORIGIN"`
Or
`Header unset X-FRAME-OPTIONS` should do the trick.

**Comment by dhruv728462** [comment]
Hey when i have changed my hosting to new amazon server so i'm getting this error it's again refuse to connect. 

My Process ->
1. http://example.com/login - when i have done my installation and on billing process i have cancelled my recurring charge.
2.  from shopify admin panel going to my app it should display billing page (because it was declined)
so it's refusing to display but when i'm opening url from console it's working.

![screenshot 359](https://user-images.githubusercontent.com/26164295/51964325-308bcb00-248c-11e9-82c5-1a3e24e7ee83.png)
![screenshot 360](https://user-images.githubusercontent.com/26164295/51964326-308bcb00-248c-11e9-9cef-01565ac85c3e.png)

Please check what's the problem in this. error is 

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://example.com') does not match the recipient window's origin ('null').

**Comment by arslan308** [comment]
> This package attempts to modify the headers, if this does not work then yes you need to use config.
> 
> `Header append X-FRAME-OPTIONS "SAMEORIGIN"`
> Or
> `Header unset X-FRAME-OPTIONS` should do the trick.

In which file we have to add this.???  and how. can you please write it for me and send a screenshot

**Comment by joneyspark** [comment]
Go your .htaccess file and unset the header writing this code for Apache server 

```
<IfModule mod_headers.c> 
Header unset X-Frame-Options "SAMEORIGIN" 
</IfModule>
```

**Comment by burfbari** [comment]
For XAMPP based installations on Windows, 
click on Config button of Apache in the XAMPP Control Panel and select Apache (https.conf) file
Enter the following at the end of the file (drop .c - as taken from joneyspark's comment above) save and restart Apache

```
<IfModule mod_headers> 
Header unset X-Frame-Options "SAMEORIGIN" 
</IfModule>
```

**Comment by Sky-bits** [comment]
> Go your .htaccess file and unset the header writing this code for Apache server
> 
> ```
> <IfModule mod_headers.c> 
> Header unset X-Frame-Options "SAMEORIGIN" 
> </IfModule>
> ```

@joneyspark  

how to do with nginx and express js framework ?
