### ISSUE TITLE
table names

### ISSUE THREAD

**Issue by amosmos** [ohmybrew/laravel-shopify#167]
Hi,

I suggest to use a different name for the app's tables - charges and plans. As these are very generic names that might happen to be part of any app (it just occurred to me since I had them in my app).

So I was thinking of shopify_charges and shopify_plans.

I think these might mean that the model name should change as well, which I think is a good idea too, although I think it's not a must since the namespace will take care of that.

What do you think?
Amos

**Comment by ohmybrew** [comment]
I don't believe it would be an issue for mainstream. If it was, someone could publish the migrations themselves to edit the name and model table name. This apparoch by default would require either extra code on the models to point to the table name or renaming the model. Unless it becomes a wide issue I'll be leaving it as-is I think :)

**Comment by ohmybrew** [comment]
Having thought on this, I think we're ok on this :) I dont want to risk changing the models and migrations for this isolation when its not applicable to most. Override is always still available.

**Comment by amosmos** [comment]
I think it's a better practice of a package to use some sort of namespacing to it's resources.

For example, only on my own app that I'm using your package with, I had both plans and shops resources used as part of my own app :-)

Yes, there is a way to change the name, but I do think that the right approach for a package is to name it in an isolated way and not generic.

Anyways THANKS!!
