### ISSUE TITLE
Pulling product information from Shopify Store

### ISSUE THREAD

**Issue by spooksie** [ohmybrew/laravel-shopify#170]
I've finally got everything connected and configured. Next step is grab the products from the API. 

I see that the scopes already has read products. Is there an easy way to list all the products?

**Comment by ohmybrew** [comment]
You'll need to loop to get all products, but an example at bare to pull the first page would be, Example:

```php
$shop = ShopifyApp::shop();
$request = $shop->api()->rest('GET', '/admin/products.json');
$products = $request->body->products; // array of products from page 1.
```
