### ISSUE TITLE
API problems connecting 

### ISSUE THREAD

**Issue by spooksie** [ohmybrew/laravel-shopify#171]
I've followed the tutorial here: https://github.com/ohmybrew/laravel-shopify/wiki/Usage#accessing-api-for-the-current-shop

Installed Guzzle too as its required.

Heres my code: 
```
<?php

namespace App\Http\Controllers;

use OhMyBrew\ShopifyApp\ShopifyApp;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\GuzzleException;
//use OhMyBrew\BasicShopifyAPI;
//use Illuminate\Http\Request;

class ShopifyApi extends Controller
{
    //
    public function GetAllProducts()
    {
        $shop = ShopifyApp::shop();
        $request = $shop->api()->rest('GET', '/admin/shop.json');
        $products = $request->body->shop->name;

//        var_dump($products);


        return view('products', compact('products'));
    }

}
```
I'm getting this error message
`"Non-static method OhMyBrew\ShopifyApp\ShopifyApp::shop() should not be called statically"
`
I've tried adding static to the function and it gives the same error.

**Comment by brianakidd** [comment]
You need to use the ShopifyApp facade,  OhMyBrew\ShopifyApp\Facades\ShopifyApp

**Comment by spooksie** [comment]
> You need to use the ShopifyApp facade, OhMyBrew\ShopifyApp\Facades\ShopifyApp

You sir, are a LEGEND!
