### ISSUE TITLE
App installs correctly but refuses to connect

### ISSUE THREAD

**Issue by lmartins** [ohmybrew/laravel-shopify#172]
Hi,

I'm having an issue installing a simple app on a production site, which I'm uncertain as to what it is causing it.

I was running the app locally using ngrok and it was working just fine. I've then installed a new web server which is now accessible with https.

All the details on the App Setup were updated to use the new live domain, including the App URL, redirection URL and proxy address.

The env details on the server app install already include the API credentials.

I then went to the store, removed the previous app and installed it again using the new domain configured in the App Setup. The install process runs okay, it shows as a new install on the app dashboard in Shopify Partners, but when I try to access the app from the store I get the following error:

https://cl.ly/52dec37f075a

Any tips as to what could cause this?

Update: One interesting aspect to this, if I paste the app link directly, while logged in to the store, I see briefly the dashboard and when I'm redirected to the Shopify UI (where the app loads from an iframe) its only then that I see the issue.

**Comment by brianakidd** [comment]
Make sure you clear any browser cached cookies.  Also does your webserver allow for loading in an iframe?

**Comment by ohmybrew** [comment]
So it seems like as @brianakidd has said, an iframe issue given you see the dashboard for a second then when it tries to embed, it fails for some reason.

I'd inspect the network and console tabs on Firefox/Chrome to point to some clues. This is certainly not a package issue based on the description.
