### ISSUE TITLE
Duplicate charges_charge_id_unique

### ISSUE THREAD

**Issue by fyroc** [ohmybrew/laravel-shopify#175]
> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6005686372' for key 'charges_charge_id_unique'

I just got an interesting error recently. Any idea why this would happen? Wouldn't each charge be unique?

**Comment by ohmybrew** [comment]
Hmmm... yes it should be unique from Shopify. Trying to think how this would trigger... I wonder if someone tried to accept a charge, Shopify failed or was down for some reason, then they tried to accept it again? By that time it would've been in the database possibly. Do you have any other information that might lead to how it would happen?

**Comment by fyroc** [comment]
No idea. It was just sent to Sentry.

**Comment by ohmybrew** [comment]
I think this is the issue. I'm going to modify it to do a find or create.
________________________________
