### ISSUE TITLE
i'm getting error "refuse to connect".

### ISSUE THREAD

**Issue by dhruv728462** [ohmybrew/laravel-shopify#176]
Hey when i have changed my hosting to new amazon server so i'm getting this error it's again refuse to connect. 

My Process ->
1. http://example.com/login - when i have done my installation and on billing process i have cancelled my recurring charge.
2.  from shopify admin panel going to my app it should display billing page (because it was declined)
so it's refusing to display but when i'm opening url from console it's working.

![screenshot 359](https://user-images.githubusercontent.com/26164295/51964325-308bcb00-248c-11e9-82c5-1a3e24e7ee83.png)
![screenshot 360](https://user-images.githubusercontent.com/26164295/51964326-308bcb00-248c-11e9-9cef-01565ac85c3e.png)

Please check what's the problem in this. error is 

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://example.com') does not match the recipient window's origin ('null').

_Originally posted by @dhruv728462 in https://github.com/ohmybrew/laravel-shopify/issues/166#issuecomment-458836620_

**Comment by brianakidd** [comment]
It could be other things causing it but you should be running over SSL - Shopify requires it.

**Comment by dhruv728462** [comment]
I have followed everything from the package and even using SSL with my url giving this error and not providing the view.

**Comment by ohmybrew** [comment]
Your error in console shows its trying to connect via http. I'd check your APP_ENV url and also partner dashboard to ensure things are correct. This error can also happen when the iframe fails to load (500 error, etc). Your app was working before your move so something is up with the configuration. However, I do not provide support for server related issues.

**Comment by ohmybrew** [comment]
When is it you're seeing this issue? Shopify handles decline of billing internally. If you decline the charge Shopify now redirects the customer to the app page with a message.

**Comment by ohmybrew** [comment]
Please check your server logs, chrome/firefox network tab, and such for clues. The iframe in your screenshot is saying it was refused to connect.

https://streamable.com/furdx

In the video I am installing the app, then declining the charge, I get redirected to Shopify. When I re-open the app, I am asked again to approve charge, I do, page loads.

**Comment by ohmybrew** [comment]
@dhruv728462 Have you had any success in debugging this?

**Comment by joneyspark** [comment]
### I have also the problem "refuse to connect"
I configure everything following documentation but I don't understand why it's refuse to connect 

![refuse to connect](https://user-images.githubusercontent.com/34330722/83837609-a48d5180-a718-11ea-8557-fc1a37b1da53.png)

**Comment by osiset** [comment]
Your issue is XFrameOptions... modify your Nginx or Apache config to allow.
