### ISSUE TITLE
Send events to custom queue

### ISSUE THREAD

**Issue by armandohg** [ohmybrew/laravel-shopify#177]
Sometimes it is necessary to process webhooks events immediately to keep an up to date database.
If my default queue has a lot of jobs pending it will take a long time to process the webhook event job.

Adding an option to set a custom queue my help solve this.
eg. You can set a custom 'high' or 'webhook' queue and run the command:
php artisan queue:work --queue=high,default (all jobs in the 'high' queue will be processed first)

Does this make sense?

**Comment by ohmybrew** [comment]
Makes sense yes, should not be hard to add these config options I can certainly look into this.

**Comment by ohmybrew** [comment]
Solved in v5.3.0 see changelog/upgrading for details. Thanks!
