### ISSUE TITLE
How to return manifest.json file to shopify

### ISSUE THREAD

**Issue by bhavinjr** [ohmybrew/laravel-shopify#178]
Hello Is there any way to return or add `manifest.json` file to the Shopify store

I also configure proxy setting in Shopify but didn't get any results

For more Information about the issue [Check here](https://stackoverflow.com/questions/54593819/shopify-proxy-is-not-working-with-manifest-json-shopify-and-laravel).

Anyone have idea about that?

**Comment by ohmybrew** [comment]
It seems you have a good reply in the Stackoverflow, this is not related to the package directly. As mentioned on SO, its better to inject these types of files via scripttags and theme assets.

Thanks!
