### ISSUE TITLE
Trying to get property 'shopify_domain' of non-object

### ISSUE THREAD

**Issue by pearlbells** [ohmybrew/laravel-shopify#179]
I am trying to access the products API in the middleware. I am getting the above error. Please help I am new to laravel and Shopify.

My code 

`<?php
namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use OhMyBrew\ShopifyApp\Facades\ShopifyApp;

class Products
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        $shop = ShopifyApp::shop();
        echo(ShopifyApp::shop()->shopify_domain); // If you want to get all the product
        $response = $shop->api()->request('GET', '/admin/products.json');
        $products = $response->body;
        echo 'products page';
        return $next($request);
    }
}

Thanks in advance
`

**Comment by ohmybrew** [comment]
Sorry I can not provide support for building. Middleware is not really the place for doing this logic, this should be done in a service or a controller. I think you should try out some basic Laravel apps before attempting to go head in on Shopify development, it can be tricky :)

**Comment by pearlbells** [comment]
Thanks for the reply. I added the code in the controller. It is working.

`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use OhMyBrew\ShopifyApp\Facades\ShopifyApp;

class ProductsController extends Controller
{
    public function index() {
        
        $shop = ShopifyApp::shop();
        $response = $shop->api()->request('GET', '/admin/products.json');
        $products = $response->body;
       // echo '<pre>';
       // print_r($products);      
        
    }
}
`
