### ISSUE TITLE
Migration Refresh issue

### ISSUE THREAD

**Issue by ilamp** [ohmybrew/laravel-shopify#181]
Executing `php artisan migrate:refresh` causes following issue:

`Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1828 Cannot drop column 'plan_id': needed in a foreign key constraint 'charges_plan_id_foreign' (SQL: alter table `charges` drop `plan_id`)`

**Comment by ilamp** [comment]
I have the bug fix for this. Please allow me access so that I can submit a pull request. @ohmybrew

**Comment by ohmybrew** [comment]
Hi! Please open a pull request with the code change and I can merge it in.

**Comment by ilamp** [comment]
Doing it right now.

**Comment by ilamp** [comment]
I see that the travis throwing an error:

`SQLite doesn't support dropping foreign keys (you would need to re-create the table).`

Do you want me to look into that?

**Comment by ilamp** [comment]
@ohmybrew Hey Tyler, pull request should be passing the tests now. Please let me know if you wanted me to change anything else.
Thanks
Daljeet
