### ISSUE TITLE
PHP Fatal error on Tests

### ISSUE THREAD

**Issue by ilamp** [ohmybrew/laravel-shopify#183]
I am getting following error in the unit tests:

`PHP Fatal error:  Declaration of OhMyBrew\ShopifyApp\Test\TestCase::setUp() must be compatible with Orchestra\Testbench\TestCase::setUp(): void in /Users/dsingh/Code/laravel-shopify/tests/TestCase.php on line 10`

**Comment by ilamp** [comment]
orchestra/testbench-core version is 3.8.x-dev 68f5699

**Comment by ilamp** [comment]
This has to do with the return type declaration in Orchestra\Testbench\TestCase::setUp().
I can define update the tests and define the return types but that might make the code incompatible with PHP < 7.0.

What do you think @ohmybrew? Do you want to keep the tests compatible with 5.6 or update them?

**Comment by ohmybrew** [comment]
I think it's because you're using 7.3 PHP version of orchestra. The version in composer will need to be downgraded.

**Comment by ilamp** [comment]
PHP 7.2.14 (cli) (built: Jan 12 2019 05:21:04) ( NTS )

**Comment by ohmybrew** [comment]
@ilamp I've forced it to stay at the 3.5 versions. If you pull from master and update composer, this issues should resolve.

**Comment by ilamp** [comment]
@ohmybrew You beat me to it. I was about to commit a change for that. Thank you
