### ISSUE TITLE
Ability to change billing to another currency (Euro)

### ISSUE THREAD

**Issue by spooksie** [ohmybrew/laravel-shopify#184]
Hey,

I'd like to congratulate you on this amazing repo. Its saved me so many hours of work.

I've got the payments working, however its only charging in USD for one-off billable payments. When my whole system is EURO based. 

Is it possible to change to Euro?

https://github.com/ohmybrew/laravel-shopify/wiki/Creating-a-Billable-App#freemium-mode

**Comment by spooksie** [comment]
Spoken with them direct, its not possible. Its only USD based and remember its a 80/20 split in charges on the app.

**Comment by ohmybrew** [comment]
Yup Shopify only charges in USD right now for apps.
