### ISSUE TITLE
[Discussion] Architecture with separate frontend and backend

### ISSUE THREAD

**Issue by tobiasdalhof** [ohmybrew/laravel-shopify#185]
Hey all,

I'm currently thinking about separating my frontend (user interface) and backend.

Is there currently a way to authorize the frontend to make requests to the backend?

**Comment by ohmybrew** [comment]
Like Vue -> backend for example?

Hmm. If they're logged in/authed then any standard xhr request should work given the xhr request has access to cookies for the session.

**Comment by tobiasdalhof** [comment]
Exactly. What about auth via a JWT?

**Comment by ohmybrew** [comment]
That's certainly possible.

Could use tymon/jwt-auth but that requires its own setup and could conflict with someone's code.

If it were to be a part of this package it would have to be something baked in..

Certainly worth exploring. What sort of flow and use case do you see for it?

**Comment by fyroc** [comment]
Why use Vue with Shopify has React/Polaris?

**Comment by ohmybrew** [comment]
True! Still was looking into best implementation for this. I'd rather not include another package as that would be odd and also mean more setup.

**Comment by ohmybrew** [comment]
What sort of flow were you invisioning for using frontend/backend

**Comment by ptcampbell** [comment]
I'm not sure what this question is asking? Deeper Polaris integration from the outset?

**Comment by ohmybrew** [comment]
Closing for now as I dont have a good solution to offer. @tobiasdalhof  If you have more insight, feel free to reopen :)
