### ISSUE TITLE
Searching for a discount code returns an error

### ISSUE THREAD

**Issue by demoskp** [ohmybrew/laravel-shopify#186]
I am trying to check if a discount code already exists with the lookup endpoint:

`GET /admin/discount_codes/lookup.json?code=<discountcode>
`

However I have come across 2 issues here. When you make a request for an existing code you get the body which is empty which makes sense but the location header is not in the response headers it does not exist. Is that something that should be returned automatically by Shopify or do we need to send out our own specific headers as params in addition to the 'X-Shopify-Access-Token?

The second issue I encounter is when a request is made to retrieve a discount code location that does not exist in Shopify then you get a 404 not found error but instead I would like to not get an exception error and instead treat the 404 as an indication that the discount doesn't exist and then I will create it in another sequence.

I could duplicate the rest function the BasicShopifyAPI and add the changes that it works for this kind of request as it is unique.

Any suggestions?

**Comment by ohmybrew** [comment]
The exceptions are direct from guzzle and expected behavior.

I wouldn't muddle with catching these 404s at the core library because it should be left up to the developer to determine what to do with their exception.

The issue to is if discount returns a 404 for no discount, but someone also trys to use a deprecated API route, then you now have an issue of determining what to do for the user, and it'll be guessed wrong.

It's best to catch the exception for discount since you now know 404 returns no discount. You can even make a wrapper on your side for this stuff.

On mobile, but maybe something like

function shopifyCall(Closure $fn) {
  try {
     return $fn();
   } catch (\GuzzleHttp\Exception\RequestException $e) {
      return null;
    }
}

Or similar.

**Comment by demoskp** [comment]
Alright I'll try that but what about the initial call with a valid discount code? Why am I not getting the location header?

On 24 Feb 2019 16:15, Tyler King <notifications@github.com> wrote:

The exceptions are direct from guzzle and expected behavior.

I wouldn't muddle with catching these 404s at the core library because it should be left up to the developer to determine what to do with their exception.

The issue to is if discount returns a 404 for no discount, but someone also trys to use a deprecated API route, then you now have an issue of determining what to do for the user, and it'll be guessed wrong.

It's best to catch the exception for discount since you now know 404 returns no discount. You can even make a wrapper on your side for this stuff.

On mobile, but maybe something like

function shopifyCall(Closure $fn) {
try {
return $fn();
} catch (\GuzzleHttp\Exception\RequestException $e) {
return null;
}
}

Or similar.

**Comment by ohmybrew** [comment]
The response from BasicShopifyAPI returns the body and response, direct from what guzzle gives. So I am not sure, have you looked into all the response headers for sure?

**Comment by ohmybrew** [comment]
Is curl installed on the machine? If not guzzle falls back to another library which has different header handlers

**Comment by demoskp** [comment]
I have looked into all the responses from within the response and it's not there. I even went into the basicshopifyapi and added a third element getHeader('location') and it returns it empty there.

On 24 Feb 2019 16:51, Tyler King <notifications@github.com> wrote:

The response from BasicShopifyAPI returns the body and response, direct from what guzzle gives. So I am not sure, have you looked into all the response headers for sure?

**Comment by demoskp** [comment]
Curl is installed yes I just checked so that shouldn't be the issue. When you get some time try it as well I think you might get the same issue

On 24 Feb 2019 16:56, Tyler King <notifications@github.com> wrote:

Is curl installed on the machine? If not guzzle falls back to another library which has different header handlers

**Comment by ohmybrew** [comment]
You would won't get location if it's not a redirect though

**Comment by demoskp** [comment]
Then why does it say in the Shopify manual that the location of the discount code will be returned in the location header?

On 24 Feb 2019 17:25, Tyler King <notifications@github.com> wrote:

You would won't get location if it's not a redirect though

**Comment by ohmybrew** [comment]
Can you link me to this doc

**Comment by demoskp** [comment]
https://help.shopify.com/en/api/reference/discounts/discountcode

Discount code lookup.

On 24 Feb 2019 18:38, Tyler King <notifications@github.com> wrote:

Can you link me to this doc

**Comment by ohmybrew** [comment]
Ok I'll have to test this tomorrow. By default. Guzzle will follow redirects so it should then go to the location. What are you getting for a response body?

**Comment by demoskp** [comment]
Response body is empty which is what the Shopify API docs suggested as well.

On 25 Feb 2019 11:35, Tyler King <notifications@github.com> wrote:

Ok I'll have to test this tomorrow. By default. Guzzle will follow redirects so it should then go to the location. What are you getting for a response body?

**Comment by ohmybrew** [comment]
So the issue was two fold. Redirect from Shopify doesnt include private access keys obviously, so Guzzle attempted to go to a page which actually ended up producing a login page.

I've fixed this in development of the library (BasicShopifyAPI), and need to write some more tests.

I'll move the ticket to there for now.
