### ISSUE TITLE
[Feature] Ability to customize the /login page?

### ISSUE THREAD

**Issue by stursby** [ohmybrew/laravel-shopify#187]
First off, thanks for this awesome project!

So I was wondering what the best way would be to customize the layout/style of the `/login` view?

![image](https://user-images.githubusercontent.com/527849/53302679-97e83100-3826-11e9-916a-5650b413e7c4.png)

I see that it's being loaded from `/vendor/ohmybrew/laravel-shopify/src/ShopifyApp/resources/views/auth/index.blade.php` but I'm not sure how to override it w/o modifying that code directly (which I don't want to do since it would be overwritten with any future updates).

Can I tap into the Middleware and specify my own view for specific routes? Any thoughts would be much appreciated!

Thanks!

**Comment by ohmybrew** [comment]
No problem!

To override views it's standard Laravel package so you would just need to put the files in the correct place for Laravel to see and override the package views.

See this wiki entry for an idea https://github.com/ohmybrew/laravel-shopify/wiki/Overriding-and-Extending#views
