### ISSUE TITLE
laravel-shopify install fails issue with basic-shopify-api And Session Termination Not handled properly

### ISSUE THREAD

**Issue by ARKKYN** [ohmybrew/laravel-shopify#189]
Suggestion 1: It asks for 4.0 version of basic-shopify-api , but the current one is 5.1
@ohmybrew 

Bug: let's say i am logged into shopify using an emmbedded app built using laravel shopify. and I am uninstalling the app from the shop. and if i open the shopify app url in another tab it still does not terminate session and redirects to the same shop embedded app url that's it

**Comment by ohmybrew** [comment]
What's the error?

**Comment by ARKKYN** [comment]
@ohmybrew I installed ohmybrew/basic-shopify-api first and then I tried to install the latest version of laravel-shopify it throws an error, I won't say it as bug for sure but updating dependency will be better

**Comment by ohmybrew** [comment]
Oh you had conflicting composer entries by doing that and it got confused. Stripping out basic-shopify-api and upping laravel-shopify to ~6.0 whould work fine and resolve.

**Comment by ARKKYN** [comment]
@ohmybrew please have a look session termination and shopify plan based billing Please merge the pull request (https://github.com/ohmybrew/laravel-shopify/pull/160)

**Comment by ohmybrew** [comment]
Please open a new issue for that.
