### ISSUE TITLE
ShopifyQL

### ISSUE THREAD

**Issue by vishal-px** [ohmybrew/laravel-shopify#191]
Is this package support Shopify Query Language: https://prnt.sc/mtw6p0 ?
If yes, then is there any documentation? 

Thanks.

**Comment by ohmybrew** [comment]
Yes, [see here](https://github.com/ohmybrew/Basic-Shopify-API).

In the case of this package access it would be something like

```php
$shop->api()->graph(string $query, array $variables = []);
```

**Comment by vishal-px** [comment]
Thank you @ohmybrew for the help.

**Comment by vishal-px** [comment]
Hi @ohmybrew 

Using GraphQL I tried to create product.

1. Without metafields the product successfully created.
2. Now, I tried to create product with metafields then it throw me this error: https://prnt.sc/mwa46a

This is my inpu string:
`{title:"Test Product - 1",descriptionHtml:"Test Description",metafields:{namespace:"mataNamespace",key:"mataKey",value:"mataValue",valueType:"STRING"}}`

This is my controller:

```
<?php
namespace App\Http\Controllers\Bundle;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
class BundleProductController extends Controller 
{
    public function index(Request $request){
    	$shop = \ShopifyApp::shop();
    	if(@$request->_token != "") {

    		$input['title'] = "Test Product - 1";
    		$input['descriptionHtml'] = "Test Description";

    		$metafields['namespace'] = 'mataNamespace';
    		$metafields['key'] = 'mataKey';
    		//$metafields['description'] = 'mata_desc';
    		$metafields['value'] = 'mataValue';
    		$metafields['valueType'] = 'STRING';
    		$input['metafields'] = $metafields;
    		echo $query_input = $this->jsonString($input);

    		$query = <<<EOT
			mutation {
			  productCreate(input: $query_input) {
			    product {
			      id
			      handle
			    }
			    userErrors {
			      field
			      message
			    }
			  }
			}
EOT;
			$shop = $shop->api()->graph($query,[]);
			dd($shop);
    	}
    	return view('pages.bundle.create');
    }

    public function jsonString($input){
    	return preg_replace('/"([^"]+)"\s*:\s*/', '$1:',  json_encode($input));
    }
}
```
Can you tell me where I'm wrong.

Thank you.

**Comment by ohmybrew** [comment]
I dont think you need to json_encode it... since this is done by Guzzle.

I believe it needs to be STRING without any quotes around it.

**Comment by vishal-px** [comment]
I tried without quote and it's thrown me an error.
Can you please show me the example of a product with metafields?

**Comment by ohmybrew** [comment]
Sorry I have not played with adding metafields through graph.
