### ISSUE TITLE
Adding elements to 'My Account' pages within Shopify

### ISSUE THREAD

**Issue by spooksie** [ohmybrew/laravel-shopify#192]
Hey buddy,

The apps nearly ready to go live, love the repo as it's saved me so much time. However I'm looking for a pointer from anyone who can help me. 

Basically, once someone installs my app, I want to add text input fields in the 'My Account > Order' page.  Which will communicate with my app.

Is this possible? if so can you point me in the right direction?

**Comment by ohmybrew** [comment]
You can use scripttag feature to inject scripts into the shop which can use JS to add those inputs.

Other than that, you would need to do theme mods.

Those are really the only two ways.
