### ISSUE TITLE
The page has expired due to inactivity

### ISSUE THREAD

**Issue by vishal-px** [ohmybrew/laravel-shopify#193]
Hi @ohmybrew 

I have set up the  Shopify proxies in my app, here is my code.

 **routes -> web.php**
`Route::match(['get','post'],'/bundle-product','Bundle\BundleProductController@index')->name('bundle.create')->middleware('auth.proxy');`

**Controller**

```
<?php
namespace App\Http\Controllers\Bundle;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
class BundleProductController extends Controller 
{
    public function index(Request $request){
    	if($request->isMethod('get'))
    		return view('pages.bundle.create');
    	
    	if($request->isMethod('post')){
    		dd($request);
    	}
    }
}
```

**View**

```
<form action="https://mydomain.myshopify.com/apps/proxies-app/bundle-product" method="post" >
@csrf
	<input type="text" name="title" class="Polaris-TextField__Input" placeholder="Title" value="{{ old('title') }}">

	<button type="submit" class="Polaris-Button Polaris-Button--primary"><span class="Polaris-Button__Content"><span>Save</span></span></button>
</form>
```

When I submit the form the it showing me this page: https://prnt.sc/mvfl9o
Can you please tell me what wrong I'm doing?

**Comment by ohmybrew** [comment]
Post requests do not work for app proxies, as the request for proxies passes through Shopify servers first.

**Comment by vishal-px** [comment]
So for form submission, I have to use get method? 
OR
If you have suggestions then please with me.
Thank you.

**Comment by ohmybrew** [comment]
Use GET or AJAX post direct to server. Thats all I can offer :) Google the topic might find some other options!
