### ISSUE TITLE
Redirect to guide page after install

### ISSUE THREAD

**Issue by frexiz** [ohmybrew/laravel-shopify#195]
Hello, how can I set a custom redirect in the after authenticate job? I want after install to redirect the user to /how-to-install.

**Comment by fyroc** [comment]
Just use conditional logic in your home controller to redirect if it's their first visit.

**Comment by ohmybrew** [comment]
@fyroc  Is correct. Since the job is dispatched out (either inline or background) the redirect won't happen, so this redirect you wish to do needs to happen in a controller or middleware, but a simple check on the home controller would work.
