### ISSUE TITLE
[Question] Making API calls from outside the auth middleware

### ISSUE THREAD

**Issue by bilfeldt** [ohmybrew/laravel-shopify#196]
The documentation paragraph [Accessing API for the current shop](https://github.com/ohmybrew/laravel-shopify/wiki/Usage#accessing-api-for-the-current-shop) describes how to use the current authenticated shop to make API calls to Shopify like so:
```
// Returns instance of \OhMyBrew\BasicShopifyAPI (ohmybrew/basic-shopify-api)
$shop = ShopifyApp::shop();
$shop->api()->rest(...);
```
According to [docs](https://github.com/ohmybrew/laravel-shopify/wiki/Usage#accessing-the-current-shop):

> For this to properly work your route must be behind `auth.shop`

# Jobs (and webhooks)
Let us say, that we implement a `queued job` that needs to make API calls to Shopify - it might for example be the `CustomersDataRequestJob` described [here](https://github.com/ohmybrew/laravel-shopify/wiki/GDPR#customersdata_request).

This job will be fired by some controller behind the `auth.webhook` middleware.

Such a queued job will be fired by some controller behind the `auth.shop` middleware (or the `auth.webhook` middleware). It could also be an event listener that registres something happens, which require an API call to Shopify on behalf of the currently authenticated shop.

# Events and listeners
Say that we have a controller behind the `auth.shop` middleware. When something relevant occurs, then we [dispatching an event](https://laravel.com/docs/5.8/events#dispatching-events) like so: `event(new OrderHandled($order));`

We have an [event listener](https://laravel.com/docs/5.8/events#defining-listeners) for this event, which should then make some API call to Shopify - might for example be adding meta data to the order.

# Question
How should the job or event listener get an instace of `\OhMyBrew\BasicShopifyAP` authenticated as the shop that originally made the request? One need to be sure that the instance is authenticated as the store that originally was responsible for firing the event og job.

Thanks for input.

**Comment by ohmybrew** [comment]
Not sure I entirely follow.. but you can just look the shop up via eloquent and get the API instance.

```php
$shop = Shop::where('shopify_domain', 'domain.myshopify.com')->first();
$shop->api()->rest(...);
```

**Comment by bilfeldt** [comment]
@ohmybrew Thanks for your explanation. I was not aware that I could get the api directly from the `App\Shop` model.

We are passing this model to any queued jobs, so using this will make it possible to use the shops api.
