### ISSUE TITLE
Call to undefined method App\Jobs\AfterAuthenticateJob::dispatch() after update from 3.x to 6

### ISSUE THREAD

**Issue by frexiz** [ohmybrew/laravel-shopify#197]
Hello, I have updated the package from version 3 to version 6. Laravel version is 5.8. I'm getting this error when I install the app in a new shop. Any help?
 Thanks.

**Comment by frexiz** [comment]
![image](https://user-images.githubusercontent.com/5787064/54622906-28efa800-4a73-11e9-8d04-c16aa7626ba5.png)

**Comment by ohmybrew** [comment]
I am not sure. I have not fully checked out 5.8 . Check your uninstall job and compare it to the package's and see if the interfaced and traits match up.

**Comment by ohmybrew** [comment]
Someone had a similar issue online and stated:

"Solved! Remove all /bootstrap/cache/ files Then clear cache (php artisan cache:clear) And finaly clear views (php artisan view:clear)"

**Comment by frexiz** [comment]
> Someone had a similar issue online and stated:
> 
> "Solved! Remove all /bootstrap/cache/ files Then clear cache (php artisan cache:clear) And finaly clear views (php artisan view:clear)"

This fixed my issue. Thanks.

**Comment by JDSHINDE** [comment]
i got same issue after update and i also clear catch and view but still get error

![Screenshot_55](https://user-images.githubusercontent.com/46311508/63667599-192e7980-c7f2-11e9-9636-f1e23c7aa834.png)
