### ISSUE TITLE
Facing issue on installation of app.

### ISSUE THREAD

**Issue by azarrar** [ohmybrew/laravel-shopify#202]
Hello, I have setup a public app in shopify and after setting up all provided steps mention in your app. it successfully install app in my developement store and store information of current store in database table "demo.shops" but then redirect to a page.

"Requests to the server have been blocked by an extension."

Please provide help regarding it.

**Comment by brianakidd** [comment]
If you built an embedded app, is your webserver set to allow loading in an iframe?

**Comment by brianakidd** [comment]
For example, when I deploy using Laravel Forge, I have to comment out this X-Frame-Options setting in NGINX:

`# add_header X-Frame-Options "SAMEORIGIN";`

**Comment by ohmybrew** [comment]
Yup as brianakidd said, and also make sure it's HTTPS.

**Comment by azarrar** [comment]
Please let me know, How to check my https are valid for public app requirement?

**Comment by ohmybrew** [comment]
There's several ways. You could use a self signed certificate for localhost development. This wiki entry has some guides https://github.com/ohmybrew/laravel-shopify/wiki/Developing-Locally

Other than that explore and see what others have done :)
