### ISSUE TITLE
Middlewares not working with laravel 5.7

### ISSUE THREAD

**Issue by mat-dropshipspy** [ohmybrew/laravel-shopify#203]
I try to install it, and I can embed code to shopify admin if I remove middleware... but if I leave middleware it showing only a blank page. 

code below returning blank page (just shopify navbars and title bars)
Route::get('/', function () {
    return var_dump('here');
})->middleware('auth.shop')->name('home');

this one returning 'string(4) "here"'
Route::get('/', function () {
    return var_dump('here');
})->name('home');

any idea why I cannot use middleware?

**Comment by ohmybrew** [comment]
I pulled in your #205 thanks. Will issue a patch release tomorrow for it.
