### ISSUE TITLE
Proxy App gives me 404

### ISSUE THREAD

**Issue by fbunadi** [ohmybrew/laravel-shopify#204]
Hi,

I've setup proxy app in shopify with the following details
Subpath prefix: a
Subpath: customer-meta

Proxy URL: https://[our-domain]/proxy

The route in web.php

Route::get('/proxy', function () {
   return response('Hello, world!', 200)->withHeaders(['Content-Type' => 'application/liquid']);
})->middleware('auth.proxy');

When I go to https://[shop].myshopify.com/a/customer-meta, it gives me 404 - nginx page. This is the url for the 404 page https://[shop].myshopify.com/proxy?shop=[shop].myshopify.com&path_prefix=%2Fa%2Fcustomer-meta&timestamp=1553486438&signature=[signature]

If I comment out the rewrite rule in /public/.htaccess, it displays the app proxy page correctly.

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    **#RewriteRule ^ %1 [L,R=301]**

However, this solution makes the Application page in Shopify Admin not working (404 page)
<img width="892" alt="Screen Shot 2019-03-25 at 3 03 00 pm" src="https://user-images.githubusercontent.com/911656/54894514-1bbd3800-4f0f-11e9-9773-9bacd86b92b7.png">

Can anyone help me solving this issue? Thank you!

**Comment by khiconit** [comment]
It must be: `https://[shop].myshopify.com/a/customer-meta/`

**Comment by ohmybrew** [comment]
Given it works if you remove your rule, this seems to be a server issue, not a code one? Will leave open for a couple more days if you have any more insight, right now I can't reproduce on my two test installs.

**Comment by fbunadi** [comment]
I found that shopify added a '/' at the end of the app proxy url, just like khiconit said. Because of this the .htaccess rule kicked in and redirect the page to [request uri, i.e shopify url]/[proxy url] instead of just staying in the laravel host url/proxy. After I changed the .htaccess rewrite rule to RewriteRule $1 [L,R=301], the app proxy works and it also doesn't affect the admin page.
