### ISSUE TITLE
Suggest verify domain when install app

### ISSUE THREAD

**Issue by khiconit** [ohmybrew/laravel-shopify#206]
Sometimes our customer fill all link in to Install app page
example: https://yourstore.myshopify.com/abc/xyz, so app will can't be install
I  recommend you should get domain only
here is my suggestion:
```php
    public function sanitizeShopDomain($domain)
    {
        if (empty($domain)) {
            return;
        }

        $configEndDomain = Config::get('shopify-app.myshopify_domain');
        $regex = '/([\w\-\_\d]+\.'.$configEndDomain.')/i';
        if(preg_match($regex,  $domain,$matches))
        {
            $domain = $matches[0];
        }
        //$domain = preg_replace('/https?:\/\//i', '', trim($domain));

        if (strpos($domain, $configEndDomain) === false && strpos($domain, '.') === false) {
            // No myshopify.com ($configEndDomain) in shop's name
            $domain .= ".{$configEndDomain}";
        }

        // Return the host after cleaned up
        return parse_url("http://{$domain}", PHP_URL_HOST);
    }

```

**Comment by ohmybrew** [comment]
Thats exactly what the function does without modifications, [tests work for it](https://github.com/ohmybrew/laravel-shopify/blob/master/tests/ShopifyAppTest.php#L63).

Theres something else going on if thats the case. Can you explain what is happening?

**Comment by ohmybrew** [comment]
Ah! Actually #205 might be why you're experiencing this issue :) just noticed the change, which is where this issue would happen for you.

Should resolve when I do a new patch release.
