### ISSUE TITLE
Reactivate user charge ?

### ISSUE THREAD

**Issue by frexiz** [ohmybrew/laravel-shopify#207]
Hello, in my AfterAuthanticate job  I check if the user is reinstalling his shop and I check the first activation date of the previous charge and the canceled day. For example, he deactivated the app 15 days before the recurring payment. How can I reactivate the same charge_id with 15 days trial?

I saw that Shopify has: Activates a previously accepted recurring application charge
/admin/recurring_application_charges/#ID/activate.json

**Comment by ohmybrew** [comment]
You need to create a new charge, the old won't activate. There's logic in the billing controller to already pull their last charge details and work out the remaining trial days if any and create a new charge
