### ISSUE TITLE
Performing user creation during shop authentication

### ISSUE THREAD

**Issue by eleazargan** [ohmybrew/laravel-shopify#208]
How can I intervene the shop authentication process and create a user based of the response that has been received. I'm aware that the response after authenticating with Shopify will have the user credential. Is there any controller that I can override? Thanks.

**Comment by ohmybrew** [comment]
All [controllers are a trait](https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/Traits/AuthControllerTrait.php). So you can effectively override the auth functionality if you want... by including the trait and making a route to your controller to override the package route.

If you just need to make a user though, AfterAuthenticate job would be a good option, you can set it to run inline (no background dispatching). This way, you can check if a user exists for the shop, if not, simply inject one in, and it will do it before they ever see the landing page of your app.

**Comment by eleazargan** [comment]
I’m dispatching AfterAuthenticate job to a queue because the job will do some heavy lifting and it will be blocking if I run it online. So I suppose it’s not possible to get user from the shop right? And using rest API to get user is not a good way as it only works for Shopify Plus shops.

**Comment by ohmybrew** [comment]
Oh I see I thought you meant Laravel User.

You want to grab `associated_user` from the Oauth request?

IE:

```json
  "associated_user": {
    "id": 902541635,
    "first_name": "John",
    "last_name": "Smith",
    "email": "john@example.com",
    "email_verified": true,
    "account_owner": true,
    "locale": "en",
    "collaborator": false
  }
```

**Comment by eleazargan** [comment]
Yea that's what i want to achieve. I have to override the auth trait in order to achieve that right?

**Comment by ohmybrew** [comment]
Yes, but I should also build this in as well since it would beneficial to the package.

**Comment by eleazargan** [comment]
Ah cool! Thank you. Would be nice if you could update this issue after the changes has been done so that I can update my package. 😁

**Comment by ohmybrew** [comment]
[This commit on the dependant package](https://github.com/ohmybrew/Basic-Shopify-API/commit/59332a23c48c010c5255de30caf2ed55d67ca92d) will enable this, I have to build a config option into this package to support it... stay tuned.

**Comment by eleazargan** [comment]
@ohmybrew is this feature tested for the new release?

**Comment by ohmybrew** [comment]
Yes, tests now in and passing, just need some physical tests.
