### ISSUE TITLE
How do I create application credit if customer re-install?, I see no log for charge_id

### ISSUE THREAD

**Issue by nonghinh** [ohmybrew/laravel-shopify#209]

**Comment by ohmybrew** [comment]
You can not make an application credit on an old discontinued charge. If they reinstall, they'll have a new charge.

**Comment by nonghinh** [comment]
@ohmybrew Thank you
So,  I want to refund the balance of the customer when they uninstall app with time using app less than 30 days. Can I do that?

**Comment by ohmybrew** [comment]
If they uninstall the app, all API access is gone, you can do nothing at that point. You would have to refund them in another way (manually).

**Comment by brianakidd** [comment]
Once they uninstall your app, the api token stored with the shop is invalidated so you won’t be able to make any more requests with that token.

**Comment by nonghinh** [comment]
I have one more question:
I want to know that If the charge app of customers expired after 30 days and they do not pay on time, I will show an alert for theme. Can I do it? 
- Or I have to make a cronjob and run every day to request status of app charge?

**Comment by ohmybrew** [comment]
Shopify handles the billing. Billing goes through the card attached to the store. When the shop gets behind on billing for Shopify monthly fees, the shop is frozen along with all charges. The owner can not access aspects of their store until they fix the billing issue. You can check the status of the charge if you like which has many statuses like accepted, frozen, etc

**Comment by nonghinh** [comment]
Many thanks
