### ISSUE TITLE
Billing capped amount and terms

### ISSUE THREAD

**Issue by brianakidd** [ohmybrew/laravel-shopify#21]
Hello, still enjoying the package.  Do you have any plans of adding a means to provide a capped amount and terms in cases where there will be a recurring charge and a periodic usage charge?

Here's the documentation: https://help.shopify.com/api/reference/recurringapplicationcharge#create

Thanks.

**Comment by brianakidd** [comment]
Yes, that's correct.  The best pricing model for my app is usage-based pricing so I'll need to provide the capped amount and terms when the recurring application charge is created.  If one of these fields is populated, the other is required but, as you know, these fields aren't required so shouldn't cause any breaking changes.

Thanks for the consideration.

**Comment by ohmybrew** [comment]
I'll add this in either today or tomorrow sure.

**Comment by ohmybrew** [comment]
Hey @brianakidd #22 should solve this, its merged in, tests passed. Released as v2.2.0, should be in Composer. Theres a couple new entries in `config/shopify-app.php`

If you're using ENV vars, set `SHOPIFY_BILLING_CAPPED_AMOUNT` and `SHOPIFY_BILLING_TERMS` to get it to work.

Thanks!

**Comment by brianakidd** [comment]
Thanks so much!

**Comment by ohmybrew** [comment]
Ill close for now, reopen if theres a issue. Cheers.
