### ISSUE TITLE
Facing issue on public app after installation.

### ISSUE THREAD

**Issue by azarrar** [ohmybrew/laravel-shopify#210]
I have created a public app from partner account and installed on development store, app installed sucessfully, but when i load my app in firefox it work fine, but when i am loading it on chrome it is showing a broken page with a message "Requests to the server have been blocked by an extension." in chrome console it is showing 
Refused to frame 'example.com/ because it violates the following Content Security Policy directive: "frame-src app.myshopify.io *.shopifyapps.com *.myshopify.io *.myshopify.com https://* shopify-pos://*".
I have verified my SSL from site 
https://www.sslshopper.com/ssl-checker.html#hostname=example.com

also i have set  $response->headers->set('X-Frame-Options', 'SAMEORIGIN', false); in laravel settings.

I am not able to get this issue. please help me regarding this issue.

**Comment by ohmybrew** [comment]
Sorry I don't have anything to offer it could be a number of things from an insecure request or SSL issue, try setting the CSP and X frame headers on the server instead of Laravel.

**Comment by chandlerwilcox88** [comment]
I have this same issue. Did you fix the CSP issue?
