### ISSUE TITLE
Authorization does not use custom domain

### ISSUE THREAD

**Issue by eleazargan** [ohmybrew/laravel-shopify#211]
When user authorize with their custom domain, the back-end still store the .myshopify domain instead of the custom domain. This will conflict if an app wants to build a URL for that store.
Use-Case:
1. User authorize with shopify app.
2. Back-end store .myshopify domain of the store instead of custom domain.
3. Back-end need to build a product URL for the user, the domain is .myshopify instead of custom domain. This will make user feels like it's from a different site.

**Comment by ohmybrew** [comment]
Auth with Shopify domain is always required as it's a permanent domain name, where their custom domain can change. If you need the custom domain, you will need to make an API call to the store to grab it.

**Comment by eleazargan** [comment]
Ah alright. That make sense. I am grabbing the custom domain through the shop API. Just wondering why shopify_domain is always the .myshopify domain instead of custom domain even when a user uses the custom domain to authenticate. Thanks.

**Comment by ohmybrew** [comment]
Closing if it makes sense!
