### ISSUE TITLE
Extending Base Shop Model Error

### ISSUE THREAD

**Issue by eleazargan** [ohmybrew/laravel-shopify#213]
Extending Shop Model will cause the authentication to fail because it fails to set the `shopify_domain` value.

```SQLSTATE[HY000]: General error: 1364 Field 'shopify_domain' doesn't have a default value (SQL: insert into `shops` (`namespace`, `updated_at`, `created_at`) values (, 2019-04-09 08:05:58, 2019-04-09 08:05:58))```

This happens when the child model has its own `protected $fillable` thus the child model is not able to read the `shopify_domain` in parent model as it is protected.

My temporary fix, I added `shopify_domain` to the child model that extends `shop` model.

**Comment by ohmybrew** [comment]
This is a known issue. You can not include properties like that in a trait. So you will need to duplicate all properties in here https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/Models/Shop.php

And add it to your model.

**Comment by eleazargan** [comment]
Alright thanks.
