### ISSUE TITLE
Shopify Versioning

### ISSUE THREAD

**Issue by fyroc** [ohmybrew/laravel-shopify#214]
Shopify just announced a new API and API versioning.

Will you be supporting this in the future?

https://www.shopify.com/partners/blog/api-versioning-at-shopify?utm_medium=email&utm_source=exacttarget&utm_campaign=api_version_active_190409

**Comment by ohmybrew** [comment]
Yup I've been following along at work. Good to open a issue for it. Although I've been on the fence as to weather I need to do anything. The underlying package, basic-shopify-api simply let's you define the target routes so there's no breakage here. I can only imagine adding a helper to the init of the API where you could specify a version and the package would auto attach it for you. This might be the path I go for. Ie:

$api->setVersion('unstable')

And a whitelist for routes which do not have versioning.

**Comment by ohmybrew** [comment]
Decided to go ahead and do it!

[Docs](https://github.com/ohmybrew/Basic-Shopify-API#api-versioning) / [Commit](https://github.com/ohmybrew/Basic-Shopify-API/commit/d88d036a00210497409e4b9f550cc279adcd3a74).

Added support into this package as a config option as well, [commit](https://github.com/ohmybrew/laravel-shopify/commit/f93fb2b82da95f2ea9418ca85cf28b387aae48fe).

Will be part of next release (which is soon as I fix some tests up that broke from supporting new auth stuff).

Thanks!

**Comment by fyroc** [comment]
You work fast!

**Comment by ohmybrew** [comment]
Now in master, passing, just need some physical tests.
