### ISSUE TITLE
[QUESTION] Custom Guard which uses the Shop-model

### ISSUE THREAD

**Issue by bilfeldt** [ohmybrew/laravel-shopify#215]
I am building an application using this awesome package and my app has a settings part. Here the logged in user is capable of editing the _settings_-model which is related to the _shop_-model. I wanted to use [Policies](https://laravel.com/docs/5.8/authorization#creating-policies) for this, as the settings are essentially a resource related to the authenticated shop.

During this, then I started looking into making a custom [Guard](https://laravel.com/docs/5.8/authentication#introduction) for the shop as I think that would make sense. I noticed that the package documentation mentioned nothing about this, and was wondering if there might be other users wondering about this.

Do anyone have any experience in making a Guard for this package? I was thinking that it would make sense to add a new `shopify` guard to the `config/auth.php` file like so:
```php
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'shopify' => [
            'driver' => 'session',
            'provider' => 'shops',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],
```
which uses the `shops`-provider defined in the same file:
```php
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

        'shops' => [
            'driver' => 'eloquent',
            'model' => App\Shop::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
```

But I am currently unsure how to successfully authenticate using such a custom Guard, and would appreciate any inputs from others having experience with this.

**Comment by ohmybrew** [comment]
Maybe "Closure Request Guards" might help here https://laravel.com/docs/5.8/authentication

The entire provider process seems overkill for the shop since there's no real credentials to check like jwt or database login.

**Comment by bilfeldt** [comment]
Thanks for your answer.

I am just thinking that all of the app pages, including configuration/settings, are behind the `AuthShop`  middleware and all webhooks are behind the `AuthWebhook` middleware, so I was wondering if it should not be possible to setup a Guard that uses the shop-model instead of the user-model - or am I perhaps missing something :/

**Comment by ohmybrew** [comment]
I think thats what the closure guard would do, you'd use the Shop model in the closure to get the shop. I am not too sure to be honest, I have not made custom guards for Laravel.

**Comment by ohmybrew** [comment]
Digging into it more. It seems a few things would need to happen. Not even sure its possible due to theres no "login" credentials, but heres my thoughts...

A) Shop model would need to implement [Authenticatable](https://laravel.com/api/5.8/Illuminate/Contracts/Auth/Authenticatable.html)

B) A custom provider for auth, example:

```php
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Auth;
use App\Extensions\ShopProvider;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * Register any application authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

        Auth::provider('shop', function ($app, array $config) {
            // Return an instance of Illuminate\Contracts\Auth\UserProvider...
            return new ShopProvider();
        });
    }
}
```

You'd then edit `auth.php` to be:

```php
'providers' => [
    'users' => [
        'driver' => 'shop',
    ],
],
```

Edit `guards.php` to be:

```php
'guards' => [
    'web' => [
        'driver' => 'session',
        'provider' => 'shops',
    ],
],
```

C) A custom provider (ShopProvider) which implements the following interface

```php
<?php

namespace Illuminate\Contracts\Auth;

interface UserProvider {
    public function retrieveById($identifier);
    public function retrieveByToken($identifier, $token);
    public function updateRememberToken(Authenticatable $user, $token);
    public function retrieveByCredentials(array $credentials);
    public function validateCredentials(Authenticatable $user, array $credentials);
}
```

retrieveById -> shop.id
retrieveByToken -> shop.shopify_token?

The other 3 methods are not valid for a shop, not sure it could be implemented.

D) Modify a custom Shop model to implement this interface:

```php
<?php

namespace Illuminate\Contracts\Auth;

interface Authenticatable {

    public function getAuthIdentifierName();
    public function getAuthIdentifier();
    public function getAuthPassword();
    public function getRememberToken();
    public function setRememberToken($value);
    public function getRememberTokenName();

}
```

**Comment by bilfeldt** [comment]
These are great thoughts!

> Not even sure its possible due to theres no "login" credentials...

My thoughts were that there **are** indeed login credentials since Shopify is using two different authentications:

- Embedded Apps: Uses OAuth as described [here](https://help.shopify.com/en/api/embedded-apps/embedded-app-sdk/oauth).
- Webhooks: Shopify will include three headers as described [here](https://help.shopify.com/en/api/reference/events/webhook):
  - **X-Shopify-Topic**: Example `orders/create`, not important for authentication
  - **X-Shopify-Shop-Domain**: This is the user_n_ame of the shop so to say. It is the domain, example: `johns-apparel.myshopify.com`
  - **X-Shopify-Hmac-SHA256**: This is the _password_ so to say. It is a hash of the request verifying that it has not been modified. See details in [Verifying webhooks](https://help.shopify.com/en/api/getting-started/webhooks#configuring-webhooks)

Currently the [AuthShop](https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/Middleware/AuthShop.php) middleware checks for an active session or redirects to Oauth authentication. The [AuthWebhook](https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/Middleware/AuthWebhook.php) middleware currently checks the Hmac.

p.s. There are two typos in your post for B. Just in case someone finds this later on:
```
// Return an instance of Illuminate\Contracts\Auth\UserProvider...
```
should be (`ShopProvider` instead of `UserProvider`):
```
// Return an instance of Illuminate\Contracts\Auth\ShopProvider...
```
and the providers should say `'shops' => [` instead of `'users' => [`

**Comment by ohmybrew** [comment]
Hmm but that's a signature for the request which changes. For policies, I am just not sure it'll fit in off top my head. Not unless maybe you link a shop  to a dummy user?

**Comment by bilfeldt** [comment]
As I see it, then authentication does not necessarily have to do with a _user_. It could also be another model like a _team_ or in our case a _shop_. It simply means a way of authenticating exactly _which_ shop that made the request (and not another shop pretending to be someone else).

I have found [this](https://medium.com/@sirajul.anik/laravel-api-authenticate-user-with-custom-driver-different-table-using-auth-middleware-fa2cabec2d61) brilliant article describing the details of adding a custom authentication scheme, which is really close to your solution.

You have also been so kind as to put details on the [Shop Installation and Authentication Process](https://github.com/ohmybrew/laravel-shopify/wiki/Shop-Installation-and-Authentication-Process#fresh-shop) in the Wiki.

As I see it, then we should look for the `shop` and `hmac` of each and every request. We could consider this like a _username_ and a _password_. If they match, then we know that the request came from the given Shopify shop (authenticated). For webhooks then it will be in the headers `X-Shopify-Shop-Domain` and `X-Shopify-Hmac-SHA256` while for page loads (like going to the apps custom settings page) then it will be query parameters `hmac` and `shop`. I am not completely sure how it works for [Admin links](https://help.shopify.com/en/api/embedded-apps/app-extensions/shopify-admin/app-admin-access) and [Bulk action links](https://help.shopify.com/en/api/embedded-apps/app-extensions/shopify-admin/bulk-action-links) yet.

I imagine that we create two new guards like so:
```
'guards' => [
    // this will be like auth:shopify instead of auth:web
    // name the guard anything you want
    'shopify' => [
        // hmac is what we defined inside Auth::extend
        // you can name this anything BUT should match with 
        // Auth::extend('HERE');
        'driver' => 'hmac',
        'provider' => 'shops',
    ],
],
```
then we can implement the new classes `HmacGuard` which implements `Illuminate\Contracts\Auth\Guard`. This class should try to authenticate using either the header or the query parameters depending on what is present (like the Laravel API authentication works with `api_token` that can be either a header or a query parameter)

Doing something like this would mean that routes could be defined like:
```php
<?php
// routes/web.php
// shopify is the guard name, we defined above in config/auth.php
Route::group(['middleware' => 'auth:shopify'], function(){
    // AUTHENTICATED shop here.
    // Get the currently authenticated shop: Auth::user();

    // define routes here

});
```

**Comment by ohmybrew** [comment]
Ah good find on the article that's really detailed. If you manage to make any progress with it and find a working solution, feel free to make a wiki entry for others.On Apr. 16, 2019 20:35, Anders Bilfeldt <notifications@github.com> wrote:As I see it, then authentication does not necessarily have to do with a user. It could also be another model like a team or in our case a shop. It simply means a way of authenticating exactly which shop that made the request (and not another shop pretending to be someone else).
I have found this brilliant article describing the details of adding a custom authentication scheme, which is really close to your solution.
You have also been so kind as to put details on the Shop Installation and Authentication Process in the Wiki.
As I see it, then we should look for the shop and hmac of each and every request. We could consider this like a username and a password. If they match, then we know that the request came from the given Shopify shop (authenticated). For webhooks then it will be in the headers X-Shopify-Shop-Domain and X-Shopify-Hmac-SHA256 while for page loads (like going to the apps custom settings page) then it will be query parameters hmac and shop. I am not completely sure how it works for Admin links and Bulk action links yet.
I imagine that we create two new guards like so:
'guards' => [
    // this will be like auth:shopify instead of auth:web
    // name the guard anything you want
    'shopify' => [
        // hmac is what we defined inside Auth::extend
        // you can name this anything BUT should match with 
        // Auth::extend('HERE');
        'driver' => 'hmac',
        'provider' => 'shops',
    ],
],

then we can implement the new classes HmacGuard which implements Illuminate\Contracts\Auth\Guard. This class should try to authenticate using either the header or the query parameters depending on what is present (like the Laravel API authentication works with api_token that can be either a header or a query parameter)
Doing something like this would mean that routes could be defined like:
<?php
// routes/web.php
// shopify is the guard name, we defined above in config/auth.php
Route::group(['middleware' => 'auth:shopify'], function(){
    // AUTHENTICATED shop here.
    // Get the currently authenticated shop: Auth::user();

    // define routes here

});

**Comment by bilfeldt** [comment]
If I manage to find a solution for this, then I will for sure post a Wiki and perhaps make a PR for a new Authentication guard that could be included in the package.

NOTE for others: To disable the `auth` middleware have a look at the `src/ShopifyApp/resources/routes.php` file.

**Comment by ohmybrew** [comment]
Thanks, please do!

**Comment by jtrachez** [comment]
> If I manage to find a solution for this, then I will for sure post a Wiki and perhaps make a PR for a new Authentication guard that could be included in the package.
> 
> NOTE for others: To disable the `auth` middleware have a look at the `src/ShopifyApp/resources/routes.php` file.

Hi, this is a very interesting discussion. Have you been able to advance on this problem? Do you need help ? Because I am currently looking for a solution too. For my problem, I have a table settings that is related to shops, I would like to use the Guard laravel to "protect" the settings for his own shop
