### ISSUE TITLE
Getting user from auth

### ISSUE THREAD

**Issue by eleazargan** [ohmybrew/laravel-shopify#218]
Is there a docs for getting the user from auth?

**Comment by fyroc** [comment]
Yes. The very first thing in “Usage” in the wiki.

https://github.com/ohmybrew/laravel-shopify/wiki/Usage

**Comment by ohmybrew** [comment]
@fyroc As said yes, perfect :)

Essentially it grabs the shopify_domain from Laravel's session, used the Shop model to find that same shop and return that shop with API access ready to go.

**Comment by eleazargan** [comment]
Yea I tried to use
```
$shop = ShopifyApp::shop();
$user = $shop->api()->user;
```
But it always returns null

**Comment by fyroc** [comment]
Are you calling it via the web or api route?

**Comment by eleazargan** [comment]
Web route.

**Comment by eleazargan** [comment]
Oh wait a sec, the per-user auth thingy is not in Release 6.0.0? Gonna be in next release?

**Comment by ohmybrew** [comment]
Per user authentication is not available until release. Which is ready as of yesterday, just needs some physical tests to ensure it's ok

**Comment by ohmybrew** [comment]
Physical tests seem good, getting user data just fine. Will be prepping releasing.

**Comment by ohmybrew** [comment]
7.0.0 released
