### ISSUE TITLE
Customise Login URL

### ISSUE THREAD

**Issue by akkivaghasiya5** [ohmybrew/laravel-shopify#221]
I want to change login url of the app from `/login` to `/`. So I also have to change `/` url of the app to `/home`. But route names will be same as named in the package. I have successfully changed url of the home route to `/home`. But I can't override `/login` url to `/`.

Here is my web.php routes

```
Route::get('/', function() {
    return view('landing');
})->name('login');

Route::group(['middleware' => ['auth.shop']], function () {

    Route::get('home', function () {
        return view('welcome');
    })->name('home');
});
```

Here is list of routes (php artisan route:list)
![download](https://user-images.githubusercontent.com/19259101/56214901-57fe3700-607c-11e9-976d-82da86154695.png)

**Comment by ohmybrew** [comment]
I think you would need to switch the position of the package provider to come either before or after the route provider

**Comment by akkivaghasiya5** [comment]
@ohmybrew 
Your suggestion worked. Thanks
