### ISSUE TITLE
billable not work

### ISSUE THREAD

**Issue by JDSHINDE** [ohmybrew/laravel-shopify#222]
here is my .env file code
and i created plan table for check plan
SHOPIFY_APP_NAME="Shopify Quizify App"
SHOPIFY_API_KEY="xyz"
SHOPIFY_API_SECRATE="xyz"
SHOPIFY_BILLING_ENABLED=1
SHOPIFY_BILLING_TYPE=recurring
SHOPIFY_BILLING_PLAN_NAME="test"
SHOPIFY_BILLING_PRICE=4.99
SHOPIFY_BILLING_TEST=1
SHOPIFY_BILLING_FREEMIUM_ENABLED=0

here is afterauthenticatejob.php file

public function handle()
     {

       if ($this->shop->finished_setup) {
           // Setup has finished, this should've ran by now, kill it
           return;
       }

       if (!$this->shop->isGrandfathered()) {
           $planName = $this->shop->api()->rest('GET', '/admin/shop.json')->body->shop->plan_name;
           if ($planName === 'affiliate' || $planName === 'staff_business')
           {
               $shop->grandfathered = true;
               $shop->finished_setup = true;
               $shop->save();
           }
       }
    }
![Screenshot_8](https://user-images.githubusercontent.com/46311508/56281717-f34de580-612a-11e9-8545-8a5ff7d6781d.png)

**Comment by ohmybrew** [comment]
What version is this? I don't recognize that code is this custom? The error lies in that you're using $shop instead of $this->shop from what I can tell

**Comment by ohmybrew** [comment]
Ohhhh is this one of the code tips in wiki? If so it may have typos by looks of it, was copied from a contributor

**Comment by tobiasdalhof** [comment]
`$shop` is undefined! I have fixed the example at https://github.com/ohmybrew/laravel-shopify/wiki/Free-Access-Based-on-Shopify-Plan#implementation

**Comment by ohmybrew** [comment]
@tobiasdalhof thanks!
