### ISSUE TITLE
oauth issue with ngrok 

### ISSUE THREAD

**Issue by muhammadasfar** [ohmybrew/laravel-shopify#224]
Hi

I am facing this issue **400 Oauth error invalid_request: The redirect_uri is not whitelisted** with ngrok but its work fine over my https staging server. I have checked ngrok urls in Shopify app and credentials in .env file

Using Laravel 5.8.7
ohmybrew/laravel-shopify v6.0.0

**URL** https://xyzdomain.myshopify.com/admin/oauth/authorize?client_id=361b26bfe15086cae6a0f705031a821d&scope=read_script_tags&redirect_uri=https%3A%2F%2Fcb3169ec.ngrok.io%2Fauthenticate
**Error**
![image](https://user-images.githubusercontent.com/38552865/56361825-cae4ea80-6201-11e9-9657-98954eaa45fb.png)

**Comment by ohmybrew** [comment]
Ngrok has odd issues with HTTPS even for webhooks and such. There's nothing I can do on my end to help with this.

**Comment by muhammadasfar** [comment]
okay, I am closing this issue.
