### ISSUE TITLE
Remove app login and add this as an additional feature on existing app

### ISSUE THREAD

**Issue by stacybot123** [ohmybrew/laravel-shopify#225]
Hi,

I have an existing app with login and billing setup for it. I am trying to add shopify integration as an additional feature on my app. I am going through the Wiki, 
Is there a way so not to include the default login and billing feature of the package and use every other functionality on the package. 

So instead of the user loggin in with their shop url , they can click the button enter their shop url and connect. I have installed the package but its overriding my default login

**Comment by ohmybrew** [comment]
I am not too sure how I could go about that... is there a package that does optional routes? I could add an option to the provider to turn all route on or off but I believe that's all I could do.

**Comment by stacybot123** [comment]
@ohmybrew That would be awesome!

**Comment by fyroc** [comment]
Some of these very specific requests could be solved by just forking the project and removing the routes in the fork.

**Comment by ohmybrew** [comment]
True yes. I could also prefix all routes in the future with /shopify to avoid conflicts.

**Comment by stacybot123** [comment]
@ohmybrew  thanks! I will fork and change the routes
