### ISSUE TITLE
After Authen job inline true false wrong comment

### ISSUE THREAD

**Issue by serkandyck** [ohmybrew/laravel-shopify#228]
https://github.com/ohmybrew/laravel-shopify/blob/b71a3c6008fc356cdfa68b7d606b88d16670af24/src/ShopifyApp/Services/AuthShopHandler.php#L167
this line say if inline true job run on immediately

But shopify-app config say true = dispatch job for later
https://github.com/ohmybrew/laravel-shopify/blob/b71a3c6008fc356cdfa68b7d606b88d16670af24/src/ShopifyApp/resources/config/shopify-app.php#L291

**Comment by ohmybrew** [comment]
Good catch. Have solved this on master :) #fe18b3d
