### ISSUE TITLE
Homestead installation

### ISSUE THREAD

**Issue by alexlathwell** [ohmybrew/laravel-shopify#23]
Hey, do you know when you'll have the Homestead installation guide done?

I have everything setup with ngrok but when I go to the app in Shopify the page is blocked with the error:

> The webpage at [homestead .test domain] might be temporarily down or it may have moved permanently to a new web address.

Cheers

**Comment by ohmybrew** [comment]
Hey @alexlathwell I havent had a chance to do Homestead. Seems like a misconfigured setup, nothing to do with the repo specifically.

Heres an example of Valet: https://www.youtube.com/watch?v=vU8XrJQQPMo

If I add a Homestead setup to the docs (when I get time), I'll ping you :)

**Comment by ohmybrew** [comment]
Ah yes makes sense, they made that a requirement since summer of 2017. Glad
you're set up :)
