### ISSUE TITLE
[Feature] Billing plan Selection

### ISSUE THREAD

**Issue by ARKKYN** [ohmybrew/laravel-shopify#233]
1. Please Add an option to select a billing plan based on Shopify plan
2. Please add options for selecting a billing plan willing to purchase

**Comment by ohmybrew** [comment]
Hi @ARKKYN 

This is not something I will be adding for the project as it has too much bias on what to do, and I want the package to remain lean. If you would like someone to select a plan, use our Freemium option (see wiki for info), and allow them to select a plan inside your app.

Thanks!

**Comment by iwaheedshahzad** [comment]
But thgis is need of the day,,,,You should add.

**Comment by Kyon147** [comment]
The package is designed to be as open as possible so developers can add the specific business logic they need on a case by case basis. If you need it you should add it yourself and not everyone will.

I've added a plan selection screen on one of my apps which allows you to select a plan based on usage, it's something you can do without too much issue and all of the base stuff is there thanks thanks to ohmybrew
