### ISSUE TITLE
Issue in Webhooks

### ISSUE THREAD

**Issue by azarrar** [ohmybrew/laravel-shopify#234]
Hi,

I'm trying to setup webhooks and I'm experiencing problems.
Laravel 5.8
I used your command from the wiki : php artisan shopify-app:make:webhook OrdersCreateJob orders/create and the file OrdersCreateJob is there in the App/Jobs folder.

Also added the webhook in the shopify-app.php as mentioned.

'webhooks' => [
    [
        'topic' => 'orders/create',
        'address' => 'https://xxxxxxx/webhook/orders-create'
    ],
],
If I make a get request on /admin/webhooks.json, the webhook is not showing in my development store where i have installed my public app from partner account.

**Comment by azarrar** [comment]
I have also added in in my config file ..

        /*
    |--------------------------------------------------------------------------
    | Shopify API Grant Mode
    |--------------------------------------------------------------------------
    |
    | This option is for the grant mode when authenticating.
    | Default is "offline", "per-user" is available as well.
    | Note: Install will always be in offline mode.
    |
    */

    'api_grant_mode' => env('SHOPIFY_API_GRANT_MODE', 'offline'),

        /*
    |--------------------------------------------------------------------------
    | Shopify API Version
    |--------------------------------------------------------------------------
    |
    | This option is for the app's API version string.
    | Use "YYYY-MM" or "unstable". Refer to Shopify's documentation
    | on API versioning for the current stable version.
    |
    */

    'api_version' => env('SHOPIFY_API_VERSION', '2019-04'),

**Comment by ohmybrew** [comment]
@fyroc  probably the same issue yeah. still trying to see how I can produce

**Comment by ohmybrew** [comment]
I think the new release may solve this issue, may be related to the auth issue from #244
