### ISSUE TITLE
silly - redirect to shopify

### ISSUE THREAD

**Issue by tzookb** [ohmybrew/laravel-shopify#236]
I browsed through the past issues and docs and could not find it :/

I want that clients will get redirected to my app inside shopify view, currently they are on my own domain.

Flow:
- user installs my app, through install page or marketplace
- accepts all the needed items
- (current) gets redirected to my domain `app.com`
- (expected) I want him to be inside shopify `example.myshopify.com/admin/apps/myapp`

any idea what am I doing wrong?

sorry for the stupid question :|

**Comment by MCKLtech** [comment]
This is the correct flow as Shopify redirects to your domain for OAuth and then should automatically refresh back to Shopify, landing in the admin panel and your app. It happens almost instantly.

Where does your flow stop? What do you see?

**Comment by fyroc** [comment]
Is your app enabled as an embedded app?

**Comment by tzookb** [comment]
thanks

yes @fyroc embedded app is enabled

@MCKLtech 
this the flow
- user install my app
- redirected to shopify to approve permissions
- then he is redirected to my domain
- then he is stuck on my domain and not in shopify app page

**Comment by ncpope** [comment]
Can you post the code of your view?

**Comment by tzookb** [comment]
hey @ncpope 

just saw this part in the blade template:
```
            <script src="https://cdn.shopify.com/s/assets/external/app.js?{{ date('YmdH') }}"></script>
            <script type="text/javascript">
                ShopifyApp.init({
                    apiKey: '{{ config('shopify-app.api_key') }}',
                    shopOrigin: 'https://{{ ShopifyApp::shop()->shopify_domain }}',
                    debug: false,
                    forceRedirect: true
                });
            </script>
```

Im using react so I dont have it, but I'll use it.

any ideas on where I can find the api/docs for the
`shopify.com/s/assets/external/app.js`
file ?

Thanks!

**Comment by tzookb** [comment]
got it:
https://help.shopify.com/en/api/embedded-apps/embedded-app-sdk/initialization

thanks
