### ISSUE TITLE
Issue running AfterAuthenticationJob

### ISSUE THREAD

**Issue by cornerstonewebsystems** [ohmybrew/laravel-shopify#237]
Sorry if I've added this request in the wrong place.

I have setup a job to send an email to the Store user upon authentication, per instructions <a href="https://github.com/ohmybrew/laravel-shopify/wiki/After-Authentication-Job" target="_blank">here</a>

However upon authentication, I get the following error:

`Argument 1 passed to App\Jobs\AfterAuthenticateJob::__construct() must be an instance of App\Shop, instance of OhMyBrew\ShopifyApp\Models\Shop given, called in /home/vagrant/lshopify/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php on line 16`

My config/shopify-app.php has:

    'after_authenticate_job' => [
            'job' => App\Jobs\AfterAuthenticateJob::class,
            'inline' => env('AFTER_AUTHENTICATE_JOB_INLINE', false)
    ],

and my AfterAuthenticateJob is as follows:

`<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Support\Facades\Log;

use App\Mail\NewShopInstalled;
use Illuminate\Support\Facades\Mail;
use App\Shop;

use App\Collection;

class AfterAuthenticateJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected $shop;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(Shop $shop)
    {
        $this->shop = $shop;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        if (!$this->shop->auth_email) {
            $message = new NewShopInstalled($this->shop);
            Mail::to(env('CUSTOMER_EMAIL', 'shopify@example.com.au'))
                ->queue($message);
            $this->shop->auth_email = true;
            $this->shop->save();
        }
    }
}
`

Many thanks and apologies if my issue doesn't belong here.

**Comment by ohmybrew** [comment]
Hi there.

Remove `use App\Shop;`

Add after: `use OhMyBrew\ShopifyApp\Models\Shop;`.

**Comment by cornerstonewebsystems** [comment]
Thanks @ohmybrew works beautifully - much appreciated!
