### ISSUE TITLE
App proxy 401

### ISSUE THREAD

**Issue by fbunadi** [ohmybrew/laravel-shopify#239]
I've created an app proxy to create or update customer's metafield through ajax call to laravel-shopify. However I've been getting random issues of ajax failing with 401 status and I can't seem to replicate this issue consistently. 

Are you able to help me on this issue?
I'm using laravel framework 5.8.17

**Comment by ohmybrew** [comment]
If you're trying to POST, it will not work if I remember. Shopify proxies the request.

**Comment by fbunadi** [comment]
I use GET for the proxy request. It's very random cases. I can't replicate the issue however some of my users sending screenshot of getting 401 error and I checked my statistic page; 63% hits returning 401. My suspicion is access token expired, that's why it's 401. I'm just wondering if it's because I was using laravel-shopify version 6 so it's using online access token instead of offline?

**Comment by ohmybrew** [comment]
Theres always an offline token stored in the shop.

How do you have the route setup and what are you doing inside the controller for your proxy?

**Comment by fbunadi** [comment]
Shopify Theme Liquid:
$.ajax({
        method: "GET",
        crossDomain: true,
        url: "/a/customer-meta",
        data: $("#custmeta").serialize()
      })
      .done(function( response, textStatus, jqXHR ) {
          
          $( "#updatebutton" ).prop("disabled", false);
          $( "#updatebutton" ).html("SAVE / EDIT CHILD");
          
          if(response == 'success'){
            $( "#dialog-message" ).dialog({
              modal: true,
              buttons: {
                Ok: function() {
                  $( this ).dialog( "close" );
                  location.reload();
				}
              }
            });
            
          } else {
            $( "#dialog-error-message" ).dialog({
              modal: true,
              buttons: {
                Ok: function() {
                  $( this ).dialog( "close" );
                }
              }
            });
          }     
      })
      .fail(function( jqXHR, textStatus, errorThrown ) {
          $( "#updatebutton" ).prop("disabled", false);
          $( "#updatebutton" ).html("SAVE / EDIT CHILD");
          
          var errorMessage = jqXHR.status + ': ' + jqXHR.statusText + '\n';
          errorMessage += 'Please check your data and try again. If this error continues, please contact us for assistance.';
          
          alert('Error - ' + errorMessage);
      });

Apparently many users encounters $.ajax.fail condition, thus the 401 error message.

Laravel - Shopify:
This is the route 
Route::get('/proxy/children', 'AppProxyController@children')->middleware('auth.proxy');

This is the controller
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use OhMyBrew\ShopifyApp\Facades\ShopifyApp;
use Log;

class AppProxyController extends Controller
{
    //This function will retrieves input request from shopify page and do API request to Shopify to store customer metafield

    public function children(Request $request) {
    	$shop_request = $request->query();

        $customer_id = $request->customer_id;
        $rest_url = '/admin/customers/'.$customer_id.'/metafields.json';

        $metafield_object = ['cfirstname1', 'clastname1', 'cschool1', 'cclass1', 'cfirstname2', 'clastname2', 'cschool2', 'cclass2', 'cfirstname3', 'clastname3', 'cschool3', 'cclass3', 'cfirstname4', 'clastname4', 'cschool4', 'cclass4', 'cfirstname5', 'clastname5', 'cschool5', 'cclass5'];
		
        foreach($metafield_object as $key) {
            $value = $request->$key;

            if(!empty($value)) {
                $metafield_request = $this->postMetafield($rest_url, 'children', $key, trim($value), 'string');

                if($metafield_request === false){
                	Log::error('Customer ' . $customer_id . ' metafields request: ', $request->query());
                	return response('error', 200);
                }
            }
        }

    	Log::notice('Customer ' . $customer_id . ' metafields request: ', $request->query());
    	return response(  "success", 200 );

    }

    protected function postMetafield($url, $namespace, $key, $value, $type) {
        $shop = ShopifyApp::shop();
        $data = array('namespace' => $namespace, 'key' => $key, 'value' => $value, 'value_type' => $type);
        $request = $shop->api()->rest('POST', $url, array('metafield' => $data));
        if(!empty($request->body->metafield)){
            return true;
        } 

        if(!empty($request->body->errors)){
        	Log::error('Url: ' . $url . ', Namespace: ' . $namespace . ', Key: ' . $key . ', Value: ' . $value, $request->body->errors);
        }
        
        return false;
    }
}

This is the .env file

SHOPIFY_API_VERSION="2019-04"
SHOPIFY_API_GRANT_MODE="offline"

SHOPIFY_API_RATE_LIMITING_ENABLED=true
SHOPIFY_API_RATE_LIMIT_CYCLE=500
SHOPIFY_API_RATE_LIMIT_BUFFER=100

I am now using laravel-shopify version 7 instead of version 6.

**Comment by ohmybrew** [comment]
You can not do an ajax request on the /a/ Shopify proxy route, you'd need do the request to your domain

**Comment by fbunadi** [comment]
Thank you for the quick reply.

When I changed the ajax request to my domain, I get this error, 
Access to XMLHttpRequest at 'https://[domain]/proxy/children/?[data]' from origin '[shop url]' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ohmybrew** [comment]
You need to enable cors in your server config

**Comment by fbunadi** [comment]
Sorry to trouble you again. 

I've enabled cors in my /public/.htaccess and change the ajax request to my app domain (https://[app's domain]/proxy/children). I didn't get the CORS error anymore however I get 500 Internal Server error (ErrorException (E_NOTICE)
Undefined index: signature) 

It seems if I don't use the proxy url, Shopify doesn't automatically append the signature and shop to the url's parameters. Do I need to add anything else in my ajax request?

**Comment by fbunadi** [comment]
I added a log in AuthProxy.php and as I expected, the signature received from shopify doesn't match with local signature thus it produces 401 error.

2019-05-16 11:01:59] production.DEBUG: Signature: 6bd02b9755796833447a93db4ede181077b860ac4c54ec7c571222604cd54c5d signatureLocal: 1821cec8648cb750fcb3b4ae22a1242d194e05a90d1e6fdbc0320fbead226469

I checked the data and cannot see anything wrong with it. Do you have any idea why the signature can be different?

**Comment by ohmybrew** [comment]
Ah! Nope, I'll investigate this.

**Comment by ohmybrew** [comment]
So my tests are passing and they use the exact same example as provided by [Shopify ](https://help.shopify.com/en/api/guides/application-proxies) in calculating the signature.

How is this proxy request coming through? GET?

**Comment by fbunadi** [comment]
Yes, the request is coming through ajax with GET method. 

The hmac calculation isn't always failing. About 60% will match in 1 try. I myself cannot replicate the issue but the log shows quite a lot of unmatched hmac.

**Comment by ohmybrew** [comment]
I think there must be a difference in sorting some how. Still looking into it.

**Comment by ohmybrew** [comment]
Unable to reproduce still but I believe the issue boils down to how PHP and Ruby may differ in the sorting of the query array. Your request has very very similar keys and I'm wondering if it's messing up there.. going to write a script to compare how each sorts.

**Comment by fbunadi** [comment]
I think I might find a way to reproduce the issue. If I put in a trailing white space in one of the fields in the form (eg: Firstname: "YYY "), the signature given by shopify is different with the local signature.

**Comment by ohmybrew** [comment]
Confirmed, signature is different. Not really sure I can do anything about that... unsure what Shopify is doing on their side with whitespace.

**Comment by ohmybrew** [comment]
The inner library use's Shopify's recommendation for signature creation with PHP. So not sure what I can do here about whitespace... open to suggestions but I'll close now since its not something I can tackle.

**Comment by darrynten** [comment]
@fbunadi were you adding your own query params to the proxy URL?

**Comment by fbunadi** [comment]
Yes. It's a form submitting all the input values to the proxy URL.

**Comment by mohinpatwary** [comment]
@fbunadi 
**Could you please help me? How can I enable cors in my /public/.htaccess?**
**I've created a route in web.php for using middleware auth.proxy**

Right now, I've enabled Cors for the Kernel.php. If I create a route in the routes/api.php. Then it works fine.
![image](https://user-images.githubusercontent.com/24967072/99020747-76deeb00-2589-11eb-9bcd-4a1a09d17539.png)

**Comment by MGhufranKhalil** [comment]
is there any one can help me on  getting following error

"Invalid proxy signature."

please help
