### ISSUE TITLE
Can't get shop name from session

### ISSUE THREAD

**Issue by ahmadzissa** [ohmybrew/laravel-shopify#24]
Hello, I like your package, but I can't get the shop name   I read the documentation

and I used  facade class

`
use OhMyBrew\ShopifyApp\Facades\ShopifyApp;
	
return var_dump(ShopifyApp::shop());
`
but shop not exists  and if I use it without facades I can't call it statically and  I have to pass parameter to constructor 

 there for I tried to get it from session directly 

> return var_dump(\Session::get('shopify_domain'));

I get null  

so how can I get shop  name ??? 

Also the documentation dose state how can I have more than one charges plan   I hope you can improve it

**Comment by ohmybrew** [comment]
Closing for now as this does not seem to be a bug but a process thing? Re-open if you think not.
