### ISSUE TITLE
Issue in Billing process

### ISSUE THREAD

**Issue by casahuga** [ohmybrew/laravel-shopify#241]
We have a free access App, and inside the App the user can upgrade to pay. In the charges table, it creates the charges but when is an 'active' charge is it save as Null in the column Status. If I make and API call to shopify asking for that charge it returns that is active, and inside the Shopify Partners panel appears as active too. We are using version v4.0.2.

**Comment by ohmybrew** [comment]
It fills in with whatever Shopify returns.

**Comment by ohmybrew** [comment]
How are you upgrading the user?

**Comment by casahuga** [comment]
route('billing', ['plan_id' => 1]), having the plan 1 in the database. 
I did a test just after the client pays. I made an API call to /admin/api/2019-04/recurring_application_charges/'.$chargeId.'.json and it returns correctly the status.

**Comment by ohmybrew** [comment]
What did it fill in for the DB? Is billing_on, trial_ends_on filled in as well?

**Comment by casahuga** [comment]
is filled all expect the status. Of course, cancelled_on is null and the other that should be null

**Comment by ohmybrew** [comment]
Has this happened every time?

**Comment by casahuga** [comment]
yes

**Comment by ohmybrew** [comment]
Is this for a recurring or one time charge?

**Comment by ohmybrew** [comment]
In testing, I am getting `active` on accept... if this issue still persists, let me know.
