### ISSUE TITLE
419 weird error and not found on my app

### ISSUE THREAD

**Issue by tzookb** [ohmybrew/laravel-shopify#242]
I get this weird image on my code is deployed

<img width="570" alt="Screen Shot 2019-05-17 at 11 43 10" src="https://user-images.githubusercontent.com/3749973/57915276-13430700-7899-11e9-9172-9ff962dc38fe.png">

when working locally app works great.
But when deploying it breaks.

The domain is the domain of my app and not shopify
but I can see this page on my shopify app

** I created a shopify app especially for the deployment with the proper domains

**Comment by ohmybrew** [comment]
I don't have a clue hmm. What session engine are you using? I don't issue out a 419 to my knowledge.

**Comment by tzookb** [comment]
thanks @ohmybrew 
you are sharp!

it was an issue on live server with an I didnt get approved for "read_all_orders"
and SESSION_DRIVER was files

and we had 2 servers serving the  app :|

thanks!
