### ISSUE TITLE
theme json get issue

### ISSUE THREAD

**Issue by prajit21** [ohmybrew/laravel-shopify#243]
hello

you made amazing work in shopify and this made easy to work for us so huge thanks to you 

i m facing issue on retrive theme id here is my code :

code :

-----------------
```
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

use Illuminate\Http\Request;
use OhMyBrew\ShopifyApp\Facades\ShopifyApp;
use Log;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
    
    public function index() {
  
        $shop = ShopifyApp::shop();
        $request = $shop->api()->rest('GET', '/admin/themes.json');
        print_r($request);

    }
}
```
-------------------------------------

sorry if i made silly mistake please guide me how to retrive theme id 

thanks

**Comment by prajit21** [comment]
same i m getting issue with 

https://help.shopify.com/en/api/reference/online-store/asset

GET /admin/api/2019-04/themes/#{theme_id}/assets.json

in other all product and all is working but themes i m having issue

**Comment by ohmybrew** [comment]
Does your app have theme permission? I don't think this is a package issue.

**Comment by prajit21** [comment]
hi 
I made silly mistake and issue solved ,
thanks for help and guide me :)
you made amazing work in shopify and this made easy to work for us so huge thanks to you

**Comment by prajit21** [comment]
hello

can you guide me how can i make private apps ?

means where is configuration for private apps and public apps

thanks in advance for helping

**Comment by ohmybrew** [comment]
Sorry I am unable to, my time is pretty limited. Best of luck!

**Comment by timothysantos** [comment]
Hi @prajit21 I'm experiencing the same thing, any tips to solve this?
