### ISSUE TITLE
Display the installation page inside the APP

### ISSUE THREAD

**Issue by vishal-px** [ohmybrew/laravel-shopify#244]
Hi @ohmybrew 

I installed and steup this package. This is my package version: "ohmybrew/laravel-shopify": "^6.0".
Here, I getting one issue, I installed the app in the shopify store and from the app listing page I clicked on my app, but it showing me installation page: https://prnt.sc/nr0mmh

Please help me to resolve this issue.
Thank you.

**Comment by ohmybrew** [comment]
What browser are you using? I remember Safari had an issue. But it seems like the full-page redirect is not working.

**Comment by priyankagadhiya** [comment]
Hey @ohmybrew,

I am using chrome browser and have got the same issue. 
My package version: "ohmybrew/laravel-shopify": "^7.0".

Can you please help me out to resolve it?

Thanks in advance.

**Comment by vishal-px** [comment]
Hi @ohmybrew 
I'm also using chrome(Version 71.0.3578.80 (Official Build) (64-bit)) browser, In one of my app I used this version "ohmybrew/laravel-shopify": "^3.2" in this version I don't face that issue.

Thank you.

**Comment by ohmybrew** [comment]
This may mean something in the validation is not right... can you guide me through the steps you're doing to produce this?

**Comment by MCKLtech** [comment]
Just to add to the discussion, I also encounter this error. A fast way to do it sometimes is to push a build to Heroku and refresh the page (Whilst on an App page) and you'll be shown the default 'Enter your Domain to Login'

The only way to get back in is to go to Apps in the Shopify Admin and click your App, then the redirect works.

**Comment by ohmybrew** [comment]
Thanks ill try to solve this.On May 27, 2019 12:01, MCKLtech <notifications@github.com> wrote:Just to add to the discussion, I also encounter this error. A fast way to do it sometimes is to push a build to Heroku and refresh the page (Whilst on an App page) and you'll be shown the default 'Enter your Domain to Login'
The only way to get back in is to go to Apps in the Shopify Admin and click your App, then the redirect works.

**Comment by ohmybrew** [comment]
I believe I have this solved. I was able to reproduce, now I can not with the fix in place. Released an update.

If issue persists, please feel free to re-open ticket.

**Comment by priyankagadhiya** [comment]
Hi @ohmybrew  

Sorry, I was busy with some other work and forgot to confirm this. It does solve it in 7.1 version.
Thanks so much for your help :)

**Comment by veed76** [comment]
Hi @ohmybrew 
I faced this same issue https://prnt.sc/pggnft in version ^10.1

Thank you.

**Comment by Hujjat** [comment]
I have the same issue on version 10.2

just installed on a fresh laravel 6. 

Thank you
