### ISSUE TITLE
billing_redirect

### ISSUE THREAD

**Issue by cornerstonewebsystems** [ohmybrew/laravel-shopify#246]
Hi,

I need to send the user an email after they approve charges for a plan. I see that I need to change the SHOPIFY_BILLING_REDIRECT value however I am not sure how exactly this works. How do I best achieve this please?

ref: https://github.com/ohmybrew/laravel-shopify/wiki/Creating-a-Billable-App#billable-middleware

SHOPIFY_BILLING_REDIRECT="/url/path" for setting the path to handle the accepting or declining of the application charge (default: /billing/process)

Thanks

**Comment by ohmybrew** [comment]
Sorry maybe thats not clear.

Thats for if you want to handle your own billing logic.

I do not have a feature for redirecting after success it simply does this:

```
        // Go to homepage of app
        return Redirect::route('home')->with('success', 'billing');
```

You could tap into the flash message on the home route and redirect somewhere else.

**Comment by cornerstonewebsystems** [comment]
Thanks @ohmybrew for the speedy response.
I will look through the Request object on the Home Controller and inject the code there.

Keep up the great work!
