### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by Saadnine15** [ohmybrew/laravel-shopify#247]
App works well on browser which i used to install, but if i open installed app on other browser/pc it shows me login/install screen.

**Comment by ohmybrew** [comment]
Similar to another issue... can you please outline the steps you've taken so I can try and reproduce.

**Comment by Saadnine15** [comment]
1.Install app using this url https://loyaltypoints-new.herokuapp.com/ on shopify store using chrome
2.Open firefox and in your shopify store navigate to app, then any page from menu of app.

Below is the example of route
Route::resource('programDetails', 'ProgramDetailController')->middleware(['auth.shop']);

**Comment by ohmybrew** [comment]
When you say any page, where do I go?

**Comment by Saadnine15** [comment]
Program details

**Comment by baorv** [comment]
@Saadnine15 I think you set a wrong URL for App URL, so you can not login to app.

![2019-05-27_16-39](https://user-images.githubusercontent.com/9483946/58411240-12328680-809e-11e9-83bc-865f928cadf9.png)

**Comment by veed76** [comment]
HI @ohmybrew 
Please see this video: https://www.loom.com/share/4786c063f40a40959d7bce0b9ce05922
If possible then please resolve ASPS.
Thank you.

**Comment by ohmybrew** [comment]
Merging to #244

**Comment by veed76** [comment]
Hi @ohmybrew 
The same issue I faced in version 10.1 https://prnt.sc/pd78hv
Is there any solution? or I have to do some configuration?

Thank You
