### ISSUE TITLE
App Proxy Error - There was an error in the third-party application

### ISSUE THREAD

**Issue by edorozco** [ohmybrew/laravel-shopify#250]
Hi, I'm following the tutorial to publish the proxy app in the store, but I get an error.

- I am using laravel forge for deploy my app (the app is the same of your tutorial),

- I have configured the Nginx file by removinng **add_header X-Frame-Options "SAMEORIGIN";**

- The public/.htaccess file is by default use laravel apps.

- I have configured app proxy in shopify correctly. 

   `prefix: a`  
  `path: laravel-forge`
  url shopify shop [https://dmodaencali.myshopify.com/a/laravel-forge](https://dmodaencali.myshopify.com/a/laravel-forge)
  url my app proxy : [https://customizesuit.com/proxy](https://customizesuit.com/proxy)

- I have installed SSL.

But I still have an error, I do not know what else to do

This is the error
**There was an error in the third-party application**

Thanks for the help, thank you very much

**Comment by ohmybrew** [comment]
check the request and response to be sure there is not an error?

**Comment by edorozco** [comment]
Yes, I did, but in  my app server doesn't report any request

**Comment by ohmybrew** [comment]
If your server is not registering the request then thats the first step to dig into. Are you sure you set the proxy route correctly into the admin panel?On May 28, 2019 17:34, Camilo Orozco <notifications@github.com> wrote:Yes, I did, but in  my app server doesn't report any request

**Comment by edorozco** [comment]
Thanks for you support.

access-log report this.

GET /proxy/?shop=dmodaencali.myshopify.com&path_prefix=%2Ftools%2Flaravel-forge&timestamp=1559078915&signature=79f98a66833754fab01bce14d55acdeb268c8864a73d5c57fb64f7f2ce4bdec2

but the error still present.

**Comment by edorozco** [comment]
@ohmybrew, finally I found what was error. 
 You must have correctly configured the ssl you can validate it in [https://www.sslshopper.com/ssl-checker.html]( https://www.sslshopper.com/ssl-checker.html) All items must be check ok.

In this case, I use [forge.laravel.com](https://forge.laravel.com)

**Comment by ohmybrew** [comment]
Correct! Thanks
