### ISSUE TITLE
Difference between Freemium and Grandfathered

### ISSUE THREAD

**Issue by StefanNeuser** [ohmybrew/laravel-shopify#256]
https://github.com/ohmybrew/laravel-shopify/blob/7453d2483ea979d221349a883fab34ea9c3adabe/src/ShopifyApp/Middleware/Billable.php#L28

Sorry but I did not find any explanation in die docs. Does any body know where I can find the explanation about whats the difference between Freemium and Grandfathered? 

Greetings, Stefan

**Comment by ohmybrew** [comment]
freemium is for if you have plans. you can allow someone to sign up for free and upgrade them to a plan manually later. this allows you to check if they're freemium mode and limit what they can see or do.

grandfathered is for if you wish to have a shop skip all billing. if you have an app which charges a customer upon install, if theyre flagged as grandfathered, they skip that screen
