### ISSUE TITLE
GetAccessToken is getting timedout

### ISSUE THREAD

**Issue by pankajbokdia** [ohmybrew/laravel-shopify#257]
Loved this. Thank you so much for making our lives easier. 
There is a small issue I am facing. After accepting the permissions and installing the app on the store, the app is getting timed out while getting access token from Shopify.

**Comment by ohmybrew** [comment]
Can you provide any sort of logs, what setup do you have.

**Comment by pankajbokdia** [comment]
Hello, Sorry for the late reply. There was some issue with Shopify. Its
sorted and working now.
