### ISSUE TITLE
customers and products webhooks

### ISSUE THREAD

**Issue by tzookb** [ohmybrew/laravel-shopify#258]
I got this tutorial:
https://github.com/ohmybrew/laravel-shopify/wiki/Creating-Webhooks

and it worked great for orders

but it seems like when Im trying to do the same for products or customers
the webhook is not created on Shopify...

my config:

```
'webhooks' => [
      
        [
            'topic' => 'orders/create',
            'address' => env('APP_URL').'/webhook/orders-create'
        ],
        [
            'topic' => 'orders/updated',
            'address' => env('APP_URL').'/webhook/orders-updated'
        ],
        [
            'topic' => 'orders/delete',
            'address' => env('APP_URL').'/webhook/orders-delete'
        ],


        // Customers
        [
            'topic' => 'customers/create',
            'address' => env('APP_URL').'/webhook/customers-create'
        ]
    ],
```

any ideas appreciated :)

**Comment by SycleUxTeam** [comment]
I ran into a similar issue and then realized that I did not request sufficient permissions from Shopify when installing the app. Make sure you includes permissions for products and customers. The file is located in config > shopify-app.php

` /*
    |--------------------------------------------------------------------------
    | Shopify API Scopes
    |--------------------------------------------------------------------------
    |
    | This option is for the scopes your application needs in the API.
    |
    */

    'api_scopes' => env('SHOPIFY_API_SCOPES', 'write_content,write_products,write_orders,write_script_tags,read_script_tags'),
`

**Comment by mferrario** [comment]
When installing the app, make sure you are including permissions for products and Customers. I ran into a similar issue, until I realized the dependency/association of scope and web hooks. 

To change the scope navigate to: config > shopify-app.php


` 
    | This option is for the scopes your application needs in the API.

    'api_scopes' => env('SHOPIFY_API_SCOPES', 'write_content,write_products,write_orders,write_script_tags,read_script_tags'),
`

**Comment by ohmybrew** [comment]
Correct. Make sure your scopes are correct and clear all cookies and reaccess the app to trigger the webhook manager
