### ISSUE TITLE
No response from app/uninstalled webhook

### ISSUE THREAD

**Issue by kennyalmendral** [ohmybrew/laravel-shopify#259]
Hello,

Not sure if I'm doing something wrong or if I'm missing something... The installation goes smoothly, but during the uninstallation process, there is no response being sent to the webhook URL which is `https://neatpod/webhook/app-uninstalled`.

Anyways, here's the contents of the `webhooks` array defined in the `config/shopify-app.php` file:

```php
'webhook' => [
    'topic' => env('SHOPIFY_WEBHOOK_1_TOPIC', 'app/uninstalled'),
    'address' => env('SHOPIFY_WEBHOOK_1_ADDRESS', 'https://neatpod/webhook/app-uninstalled')
]
```

...and here's the contents of the closure under `routes/web.php` file:

```php
Route::get('/webhook/app-uninstalled', function() {
    $data = file_get_contents('php://input');
    $hmac_header = $_SERVER['HTTP_X_SHOPIFY_HMAC_SHA256'];
    $calculated_hmac = base64_encode(hash_hmac('sha256', $data, env('SHOPIFY_API_SECRET'), true));

    $verified = hash_equals($hmac_header, $calculated_hmac);

    $recipient = 'kennyalmendral.sandbox1@gmail.com';
    $subject = 'Test Email';

    $message = var_export($verified, true);
    $message .= var_export($data, true);

    $headers = 'From: kennyalmendral.sandbox@gmail.com' . "\r\n" .
        'Reply-To: kennyalmendral.sandbox@gmail.com' . "\r\n" .
        'X-Mailer: PHP/' . phpversion();

    mail($recipient, $subject, $message, $headers);
});
```

Thanks in advance :)

**Comment by ohmybrew** [comment]
there's an internal webhook listener controller which takes and matches it to a job class. im pretty sure what you have there will never be triggered because the parent route in the package covers everything. coming to /webhook.  it would be better to use the package process since its more in line with how to properly handle it by using jobs and also handles the validation check for you.

**Comment by kennyalmendral** [comment]
@ohmybrew thanks for the response, when you said _"it would be better to use the package process..."_, do you mean the one described in here: https://github.com/ohmybrew/laravel-shopify/wiki/Installation#uninstalled-job-recommended? If so, is it okay for you to provide an example of what will the generated `App/Jobs/AppUninstalledJob` file would typically contain?

Thanks again!

**Comment by ohmybrew** [comment]
Sure, if you run the artisan command, a file gets added to your App/Jobs which points to this file.. https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/Jobs/AppUninstalledJob.php

You can override it how you please with the file thats in App/Jobs

**Comment by kennyalmendral** [comment]
Thanks @ohmybrew

**Comment by cornerstonewebsystems** [comment]
Hi @kennyalmendral, were you able to sort this out as yet? 
I have been trying (in vain) to get my webhook to work but it just doesn't seem to call the job. Any ideas please?

Thanks

**Comment by kennyalmendral** [comment]
@cornerstonewebsystems not yet because the project I was working on got paused, sorry.
