### ISSUE TITLE
GDPR Requirements

### ISSUE THREAD

**Issue by ncpope** [ohmybrew/laravel-shopify#26]
Shopify recently added information about additional webhooks that are going to be required by all apps: https://help.shopify.com/api/guides/gdpr-resources

They are `shop/redact`& `customers/redact` and the urls for them will be set in the app info panel.

Should we include sensible defaults for these in the package?

**Comment by tobiasdalhof** [comment]
+1

btw: https://help.shopify.com/api/app-store/listing-in-the-app-store/data-and-user-privacy/privacy-policy-template

**Comment by ncpope** [comment]
On second thought, I suppose we should just leave it as it is. The laravel-shopify package doesn't seem to store any personally identifiable pieces of store data. I think the developer should handle this on their own. I don't see what this package should do to cater to this except maybe mentioning it in the installation process. Or, possibly at the very most, creating a simple placeholder job for the dev to fill out on their own.

**Comment by ohmybrew** [comment]
Yeah there's so many conflicting things I'm reading. I think that's the
best action. I'll work on a solution for the week.

**Comment by ncpope** [comment]
Closing for now as it doesn't seem that any changes are required.

**Comment by ohmybrew** [comment]
Thanks @ncpope, made a wiki entry for this instead [here](https://github.com/ohmybrew/laravel-shopify/wiki/GDPR).

**Comment by mabrodeur** [comment]
As per your wiki entry, we need to set the entry in the config/shopify-app.php file.
However, if we try to install the webhooks, we get this error from shopify : 

```
Client error: `POST https://my-shop.myshopify.com/admin/webhooks.json`
resulted in a `422 Unprocessable Entity` response:
{"errors":{"topic":["Invalid topic specified. Topics allowed: app\/uninstalled,
collections\/create, collections\/delete (truncated...)
```

And as per the API reference [https://help.shopify.com/api/reference/events/webhook](https://help.shopify.com/api/reference/events/webhook) you can only set `shop/update` hook.

`shop/redact` and `costumer/redact` should be set in the `App info` tab in your app on the Shopify Partners portal. ([Source](https://help.shopify.com/api/guides/gdpr-resources#mandatory-webhooks)).

**Comment by ohmybrew** [comment]
Oh that's how it works? It's a setting? Will check this sorry

**Comment by brianakidd** [comment]
Yes, we still need to be able to respond to the redact webhooks but we don't need to subscribe to them.  The way you have the webhook controller designed, we can follow the same naming convention as the other webhooks including creating the corresponding jobs but don't need to enter them in the webhooks config.

**Comment by ohmybrew** [comment]
Makes sense.. let me try and adjust.

**Comment by ohmybrew** [comment]
@brianakidd  Thank you; adjusted.

**Comment by SignatureForum** [comment]
I have added  costumer/redact webhook in our   App info tab.Please check the shared screenshot link:https://www.screencast.com/t/c4wtuUUGW6nc
But i am unable to get the webhook response after that i have tried to create this webhook through postman   and get this error 
https://www.screencast.com/t/iDz7yRpDB
https://www.screencast.com/t/iDz7yRpDB
please help me

**Comment by ohmybrew** [comment]
@SignatureForum  I don't believe this is an issue with the package. Where does the URL go to that you have specified? The error you're getting is from Shopify iteself.

**Comment by SignatureForum** [comment]
I have added costumer/redact webhook in our App info tab.Please check the shared screenshot link:https://www.screencast.com/t/c4wtuUUGW6nc
Here is the rout url
https://user-images.githubusercontent.com/3440763/43856894-351449fc-9b63-11e8-831e-f0372df7105c.png


https://user-images.githubusercontent.com/3440763/43856741-d594202e-9b62-11e8-93ae-96955207a9ca.png

But i am unable to get the webhook response after that i have tried to create this webhook through postman and get this error
https://www.screencast.com/t/iDz7yRpDB
https://www.screencast.com/t/iDz7yRpDB
please help me

**Comment by ohmybrew** [comment]
@SignatureForum I am unsure. This is not an error from the package but Shopify itself. What URL are you running in postman

**Comment by ohmybrew** [comment]
You don't need to put in the webhooks into admin settings if I remember.. I
think this fires by Shopify itself. I don't support GDPR internally for the
package, but if there's an issue with the doc which tries to have some
guidelines I can look at that for sure.

**Comment by ohmybrew** [comment]
Sorry to exapand on the above, you enter the url into your app settings
admin, not the Shopify admin. And Shopify should fire it.. but yes if
there's an error in what's laid out in the doc I can certainly adjust.

**Comment by paulcanning** [comment]
> Sorry to expand on the above, you enter the url into your app settings admin, not the Shopify admin.

The thing is, the hooks are required by Shopify, it states it right there in the app settings page

> Required webhooks to manage requests to erase customer personal information.

**Comment by ohmybrew** [comment]
Yes they're required but after some discussion and thoughts on this issue
when it first came up, I decided I did not want to internally support this.
There could be an array of things someone needs to delete from database
entries to files, depending on the app, I could provide a base job to
extend, but it ended up being something I didn't feel comfortable providing
support for.

**Comment by paulcanning** [comment]
I removed them in the App settings (oddly, whilst required, you can save the form without them) and I'm still getting the following error when trying to install the app:

> Client error: `POST https://my-shop.myshopify.com/admin/webhooks.json` resulted in a `422 Unprocessable Entity` response: {"errors":{"topic":["Invalid topic specified. Topics allowed: app\/uninstalled, collections\/create, collections\/delete (truncated...)

Oddly, if i go back into the shop, the app has been installed, but has not gone through the billing process.

**Comment by ohmybrew** [comment]
Did you setup a webhook in the config/shopify-app file? Seems like it found
a webhook, tried to push it to your shop but the topic was bad.

**Comment by paulcanning** [comment]
Yes, I followed the instructions spat out by the console:

```
php artisan shopify-app:make:webhook CustomersRedactJob customers/redact
Job created successfully.
Don't forget to register the webhook in config/shopify-app.php. Example:

    'webhooks' => [
        [
            'topic' => 'customers/redact',
            'address' => 'https://your-domain.com/webhook/customers-redact'
        ]
    ]

```

I think this is the issue. You will need to remove these instructions.

**Comment by ohmybrew** [comment]
Ah! Yes.. I'll make a note for GDPR that it's not required to do this... Or
remove the instructions all together; not sure what's a better option there.

**Comment by ncpope** [comment]
Just thought I should mention that we might want to add to the wiki that there is an additional GDPR requirement.

When a shops customer requests their data from a shop, there will be a request sent to the app. It's required that the app to send any related data it has directly to the customer.

More info here: https://help.shopify.com/en/api/guides/gdpr-resources
See: customers/data_request

**Comment by ohmybrew** [comment]
Ah thats a new one! @ncpope Thanks, I'll reformat the entire wiki entry to help better guide this.

**Comment by tobiasdalhof** [comment]
Hey guys this might be a little off topic but what should I do when my app does not read or store any customer data? The related text fields in the app settings are required. 

Should I provide "dummy" webhooks that just return status code 200?

**Comment by ohmybrew** [comment]
I dont think its off-topic. It seems it requires a response of 200 for the redact store & customer, but the new data_request it does not say anything.

In cases for customer, I would assume a 200 is fine, maybe with a message on the body (Shopify may store it?)

**Comment by ncpope** [comment]
thanks @ohmybrew sorry to re-open the issue but I just noticed the additional requirement since I'm trying to get my app compliant before the 25th and I was double checking everything.

@tobiasdalhof It looks like you don't need to do anything for customer related data if your app doesn't access customer data. My app doesn't store any customer data either but I just created the hooks, just in case. Shopify has a tendency to change these types of requirements so I figured I would just do all of them now just in case.

**Comment by ohmybrew** [comment]
> Shopify has a tendency to change these types of requirements

Indeed.

I will replicate a lot of info in Shopify's GDPR into a revised wiki entry and link it for the install wiki entry so people are aware of the requirements.

**Comment by ohmybrew** [comment]
Wiki entry reformatted to show all types of GDPR webhooks, explanations, payloads, expected responses, activation, and more.

**Comment by sovoeun** [comment]
Hi Sir/Madam,
I try to install my first shopify app but i seem error with webhooks configuration.
Error:  https://snag.gy/a5fQcq.jpg
shopify-app.php: https://snag.gy/rZlx06.jpg

Please help and thanks

**Comment by hakimihamdan88** [comment]
@sovoeun have you add write_orders scope in SHOPIFY_API_SCOPES ?

**Comment by sovoeun** [comment]
@hakimihamdan88 Can you show maybe a bit because i not sure.
