### ISSUE TITLE
Emails

### ISSUE THREAD

**Issue by cornerstonewebsystems** [ohmybrew/laravel-shopify#265]
Hi @ohmybrew 

How do I send emails on specific actions, please? I need to send out emails to store owners based on the following conditions:

a. merchant subscribes to paid app /plan
b. merchant deleted the app from their store

Would appreciate some pointers here please.

Thanks

**Comment by Ivan1234** [comment]
Hi, use this webhook for unistaled app https://github.com/ohmybrew/laravel-shopify/wiki/Installation#uninstalled-job-recommended
