### ISSUE TITLE
check if app is deleted and redirect to "authorize"

### ISSUE THREAD

**Issue by tzookb** [ohmybrew/laravel-shopify#266]
currently I have the app redirect to Shopify when user comes in through my domain

the problem is with this flow:

- user installs app
- user removes app on Shopify
- user goes to my app domain directly again
- user gets redirected to shopify
- problem here
- the app is deleted on shopify so he gets 404 page

How can I check if app is uninstalled and redirect user to the `authorize` page?

thanks again!

**Comment by tzookb** [comment]
I see we have this page:
https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/resources/views/layouts/default.blade.php

do you maybe have this file:
https://cdn.shopify.com/s/assets/external/app.js

documented somewhere? cant find it on Shopify docs :/

**Comment by ohmybrew** [comment]
The problem is no one knows by default if the app was uninstalled. You'll need to look at using uninstall webhook (see wiki). Theres a default job provided which will run when a merchant uninstalls the app.

It will soft delete the shop, among other things.
