### ISSUE TITLE
unable to access the shop pages i am using ohmybrew.

### ISSUE THREAD

**Issue by Mussadiq4230** [ohmybrew/laravel-shopify#267]
**API Code:**
```
$shop = ShopifyApp::shop();
$request = $shop->api()->rest('GET', '/admin/api/2019-04/pages.json');
		
if($request->body){
	return $request->body->pages; 
}else{
	return null;
}
```
Returning empty or null. 
while i have 2 pages in my store published and view able.
i am confused why it is not working with pages while working fine for me for products, orders or customers.

Do i need any access scopes ? but i read shopify they said no scope is required for accessing pages.

I am Stuck help will be appreciated?

**Comment by bnzo** [comment]
Try to enable these scopes:

`read_content, write_content`

Access to Article, Blog, Comment, Page, and Redirect.

**Comment by ohmybrew** [comment]
You need scopes.

/admin/api/2019-04/pages.json is also not required, you can set your API version with config/shopify-app.php, theres a spot to enter, you can then simply hit "/admin/pages.json" and it'll sort out the versioning for you.

**Comment by Mussadiq4230** [comment]
thank you very much @ohmybrew  :)
