### ISSUE TITLE
Billing process not inserting all data

### ISSUE THREAD

**Issue by jamie-brown** [ohmybrew/laravel-shopify#269]
Hi there, 

I wondered if you could assist please. It seems I have everything working except the billing is not quite right. 

When the package processes the billing subscription it errors on Laravel about the 'type' field should not be null for the charges table.

It doesn't seem to pass a few of the necessary fields through. Here is a example table insert from the process:

```sql
insert into
  `charges` (
    `charge_id`,
    `shop_id`,
    `plan_id`,
    `type`,
    `status`,
    `activated_on`,
    `name`,
    `price`,
    `test`,
    `trial_days`,
    `updated_at`,
    `created_at`
  )
values
  ("9216622692", 11, null, null, "active", "2019-06-17", null, null, 0, 0, "2019-06-17 19:36:40", "2019-06-17 19:36:40")
```

It also doesn't seem to pass a plan_id into the shops table. 

Am I missing something?

Any help is greatly appreciated.

**Comment by jamie-brown** [comment]
Diving into this further, the errors seem to start from: `ohmybrew/laravel-shopify/src/ShopifyApp/Traits/ShopModelTrait.php - Line 87`

```php
OhMyBrew\BasicShopifyAPI::setSession() must be of the type string, null given
```
The actual data being passed:

```php
OhMyBrew\\BasicShopifyAPI->setSession('bargains-gallor...', NULL)
```
If I manually enter the plan_id into the database it all works. If I leave it, I constantly have to go through the billing screen on shopify.

**Comment by jamie-brown** [comment]
Hmm.... the plan is null when it gets to the process method in the BillingControllerTrait.

Adding this line at the top of the process method (which is the same as the index method of this trait):

```php
if (is_null($plan) || ($plan && !$plan->exists)) {
            $plan = Plan::where('on_install', true)->first();
        }
```

Makes everything work as I'd expect again.

I've got to be doing something wrong for the plan to be coming through as null in the first place.

**Comment by ohmybrew** [comment]
Do you have one plan thats set to on_install as true in the database?

**Comment by jamie-brown** [comment]
Hi sorry for the delay. Yeah my startup plan is just set to true for on_install. The rest of my plans are set to false.

**Comment by ohmybrew** [comment]
Mergint to #241
