### ISSUE TITLE
Can't grab the access token that's why below screenshot error occurred

### ISSUE THREAD

**Issue by ardnor** [ohmybrew/laravel-shopify#27]
Hello @ohmybrew, Thank you for this package I am currently studing this package for shopify and after installing the app to a store error occurred below screenshot:

https://www.screencast.com/t/eLynlUD2jDs

And the response of the access_token was nulled there no value save to the shop table.

Please advise. Thank you.

Regards,
Ronard

**Comment by ohmybrew** [comment]
@ardnor Underlying package issue of a BC I didnt see. Can you run `composer update` and ensure `ohmybrew/basic-shopify-api` moves to 3.0.1? This should fix the isuee.

**Comment by ardnor** [comment]
@ohmybrew Thank fixed now. Appreciated for your quick response.
https://www.screencast.com/t/B5PckiGgmr

**Comment by ohmybrew** [comment]
Thanks for responding :) enjoy.
