### ISSUE TITLE
Authentication after a long period of time

### ISSUE THREAD

**Issue by muhammadasfar** [ohmybrew/laravel-shopify#271]
Hi 

I hope everyone is doing great. I am developing shopify app using below 

Laravel V 5.8 
PHP V 7.2
Ohmybrew Laravel-shopify V 7.0 also same behavior at V 6

**Issue is**

After installation it is working fine but when I load this app again after few minutes it is showing me the below error. it is due to server or any other reason? 

Secondly when error occurred, removing **shopify_token** from database shop table and refreshing app, will load app correctly and updating **shopify_token** with same token.

Any help?

**Trying to get property shopify_domain of non-object**

![FireShot Capture 006 ](https://user-images.githubusercontent.com/38552865/59845933-ff972e80-9377-11e9-8bd2-d879f0d35381.png)

**Comment by Kyon147** [comment]
Getting the same error since updating the package. Does not stop the app from loading but is throwing the error every time it needs to authenticate.

Trying to get property 'shopify_domain' of non-object (View: \resources\views\vendor\shopify-app\layouts\default.blade.php)

**Comment by muhammadasfar** [comment]
@Kyon147 Waiting for its solution because I am not sure about reason of this error.  It will good if someone point my mistake in any step.

**Comment by ohmybrew** [comment]
Hmm, this would mean the session is not valid anymore. I'll take a look.

**Comment by muhammadasfar** [comment]
@ohmybrew Yes it is due to session.
Currenlty, I am adding shopify domain value in session at this key **shopify_domain** by getting value from database shop table before loading my app view. it works fine but I guess it is not a proper solution.

**Comment by ohmybrew** [comment]
Which version specifically are you using?

v7.1.0 introduced a patch to assist in issues with the session.

**Comment by Kyon147** [comment]
I've updated to v8.0 and still getting the error.

![image](https://user-images.githubusercontent.com/32519106/60530261-467a1200-9cf0-11e9-8940-1cb90032e9e3.png)

**Comment by ohmybrew** [comment]
@muhammadasfar I am really confused at what you're doing exactly. Can you step by step what you're doing, you say you're doing a custom lookup and such, I am a bit lost here.

**Comment by muhammadasfar** [comment]
@ohmybrew 
**Step by step what I am doing**
After installation it is working fine but when I am loading this app again from APPS. it is showing me the above screenshot error (Trying to get property shopify_domain of non-object).

I am overriding controller,routes and view using  [wiki doc](https://github.com/ohmybrew/laravel-shopify/wiki/Overriding-and-Extending#controllers--routes).

**what I did for its solution** 
I am adding shopify domain value in session at this key **shopify_domain** by getting value from database shop table like below code

` $shop = ShopifyApp::shop();`
` session(['shopify_domain' => $shop->shopify_domain]);`

 in my **index function of my app controller** and it is working fine now.

**Which version specifically I am using?**

I have two apps in progress. I am using 
Server Nginx
Laravel V 5.8
PHP V 7.2
Ohmybrew Laravel-shopify V.7.0 in my current app and V.6.0 in another app both have the above issue as in screenshot. 

According to your above comment v7.1.0 introduced a patch for this issue, let me give it a shot then.

**Comment by ohmybrew** [comment]
You're directly modding the session values?

**Comment by Kyon147** [comment]
It might not be linked but I've noticed I get the error because of the cached view.

![image](https://user-images.githubusercontent.com/32519106/60593163-12f3c200-9d9a-11e9-9d2b-0e830bd1a269.png)

Which seems to be triggered by /js/popper.js.map

**Comment by ohmybrew** [comment]
Cached view shouldn't be the issue since it's just blade template converted to PHP

**Comment by ohmybrew** [comment]
I have a test setup now to replicate through an admin link. I will leave it for 24 hours, visit, and see what happens. If I'm able to reproduce, I'll be able to dig into why.

**Comment by ohmybrew** [comment]
@bilfeldt I just set everything up. Route is loaded, session is in cookies I can see, so now I will leave it for 24 hours, and click the admin link again.

Can you confirm something for me, if you're able to... if you view the cookies for your app's domain, does the expire time say "Session End"? Laravel by default sets a timed expire which cased similar issues before, on auth, I override this setting to make it expire when someone closes the browser instead.

**Comment by bilfeldt** [comment]
@ohmybrew I get the following info about the cookie. Note that you should maybe wait 26 hours as it looks like that is the expiration time.

<img width="443" alt="Screenshot 2019-07-08 15 17 59" src="https://user-images.githubusercontent.com/30228807/60813325-c9d5b080-a193-11e9-88a4-b03726a9360d.png">

Let me know if you need anything else.

**Comment by ohmybrew** [comment]
@bilfeldt Not the XSRF token, look for one called "laravel_session", it may be slightly different in name if you've overwritten the default session name.

**Comment by bilfeldt** [comment]
@ohmybrew that one has the same expiration.
<img width="445" alt="Screenshot 2019-07-08 16 41 44" src="https://user-images.githubusercontent.com/30228807/60819383-c5af9000-a19f-11e9-9739-b29b0ff9c13f.png">

**Comment by ohmybrew** [comment]
Okay... I think thats the issue. It should expire on Session Close. Still, the auth middleware should see its an expired session... will investigate.

**Comment by ohmybrew** [comment]
@bilfeldt Are you using filesystem for sessions or database or other?

I forced Laravel to expire the session after an hour... which worked and re-authed me fine.

I'm doing the same test now with APP_ENV as production to rule out a production based issue but wanted to double check what session driver youre using.

**Comment by bilfeldt** [comment]
@ohmybrew I am using filesystem like so:

```php
SESSION_DRIVER=file
SESSION_LIFETIME=120
```

Do note that I am re-authenticated just fine, but the controller is running twice, so the counter is incrementing by 2 instead of 1. Have you been able to reproduce this behaviour?

**Comment by ohmybrew** [comment]
@bilfeldt ohh that's you're issue? Yes that's normal because during reauth, it sends you to your app url on your host, once it loads Shopify's esdk or app bridge detects it's not inside the iframe and loads it in one then.

**Comment by ohmybrew** [comment]
@Kyon147 What session driver are you using? Whats a method I can do to attempt to repeat your issue?

**Comment by Kyon147** [comment]
> @Kyon147 What session driver are you using? Whats a method I can do to attempt to repeat your issue?

Just using the default settings - it seems to be when Shopify session times out but the app is open and you try and do anything. As it no longer has a valid session it then just throws up errors.

```
SESSION_DRIVER=file
SESSION_LIFETIME=120
```

**Comment by ohmybrew** [comment]
@Kyon147 So you have a link or button inside the page which you click, and causes the error?

Is this button/link behind 'auth.shop' middleware?

**Comment by Kyon147** [comment]
@ohmybrew now you mention it, the routes are not using the auth.shop which is bad on my part of probably not 100% understanding middleware...

The "welcome" does which is the first route but thinking of it, the other routes do not use the auth.shop middleware. Did not think about needing to put all of them behind it as in my head everyone went through "welcome" but did not account for when they are moving from one place to another after session expiry!

I'll put all these routes using the auth.shop middleware and see if the error stops.

**Comment by ohmybrew** [comment]
Ah! Yes, its absolutely required. Maybe I should make it more clear in the docs. The exact reason is just that - it checks the Shop out completely (valid session? has it been deleted or trashed? does it still have a valid token? etc) and if anything fails, it kicks them to the auth flow.

**Comment by Kyon147** [comment]
@ohmybrew how stupid of me! It might be worth mentioning that any route created needs to have the auth.shop on it otherwise the user will be booted out. Although I completely get what you mean now it was a silly moment on my end! Hopefully, it can save someone else in the future :)

Thanks for taking the time to help though, much appreciated.  Love to help out at some point later down the line once I get more up to scratch on the inner workings on Shopify and Laravel a bit more. 

Love the package.

**Comment by bilfeldt** [comment]
> @bilfeldt ohh that's your issue? Yes that's normal because during reauth, it sends you to your app url on your host, once it loads Shopify's esdk or app bridge detects it's not inside the iframe and loads it in one then.

@ohmybrew I am not completely sure I follow. If I use the _admin link_ while having a valid session, then it opens the controller in the iframe. But if instead I use the _admin link_ without a valid session, then the controller does it magic (probably outside the frame?) and I am redirected, where the controller is now doing it's magic inside the controller.

Is there a way to get around this? If the controller is doing some irreversible action, which a lot of _admin links_ will do, then this won't work. Imagine for example that you have a controller that does some actions and then completes the order. When you use this action without an active session, then it will do all of that and then redirect you to the same controller again but this time it will fail since the order is already completed.

I hope it makes sense?

**Comment by ohmybrew** [comment]
@bilfeldt Yes this is expected. Without a valid session, the package does a fullpage redirect to Shopify to get the token data, which in turn redirects back to the page (not in an iframe), this loads the controller/view, then Shopify's JS for AppBridge/ESDK sees its not in the iframe, and loads it in one again.

**Comment by bilfeldt** [comment]
@ohmybrew thanks for the details.

I am thinking if there is any way around this. This could be an issue for all _admin links_  as I see it.

Is it possible to either:
1. Make an in-iframe redirect to Shopify to get token data if no valid session is present
2. Redirect back to a specific page instead of the route that the _admin link_ pointed to? (this is not really a solution but a workaround)

**Comment by ohmybrew** [comment]
@bilfeldt 

oAuth has to happen at top-level, can not be in an iframe.

Hypothetically, I could skip the redirect, verify the HMAC request, and update the session and it wouldn't do the "double load" you see..

If the shop has a token (and per-user is not enabled): I could have it run through the session updater and skip the oauth redirect.

Two issues to this:
1. If you update the app's scopes, the user will not be asked to confirm scope permissions unless they go back to Apps and click the main app link
2. For people using per-user, they have to go through the whole auth anyways

I may make a special branch to test this method out... if I do, would you like to point your composer entry to it once I'm done and see if it gives you the effect you're looking for?

**Comment by ohmybrew** [comment]
FYI I have a branch for this to do full and partial flow now... unit tests passed but have no tried physical tests. Branch is `alt-flow`. Will be doing physical tests shortly.

**Comment by ohmybrew** [comment]
Hmm... seems to work ok in a physical test: https://streamable.com/drg5l

- At the start I am loading the app through the main screen
- At 0:09ish I am loading a an admin link
- At 0:12ish-0:19ish I am deleting all app-domain cookies/session from Firefox
- At 0:20ish the admin link re-loads with session fixed up and no iframe redirect happened.

Will continue to test...

**Comment by bilfeldt** [comment]
> if I do, would you like to point your composer entry to it once I'm done and see if it gives you the effect you're looking for?

@ohmybrew absolutely, would be more than happy to test. 

One suggestion could be to implement this as a separate middleware that one can use for _admin links_ where this double redirect is unwanted. What about authentication for Shopify webhooks, I would assume these are not using the normal auth middleware, but I am not sure how it works there?

Thanks for your much appreciated work in this matter.

**Comment by ohmybrew** [comment]
@bilfeldt it's ready, I did some quick physical tests and all worked fine. Seperate middleware is not needed, detection happens and it decides what to do.

Change composer to point to "dev-alt-flow", run composter update and you should be good to try.

**Comment by bilfeldt** [comment]
@ohmybrew This is simply awesome! This works on my test as well.

What is the new authentication logic then?

Thanks for the fantastic support.

**Comment by ohmybrew** [comment]
@bilfeldt Glad it's working. I'll do some clean up and review on it plus write some new unit tests to support it before including it in a new release.

Essentially the middleware is split into two detections now.

A) Shop is nil? Shop is trashed? Shop in session doesn't match incoming shop? -- then: redirect to auth handler and tell auth handler it needs to do the full-page oauth flow
B) If A passes, then we check if the session is valid -- if not, then: redirect to the auth handler and tell the auth handler to skip the whole oauth flow.

So now the middleware will essentially set a "flag" to tell the auth handler if it needs to do the full oauth flow or not. By a simple if statement, we can skip the whole oauth flow and simply recreate the session for the shop since everything else is fine. This eliminates the whole redirect issue previously.

**Comment by ohmybrew** [comment]
Will try and get this done for Sunday

**Comment by Kyon147** [comment]
Hey @ohmybrew 

I've updated the routes to use the auth.shop middleware but now the app loads the "install" screen even though it has an entry in the DB.

![image](https://user-images.githubusercontent.com/32519106/61181217-02094300-a61b-11e9-8fd2-c08bfbb516ff.png)

Debugging what's happening it looks like it can't find the shop, so is sending over to the "install" screen above. Weirdly, the shop exists because when you load through the app screen it authenticates fine. Just seems to happen when already in the app and there is no valid session.

Here's the debug: 
![image](https://user-images.githubusercontent.com/32519106/61181311-91632600-a61c-11e9-909e-ad930f939420.png)

**Comment by ohmybrew** [comment]
Unit tests are in place and working, doing more physical tests before pushing a release.

**Comment by adamlevenson** [comment]
Not sure if this is related, but if I clear out the sessions in laravel and then go back into the app again, I am getting a blank screen in the shopify admin. It appears it is getting stuck in auth/fullpage_redirect.blade.php and the redirect is not happening. If I post the URL into the browser it goes back through the process and reauthenticates and then works. Look at the documentation here: https://help.shopify.com/en/api/embedded-apps/app-bridge/oauth I am not sure if what you have is the same intent or it was just not refactored to support app bridge. If so, I can give it a go and submit a PR.

**Comment by ohmybrew** [comment]
v9.0.0 is out and should solve the bulk of the auth issues. Now there is a partial and full flow.

Partial flow will now happen when the shop is valid but the session has expired, the session will be simply updated.

This solves the issues of pages showing twice sometimes (once outside iframe, then inside iframe again), now if session expires, the page will show like normal.

Marking this closed for now as its gotten a bit lengthly and off-topic in some area. If anyone has other issues when on v9.0.0 please see the new issue template in the main repo root and add an issue and i'll gladly help.

@adamlevenson Please see issue template and open a new issues for your comment :)

**Comment by darrynten** [comment]
@ohmybrew I now get stuck on "too many redirects" going to the "/partial" route

**Comment by bilfeldt** [comment]
@darrynten have you checked that your domains are correctly setup? So that you do not end with an infinite redirect loop.
