### ISSUE TITLE
How to add header to rest api requests

### ISSUE THREAD

**Issue by Hujjat** [ohmybrew/laravel-shopify#273]
Hi. 

Thanks for the great packages. :) 

I have little issue with rest api. I am trying to read the theme.liquid file and update it later. So I have the following route. 

`

Route::get('/update', function () {

    $myShop = ShopifyApp::shop();
    $themes = $myShop->api()->rest('GET', '/admin/api/2019-04/themes.json');

    $activeThemeId = "";
    // get active theme id
    foreach($themes->body->themes as $theme){
      if($theme->role == "main"){
          $activeThemeId = $theme->id;
      }
    }

    // get theme assets
    $activeTheme = $myShop->api()->rest('GET', '/admin/api/2019-04/themes/'.$activeThemeId.'/assets.json?asset[key]=layout/theme.liquid&theme_id='.$activeThemeId);
    
    return response()->json($activeTheme);

})->middleware(['auth.shop'])->name('config');

`

When I visit /update page. the request return no error with body = null. 
I followed [this ](https://help.shopify.com/en/api/reference/online-store/asset?api[version]=2019-04#show-2019-04)api instruction

Also, I have the permission on theme_read and theme write

If i send the quest to `admin/api/2019-04/themes/2334114/assets.json`
It returns all assets as object. 

## How to add header to rest api requests

My question is how to set header for my rest request. I am not sure if that's right, but we have that feature on laravel
`
 ->header('Content-Type', $type);
`

Is there any way to fix this issue or set header?

Thanks

**Comment by bnzo** [comment]
Instead of searching the active theme, you can retrieve it with this call:
`/admin/themes/current.json`

Then you should be able to retrieve any asset file with this call:
`/admin/themes/'.$activeThemeId.'/assets.json?asset[key]=layout/theme.liquid`

Not sur you need to set the header to get a correct response.

**Comment by Hujjat** [comment]
Hi @bnzo 

Thanks for the help. it worked. :)

**Comment by tungoanh** [comment]
same problem!
You have found a solution?
