### ISSUE TITLE
[Question] Reauth when session times out?

### ISSUE THREAD

**Issue by Kyon147** [ohmybrew/laravel-shopify#275]
Hey Tyler,

Great work on the laravel-shopify build it's really cool.

Been using it to build an app and noticed something that happens when the app is open and left, rather than try and reauthenticate it just throws up an error as the shop() is no longer valid.

```
        if (ShopifyApp::shop()->id !== $schedule->shop_id)
            abort(404);
```

Something like the code above then gets a "Trying to get property 'id' of non-object" error which makes sense as I should be checking for value first but, wondered why the app is not passing back through /authenticate.

Should I be checking and pushing them through manually? As I was under the impression that auth.shop should do this automatically, so technically ShopifyApp::shop() should always exist.

Again, could me my complete brain-block / lack of understanding on how your app works in detail yet but wanted to learn more.

**Comment by ohmybrew** [comment]
Hi, no, as long as you're route is behind auth.shop middleware it should ask to reauthenticate. A couple others commented on this as well so it seems to be a bug somewhere. I am investigating.

**Comment by ohmybrew** [comment]
Fwding to #271
