### ISSUE TITLE
Billing screen not show on shopify store

### ISSUE THREAD

**Issue by baljinder981** [ohmybrew/laravel-shopify#280]
Hello,

I have installed the package and created a Shopify app.

App installation and uninstall functionality is working fine and I have set up a one-time payment on app.

And I have followed this documentation :

https://github.com/ohmybrew/laravel-shopify/wiki/Creating-a-Billable-App

But the billing page is not showing in Shopify app it is directly installed my app on the store without any payment.

Can you please check and let me know which thing is missing from my end.

I have attached plan table and Shopify app screenshot please check and let me know

![image](https://user-images.githubusercontent.com/19308483/60949782-85711e80-a313-11e9-8b90-b9f9d86211f4.png)

![image](https://user-images.githubusercontent.com/19308483/60949938-cf5a0480-a313-11e9-8775-88621e9e0b2b.png)

**Comment by ohmybrew** [comment]
What is your config settings.

**Comment by baljinder981** [comment]
Please check :

<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Manual migrations
    |--------------------------------------------------------------------------
    |
    | This option option allows you to use:
    | `php artisan vendor:publish --tag=migrations` to push migrations
    | to your app's folder so you're free to modify before migrating.
    |
    */
    'manual_migrations' => (bool) env('SHOPIFY_MANUAL_MIGRATIONS', false),

    /*
    |--------------------------------------------------------------------------
    | Namespace
    |--------------------------------------------------------------------------
    |
    | This option allows you to set a namespace.
    | Useful for multiple apps using the same database instance.
    | Meaning, one shop can be part of many apps on the same database.
    |
    */

    'namespace' => env('SHOPIFY_APP_NAMESPACE', null),

    /*
    |--------------------------------------------------------------------------
    | Shop Model
    |--------------------------------------------------------------------------
    |
    | This option is for overriding the shop model with your own.
    |
    */

    'shop_model' => env('SHOPIFY_SHOP_MODEL', '\OhMyBrew\ShopifyApp\Models\Shop'),

    /*
    |--------------------------------------------------------------------------
    | AppBridge Mode
    |--------------------------------------------------------------------------
    |
    | AppBridge (embedded apps) are enabled by default. Set to false to use legacy
    | mode and host the app inside your own container.
    |
    */

    'appbridge_enabled' => (bool) env('SHOPIFY_APPBRIDGE_ENABLED', true),

    /*
    |--------------------------------------------------------------------------
    | Shopify App Name
    |--------------------------------------------------------------------------
    |
    | This option simply lets you display your app's name.
    |
    */

    'app_name' => env('SHOPIFY_APP_NAME', 'Ad Downtime'),

    /*
    |--------------------------------------------------------------------------
    | Shopify API Version
    |--------------------------------------------------------------------------
    |
    | This option is for the app's API version string.
    | Use "YYYY-MM" or "unstable". Refer to Shopify's documentation
    | on API versioning for the current stable version.
    |
    */

    'api_version' => env('SHOPIFY_API_VERSION', null),

    /*
    |--------------------------------------------------------------------------
    | Shopify API Key
    |--------------------------------------------------------------------------
    |
    | This option is for the app's API key.
    |
    */

    'api_key' => env('SHOPIFY_API_KEY', '503dd500a600cffa95770647735eb5ec'),

    /*
    |--------------------------------------------------------------------------
    | Shopify API Secret
    |--------------------------------------------------------------------------
    |
    | This option is for the app's API secret.
    |
    */

    'api_secret' => env('SHOPIFY_API_SECRET', '2c1b69c90612c6239331a0534eb567bd'),

    /*
    |--------------------------------------------------------------------------
    | Shopify API Scopes
    |--------------------------------------------------------------------------
    |
    | This option is for the scopes your application needs in the API.
    |
    */

    'api_scopes' => env('SHOPIFY_API_SCOPES', 'read_products,write_products'),

    /*
    |--------------------------------------------------------------------------
    | Shopify API Grant Mode
    |--------------------------------------------------------------------------
    |
    | This option is for the grant mode when authenticating.
    | Default is "offline", "per-user" is available as well.
    | Note: Install will always be in offline mode.
    |
    */

    'api_grant_mode' => env('SHOPIFY_API_GRANT_MODE', 'offline'),

    /*
    |--------------------------------------------------------------------------
    | Shopify API Redirect
    |--------------------------------------------------------------------------
    |
    | This option is for the redirect after authentication.
    |
    */

    'api_redirect' => env('SHOPIFY_API_REDIRECT', '/authenticate'),

    /*
    |--------------------------------------------------------------------------
    | Shopify API class
    |--------------------------------------------------------------------------
    |
    | This option option allows you to change out the default API class
    | which is OhMyBrew\BasicShopifyAPI. This option is mainly used for
    | testing and does not need to be changed unless required.
    |
    */

    'api_class' => env('SHOPIFY_API_CLASS', \OhMyBrew\BasicShopifyAPI::class),

    /*
    |--------------------------------------------------------------------------
    | Shopify API Rate Limiting
    |--------------------------------------------------------------------------
    |
    | This option option allows you to enable basic rate limiting
    | for API calls using the default BasicShopifyAPI library.
    | Default is off.
    |
    */

    'api_rate_limiting_enabled' => env('SHOPIFY_API_RATE_LIMITING_ENABLED', false),

    /*
    |--------------------------------------------------------------------------
    | Shopify API Rate Limit Cycle
    |--------------------------------------------------------------------------
    |
    | This option option allows you to set the millisecond cycle for
    | API calls using the default BasicShopifyAPI library.
    | Default is 500ms per API call.
    | Example: 0.5 * 1000
    |
    */

    'api_rate_limit_cycle' => env('SHOPIFY_API_RATE_LIMIT_CYCLE', null),

    /*
    |--------------------------------------------------------------------------
    | Shopify API Rate Limit Cycle Buffer
    |--------------------------------------------------------------------------
    |
    | This option option allows you to set the millisecond buffer for
    | API calls using the default BasicShopifyAPI library which gets
    | appended to the `api_rate_limit_cycle` value for a safety net.
    | Default is 100ms per API call.
    | Example: 0.1 * 1000
    |
    */

    'api_rate_limit_cycle_buffer' => env('SHOPIFY_API_RATE_LIMIT_CYCLE_BUFFER', null),

    /*
    |--------------------------------------------------------------------------
    | Shopify "MyShopify" domain
    |--------------------------------------------------------------------------
    |
    | The internal URL used by shops. This will not change but in the future
    | it may.
    |
    */

    'myshopify_domain' => env('SHOPIFY_MYSHOPIFY_DOMAIN', 'myshopify.com'),

    /*
    |--------------------------------------------------------------------------
    | Enable Billing
    |--------------------------------------------------------------------------
    |
    | Enable billing component to the package.
    |
    */

    'billing_enabled' => (bool) env('SHOPIFY_BILLING_ENABLED', true),
    // 'billing_enabled' => 1,

    /*
    |--------------------------------------------------------------------------
    | Enable Freemium Mode
    |--------------------------------------------------------------------------
    |
    | Allow a shop use the app in "freemium" mode.
    | Shop will get a `freemium` flag on their record in the table.
    |
    */

    'billing_freemium_enabled' => (bool) env('SHOPIFY_BILLING_FREEMIUM_ENABLED', false),
   // 'billing_freemium_enabled' => 0,

    /*
    |--------------------------------------------------------------------------
    | Billing Redirect
    |--------------------------------------------------------------------------
    |
    | Required redirection URL for billing when
    | a customer accepts or declines the charge presented.
    |
    */

    'billing_redirect' => env('SHOPIFY_BILLING_REDIRECT', '/billing/process'),

    /*
    |--------------------------------------------------------------------------
    | Shopify Webhooks
    |--------------------------------------------------------------------------
    |
    | This option is for defining webhooks.
    | Key is for the Shopify webhook event
    | Value is for the endpoint to call
    |
    */

    'webhooks' => [
		 [
            'topic' => env('SHOPIFY_WEBHOOK_1_TOPIC', 'app/uninstalled'),
            'address' => env('SHOPIFY_WEBHOOK_1_ADDRESS', 'https://app.addowntime.com/webhook/app-uninstalled')
        ]
        /*
            [
                'topic' => env('SHOPIFY_WEBHOOK_1_TOPIC', 'orders/create'),
                'address' => env('SHOPIFY_WEBHOOK_1_ADDRESS', 'https://some-app.com/webhook/orders-create')
            ],
            ...
        */
    ],

    /*
    |--------------------------------------------------------------------------
    | Shopify ScriptTags
    |--------------------------------------------------------------------------
    |
    | This option is for defining scripttags.
    |
    */

    'scripttags' => [
        /*
            [
                'src' => env('SHOPIFY_SCRIPTTAG_1_SRC', 'https://some-app.com/some-controller/js-method-response'),
                'event' => env('SHOPIFY_SCRIPTTAG_1_EVENT', 'onload'),
                'display_scope' => env('SHOPIFY_SCRIPTTAG_1_DISPLAY_SCOPE', 'online_store')
            ],
            ...
        */
    ],

    /*
    |--------------------------------------------------------------------------
    | After Authenticate Job
    |--------------------------------------------------------------------------
    |
    | This option is for firing a job after a shop has been authenticated.
    | This, like webhooks and scripttag jobs, will fire every time a shop
    | authenticates, not just once.
    |
    */

    'after_authenticate_job' => [
        /*
            [
                'job' => env('AFTER_AUTHENTICATE_JOB'), // example: \App\Jobs\AfterAuthenticateJob::class
                'inline' => env('AFTER_AUTHENTICATE_JOB_INLINE', false) // False = dispatch job for later, true = dispatch immediately
            ],
        */
    ],

    /*
    |--------------------------------------------------------------------------
    | Job Queues
    |--------------------------------------------------------------------------
    |
    | This option is for setting a specific job queue for webhooks, scripttags
    | and after_authenticate_job.
    |
    */

    'job_queues' => [
        'webhooks'           => env('WEBHOOKS_JOB_QUEUE', null),
        'scripttags'         => env('SCRIPTTAGS_JOB_QUEUE', null),
        'after_authenticate' => env('AFTER_AUTHENTICATE_JOB_QUEUE', null),
    ],
];

**Comment by ohmybrew** [comment]
Thank you. I do not see anything wrong initially. I will attempt to recreate this issue tonight.

**Comment by baljinder981** [comment]
ok sure, please do it urgent

**Comment by ohmybrew** [comment]
Sorry, I do not supply urgent help - this is free and unpaid software.

I will update you with my findings when I can get to it.

Thanks.

**Comment by baljinder981** [comment]
Have you found any solution?

**Comment by ohmybrew** [comment]
Not as of yet.

**Comment by ohmybrew** [comment]
@baljinder981 Does the shop's plan_id show as null?

**Comment by darrynten** [comment]
@ohmybrew I'm seeing this behavior too with composer.json dependency set to "^8.0". This has not happened for other apps published ~3 weeks ago.

The shops plan_id is indeed showing as NULL.

`Trying to get property 'recurring_application_charge' of non-object` gets thrown from `/src/ShopifyApp/Services/BillingPlan.php120` when using the `billable` and `auth.shop` middlewares.

The other difference between this and my other apps is that trial is set to `0` in this one.

**Comment by darrynten** [comment]
**Additional Info**

I ran a composer update on one of my apps yesterday, which updated the version from 8.0.0 to 8.0.1.

All new installs are now skipping the billing screen and the apps are being successfully installed without any charges being activated.

This happened to 2 new purchases that happened overnight.

This is how the installs look on the application activity stream. You will see there are no billing or charge events being run:

<img width="952" alt="Screen Shot 2019-07-24 at 2 49 24 PM" src="https://user-images.githubusercontent.com/3657251/61775161-9301ca80-ae22-11e9-8344-b31b35bfa901.png">

The set of events is supposed to look like this:

<img width="1154" alt="Screen Shot 2019-07-24 at 2 56 08 PM" src="https://user-images.githubusercontent.com/3657251/61775521-48348280-ae23-11e9-89d7-cc1101ace109.png">

So 2 of the events are missing.

Locking the version to 8.0 exactly (i.e. using "8.0" instead of "^8.0" in composer.json) rolls it back to a version that still works.

I'm in discussions with Shopify Support at the moment because this upgrade is now costing me sales, and I'm trying to fix the ones that have been affected.

This is across multiple installs in multiple apps.

**Comment by ohmybrew** [comment]
Hmm thanks for all the info, will attempt to find out what the issue is.

**Comment by ohmybrew** [comment]
@darrynten Adding the type to the url is not needed as its inferred from the method argument.

Fresh install via Laradock: https://streamable.com/y50id

It would skip billing if the shop was flagged grandfather or freemium mode is enabled. Thats not the case is it?

**Comment by darrynten** [comment]
@ohmybrew are you testing this on 8.0.1?

There is no freemium and no grandfathered.

The test flag is also disabled in this case, so the billing is "real" billing.

There is also a trial period enabled in this case.

The behavior was exhibiting without the type appended to the authenticate path.

Shopify support have asked me to wait until the end of the trial period to allow them to collect more data.

After the trial period expires (3 more days) then I will be sending them additional information based on what happens to the customers.

I will update here with more information once their trial periods expire.

I'm very interested in tracking down what's causing this behavior. Besides this one hiccough everything else is working quite well.

**Comment by ohmybrew** [comment]
8.0.1! Ah my bad. No I was using current. I can re-test with 8.0.1 but I suspect I would end up backporting a lot of the auth stuff in v9.

**Comment by darrynten** [comment]
Trials expired and charges reverted and the problem hasn't happened again after downgrading to 8.0

**Comment by sergeyantonuk** [comment]
Hello,
look like this issue happening again. The billing page is not showing in Shopify app it is directly installed my app on the store without any payment.
My current package ver. 12.1.0

**Comment by JosephAlonzo** [comment]
Hello @osiset I have the same issue, afther click in install app my app redirect me to login page with  "unknow error", but if a remove the billable middleware that's work

**Comment by gbrits** [comment]
I am also getting "Unknown error" when attempting to change to billing on an app that wasn't billing before. 
SHOPIFY_BILLING_ENABLED=1 in the .env file and artisan config cache cleared, it creates the user when it gives the 'unknown error' but then with the billing middleware you cannot log into the app.

**Comment by gbrits** [comment]
Could it be custom app related?

**Comment by gbrits** [comment]
**Custom App**

**YES**   - Limited to use by one merchant
**YES**   - Not reviewed by Shopify
**NO**    - Can’t be converted into a sales channel
**NO**    - Can’t use the Billing API to charge merchants

This was my problem, hopefully someone else will see this and realise their issue too.

**Comment by MGhufranKhalil** [comment]
@gbrits  yes its work for me.. but I am getting following error 

"Upgrade your account
The operation could not be completed because of the following restrictions in your current plan:

Your plan does not allow Shopify App Store purchases. You can upgrade your plan to enable Shopify App Store purchases.

As account holder you can change the plan at any time."

**Comment by gbrits** [comment]
> @gbrits yes its work for me.. but I am getting following error
> 
> "Upgrade your account
> The operation could not be completed because of the following restrictions in your current plan:
> 
> Your plan does not allow Shopify App Store purchases. You can upgrade your plan to enable Shopify App Store purchases.
> 
> As account holder you can change the plan at any time."

You will need to use the test flag as described in the documentation, friend.

**Comment by MGhufranKhalil** [comment]
> > @gbrits yes its work for me.. but I am getting following error
> > "Upgrade your account
> > The operation could not be completed because of the following restrictions in your current plan:
> > Your plan does not allow Shopify App Store purchases. You can upgrade your plan to enable Shopify App Store purchases.
> > As account holder you can change the plan at any time."
> 
> You will need to use the test flag as described in the documentation, friend.

yess thanks mate I have updated in db test 1 working fine
