### ISSUE TITLE
Add expires_on column to charges table

### ISSUE THREAD

**Issue by diemah77** [ohmybrew/laravel-shopify#281]
When working with **cancelled** recurring plans/charges I would like to know whether there are active days left in order to provide full app support until then.

Currently there is no way to perform this check. So what about an addtional charges field called `expires_on` which is populated when a plan is cancelled:

~~~~
$this->status = self::STATUS_CANCELLED;
$this->cancelled_on = Carbon::today()->format('Y-m-d');
$this->expires_on = Carbon::today()->addDays($this->remainingDaysForPeriod())->format('Y-m-d');
~~~~

Thus you can check:

~~~~
public function hasExpired()
{
   if ($this->isCancelled())
    {
    	return Carbon::parse($this->expires_on)->lte(Carbon::today());
    }

    return false;
}
~~~~
What d you say?

**Comment by ohmybrew** [comment]
`remainingTrialDaysFromCancel` should do what you're looking for.

**Comment by diemah77** [comment]
How is a trial connected to cancelled charges?

**Comment by ohmybrew** [comment]
Ah sorry misread your question.

So the issue here is the actual charge in the database doesn't get updated with what's in Shopify. If they uninstall, currently all charges are simply marked as trashed in laravel.

**Comment by diemah77** [comment]
Actually the issue is that when a charge is cancelled (but the app is **not** uninstalled) there is no way to tell for how long the app can be used before the cencelled period ends.

**Comment by ohmybrew** [comment]
Ah there's nothing I can do in this case. I don't believe there is a webhook for this, the charge would need to be manually/periodically checkee by a job or something.

**Comment by diemah77** [comment]
Maybe there is a misunderstanding: The charge is cancelled from within the app calling `$charge->cancel()`. There is no need to sync anything as all info is available from the database.

Now that the charge is cancelled and `cancelled_on` is populated in the database there is currently no method in the charge model that show for how long this cancelled charge is "active" before the current period ends. This is why I suggested a possible way how to handle it in the issue description.

**Comment by ohmybrew** [comment]
Oh I see, I thought you meant it was cancelled on Shopify's side. Yes, if its cancelled that way, I can definately add a feature like that into the charge model.

**Comment by StefanNeuser** [comment]
Hi @ohmybrew , we already implemented that. I will start a PR for this the next hours.

**Comment by ohmybrew** [comment]
@StefanNeuser Please do :)

**Comment by StefanNeuser** [comment]
Hi @ohmybrew and @diemah77 , PR is open https://github.com/ohmybrew/laravel-shopify/pull/286

**Comment by ohmybrew** [comment]
Thanks @StefanNeuser 
Will be in next patch release.
