### ISSUE TITLE
Where to run artisan?

### ISSUE THREAD

**Issue by pzheng64** [ohmybrew/laravel-shopify#282]
`$ composer require ohmybrew/laravel-shopify`
After I have finished this command to get the repo, I could not run artisan anywhere.

```
MINGW64 /e/xampp/htdocs/shopify-app/vendor/ohmybrew/laravel-shopify/src/ShopifyApp
$ php artisan vendor:publish --tag=shopify-config
Could not open input file: artisan
```

What should I do to get it running?

**Comment by SPC7RE** [comment]
Hey pzheng64, artisan is located in your main folder of your App, that would be 
`/e/xampp/htdocs/shopify-app` , there you execute the Artisan commands.  Not in vendor folder or any where else.
