### ISSUE TITLE
Error billing app after 2nd install by using "App action" in app dashboard

### ISSUE THREAD

**Issue by nonghinh** [ohmybrew/laravel-shopify#288]
Hi @ohmybrew 
I have a problem when I install app in development store. 
- Step 1: My app installed by using "App action"

![Screenshot_4](https://user-images.githubusercontent.com/13939730/61676471-446f0600-ad26-11e9-96bd-990677df22e2.png)

 
- Step 2 : After my app installed success. I try to uninstall it and uninstall successfully
- Step 3: I install app as step 1 and return an Error
![Screenshot_1](https://user-images.githubusercontent.com/13939730/61676119-fe657280-ad24-11e9-9681-f5384efcdadc.png)

But if I install app by using /login or /authenticate directory, app have no errors

**Comment by nonghinh** [comment]
This is my plan:
![Screenshot_3](https://user-images.githubusercontent.com/13939730/61676383-dd515180-ad25-11e9-9a3d-d44aee1b1b13.png)

**Comment by darrynten** [comment]
See #280
