### ISSUE TITLE
Gracefully handle shop install cancel

### ISSUE THREAD

**Issue by brianakidd** [ohmybrew/laravel-shopify#29]
Currently, if a user initiates installing the app but on the Shopify app installation screen, chooses Cancel, the user is redirected through the billing process but because their is no token available, the call to api setSession fails.

See attached.

<img width="1420" alt="screen shot 2018-05-26 at 8 36 40 am" src="https://user-images.githubusercontent.com/6431835/40576220-0c28a52a-60c0-11e8-92a3-4599a51b92ef.png">

**Comment by ohmybrew** [comment]
@brianakidd On the actual app _install_ screen you're hitting cancel? or the billing screen?

On the app install screen, I hit cancel and it returns me the Shopify app section in the admin panel.

I'll do a more expanded test however and report back... odd...

Can you let me know the steps you did, what was in the URL bar when this error appeared... just wondering if (code) was present but not set a value, and maybe I can pick up on that.

**Comment by brianakidd** [comment]
Sorry I'm just getting back to you.  The steps are to cancel on the Shopify install page and then attempt to navigate to home as if the user has reconsidered and now decided to install the app.

By entering the shopify domain and pressing install, the shop is stubbed in the database but of course there is no token, etc.

Hope this is clear.  Thanks.

**Comment by ohmybrew** [comment]
Oh I see, so attempt to install, cancel, try to install again.. I'll test
this out and see what I can come up with!

**Comment by ohmybrew** [comment]
@brianakidd [2.3.1](https://github.com/ohmybrew/laravel-shopify/releases/tag/v2.3.1) should fix you're issue.

Essentially added `$shop->shopify_token === null` as a condition to the if statement on the middleware. This will handle issue with a shop reconsidering an install and coming back to install, theyll be forced to go through the auth again.

Tests pass as well as real-world test. Let me know if this works ok for you!

**Comment by brianakidd** [comment]
Based on all of my testing, the issue has been resolved with 2.3.1.  Thank you for addressing this.
