### ISSUE TITLE
How to access headers['link'] from api-version 2019-07

### ISSUE THREAD

**Issue by fbunadi** [ohmybrew/laravel-shopify#294]
Hi,

Do you know how to access the headers['link'] from the REST request to get the link attribute (pagination https://help.shopify.com/en/api/guides/paginated-rest-results)?

I tried to do $request->response->headers and get an error that says 
`production.ERROR: Cannot access private property GuzzleHttp\Psr7\Response::$headers {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Cannot access private property GuzzleHttp\\Psr7\\Response::$headers at`

Thanks,
Fran

**Comment by bnzo** [comment]
`$linkHeader = collect($request->response->getHeader('Link'))->first();`

**Comment by fbunadi** [comment]
Thanks @bnzo !
