### ISSUE TITLE
 Your webhook for orders/create failing to return a successful response.

### ISSUE THREAD

**Issue by JDSHINDE** [ohmybrew/laravel-shopify#296]
There is webhook error when I try to upload my app to the Shopify store 
I don't want this webhook so I comment those code but still getting an error like this
![Screenshot_47](https://user-images.githubusercontent.com/46311508/62761749-166b1f00-baa5-11e9-84be-7920d1b351f4.png)

**Comment by darrynten** [comment]
@JDSHINDE can your webserver user write to `storage/framework/cache` and `storage/framework/sessions` and `storage/framework/views` and all subdirectories? 

What error code do you get? a 500?

**Comment by JDSHINDE** [comment]
@darrynten I see my api_scopes have read orders permission in Shopify-app.php but I didn't use webhooks for create/order, is that problem related with this issue?

'api_scopes' => env('SHOPIFY_API_SCOPES', 'read_products, read_orders ,read_script_tags, write_script_tags')

**Comment by JDSHINDE** [comment]
> @JDSHINDE can your webserver user write to `storage/framework/cache` and `storage/framework/sessions` and `storage/framework/views` and all subdirectories in those 3 folders?
> 
> What error code do you get? a 500?

yes, my webserver writes in these folders. I see more files in that folders

**Comment by ohmybrew** [comment]
Whats in your config for shopify-app.php

**Comment by darrynten** [comment]
@JDSHINDE what response is your webserver sending, specifically, which response code? Can you paste from /var/log/apache/access.log or similar?

**Comment by JDSHINDE** [comment]
@ohmybrew as i mentioned above there is only 
'api_scopes' => env('SHOPIFY_API_SCOPES', 'read_products, read_orders ,read_script_tags, write_script_tags')

and i only disabled my order/create webhooks.

**Comment by JDSHINDE** [comment]
@darrynten i just check my laravel log file and here is some response like

[2018-07-25 11:48:25] local.ERROR: Class 'OhMyBrew\ShopifyApp\ShopifyAppProvider' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'OhMyBrew\\ShopifyApp\\ShopifyAppProvider' not found at /home/190178.cloudwaysapps.com/qqfgfwmnbh/public_html/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208)
[stacktrace]
#0 /home/190178.cloudwaysapps.com/qqfgfwmnbh/public_html/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(144): Illuminate\\Foundation\\ProviderRepository->createProvider('OhMyBrew\\\\Shopif...')
#1 /home/190178.cloudwaysapps.com/qqfgfwmnbh/public_html/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\\Foundation\\ProviderRepository->compileManifest(Array)
#2 /home/190178.cloudwaysapps.com/qqfgfwmnbh/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(561): Illuminate\\Foundation\\ProviderRepository->load(Array)
#3 /home/190178.cloudwaysapps.com/qqfgfwmnbh/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#4 /home/190178.cloudwaysapps.com/qqfgfwmnbh/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#5 /home/190178.cloudwaysapps.com/qqfgfwmnbh/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#6 /home/190178.cloudwaysapps.com/qqfgfwmnbh/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#7 /home/190178.cloudwaysapps.com/qqfgfwmnbh/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#8 /home/190178.cloudwaysapps.com/qqfgfwmnbh/public_html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#9 {main}
"}

**Comment by darrynten** [comment]
Have you done a `composer dump-autoload`?

**Comment by JDSHINDE** [comment]
@darrynten i did but not work. can you explain me why this webhook sending request because i already comment this webhook in my shopify-app.php config and also i didn't send any API scope which is related to that webhook.

**Comment by darrynten** [comment]
What information have you configured in your .env file (only relevant information, do not post the entire file as it is sensitive).

If you have configured scopes in the .env file (or any other env options) it will always override any hardcoded scopes in your config file.

Also try removing the vendor folder completely and doing a fresh composer install and restart your web server.

**Comment by ohmybrew** [comment]
Closing for now, please reopen if issue remains.
