### ISSUE TITLE
Trial days not adjusted

### ISSUE THREAD

**Issue by Tagra** [ohmybrew/laravel-shopify#302]
##  Expected Behavior

When app is reinstalled trail days should be adjusted

## Current Behavior

When app is reinstalled trail days are not adjusted 

## Failure Information

User can always use trail and never pay by reinstalling app

### Steps to Reproduce

1. Install app on trail
2. Adjust active charge dates 
3. Reinstall app
4. Again full trail is offered 

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v5.3.0
* Laravel Version: v5.7.28

It show that this failure is fixed in v3.0 but it does not work.

**Comment by ohmybrew** [comment]
Is your app uninstall webhook working, this is whats needed to cancel the charge and do calculation based on that.

**Comment by Tagra** [comment]
Yes it is working. When uninstalled current charge status is set to cancelled, cancelled_on data is calculated - everything seems ok.  But when i reinstall full trial period is offered once again.

**Comment by Tagra** [comment]
I am lost, if i understand correctly - https://github.com/ohmybrew/laravel-shopify/blob/e63352e241169c9f5ade4effcfffa63381feac9f/src/ShopifyApp/Services/BillingPlan.php#L137

It`s not checking previous charges but always setting full trail.

**Comment by darrynten** [comment]
@Tagra interesting problem, if I understand correctly a user can just install/uninstall/reinstall at the same frequency of the trial period and use the app for free indefinitely?

**Comment by ohmybrew** [comment]
Ah! You're right... seems remainingTrialDaysFromCancel is not being used... will have to work that in.

**Comment by darrynten** [comment]
@ohmybrew perhaps track the day/timestamp the trial started and don't change it on a reinstall?

I suppose even created_at could be used.

**Comment by Tagra** [comment]
It is very easy fix, you just need to find shops previous charge and use function remainingTrialDays which is already there.

btw @ohmybrew great job, thanks for this package ! :)

**Comment by ncpope** [comment]
I was actually just going through the codebase because I noticed a shop on one of my apps had a high number of uninstalls. I discovered that they were reinstalling just before the trial period was hitting. It's a shame that people are out there that would take advantage of something like this. Obviously they're finding value in the app, after-all they are going through so much trouble...

@Tagra Thanks for pointing this one out

**Comment by ohmybrew** [comment]
v10 has support for this issue. Will close for now, if issue, reopen please :)

**Comment by andreuka** [comment]
hi there!

It not working still, I found how to fix that.

https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/Services/BillingPlan.php#L247

`$pc = $this->shop->planCharge($this->plan->id);`
to
`$pc = $this->shop->planCharge($this->plan->id);`

https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/Traits/ShopModelTrait.php#L157

`->where('plan_id', $this->plan_id)`
to
`->where('plan_id', $planID)`
