### ISSUE TITLE
[Question] Product based teired plans?

### ISSUE THREAD

**Issue by Kyon147** [ohmybrew/laravel-shopify#303]
Just wondered how to go about pushing someone to another planned by how many products they have. 

We store their products in the DB through a sync button, which runs a function that pulls in the data from the API.

I've tried running a redirect to the next billing plan but it does not work. Also this way is not very secure, as they could just go back and that's that.

 ```
$number_of_products = Product::where('shop_id', '=', $shopifyID)->count();
            \Log::info("Number of products " . $number_of_products);
            switch ($number_of_products){
                case $number_of_products < 1001 :
                    \Log::info("Move to plan 1");
                    return redirect()->route('billing', ['plan_id' => 1]);
                    break;
                case $number_of_products > 1000 && $number_of_products < 2501 :
                    \Log::info("Move to plan 2");
                    return redirect()->route('billing', ['plan_id' => 2]);
                    break;
                case $number_of_products > 2500 && $number_of_products < 5001 :
                    \Log::info("Move to plan 3");
                    return redirect()->route('billing', ['plan_id' => 3]);
                    break;
                default:
                   return redirect()->route('billing', ['plan_id' => 1]);
            }
```

Still having a mess with it but thought I'd see what your thoughts where.

**Comment by StefanNeuser** [comment]
Hi @Kyon147 , it seems this a a issue within your implementation not within the package. @ohmybrew is there already a stackoverflow section for this kind of questions?

**Comment by ohmybrew** [comment]
@Kyon147 Not really sure what you're trying to do here. Looks correct, but yes could be the implementation, not sure what you mean by the merchant going back. I'll close for now.

@StefanNeuser Theres no SO section... good idea though.
