### ISSUE TITLE
AuthShop is failing

### ISSUE THREAD

**Issue by StefanNeuser** [ohmybrew/laravel-shopify#306]
Hi @darrynten , i have a issue with the last change. Auth is not working anymore because the exception is thrown everytime and it seems there is no `code` in the input when i open the app from the shopify admin. Do you have any idea?

https://github.com/ohmybrew/laravel-shopify/blob/5b68ee73272dbde83316b6cc09e3eaea4059af0d/src/ShopifyApp/Middleware/AuthShop.php#L165

i guess there is a missing check like here:
https://github.com/ohmybrew/laravel-shopify/blob/5b68ee73272dbde83316b6cc09e3eaea4059af0d/src/ShopifyApp/Middleware/AuthShop.php#L203

Here you can see what shopify is sending in the first request:

<img width="1404" alt="Screenshot 2019-08-12 at 19 59 45" src="https://user-images.githubusercontent.com/2176503/62886642-cfe32200-bd3b-11e9-90f6-440d0fae3a36.png">

@ohmybrew i guess that the `code` within the request from shopify-admin is only set for a `full-auth` flow. So thats why the `verifyRequest` is failing for us. Maybe i did something wrong?

**Comment by ohmybrew** [comment]
Ah yeah... code is only for the full auth flow. Hmm.

**Comment by StefanNeuser** [comment]
I recommend to roll this back because apps will be broken if they deploy the app with something like envoyer :)

**Comment by ohmybrew** [comment]
@StefanNeuser  Its not released, its on master so we're ok here to continue work on fixing it.

**Comment by darrynten** [comment]
@StefanNeuser @ohmybrew working on this right now

**Comment by darrynten** [comment]
@StefanNeuser @ohmybrew see #309 for the fix
