### ISSUE TITLE
Updating package

### ISSUE THREAD

**Issue by mabrodeur** [ohmybrew/laravel-shopify#31]
Hi,

What would be the best way to update the package using composer when you make a new release?
I have `"ohmybrew/laravel-shopify": "^2.0"` in my composer.json, but when I run `composer update ohmybrew/laravel-shopify`, nothing happens.

Also, will this update your `ohmybrew/basic-shopify-api` package at the same time?

Thanks

**Comment by brianakidd** [comment]
It may be worth checking out composer versions [here](https://getcomposer.org/doc/articles/versions.md).  Once you determine the correct version and update your composer file, run `composer update ohmybrew/laravel-shopify --with-dependencies`

Hope this helps.

**Comment by mabrodeur** [comment]
Adding `--with-dependencies` did the trick. The update went through

```
Package operations: 0 installs, 5 updates, 0 removals
  - Updating doctrine/common (v2.7.3 => v2.8.1): Loading from cache
  - Updating doctrine/dbal (v2.5.13 => v2.7.1): Loading from cache
  - Updating guzzlehttp/guzzle (6.3.0 => 6.3.3): Loading from cache
  - Updating ohmybrew/basic-shopify-api (v1.0.1 => v3.0.1): Loading from cache
  - Updating ohmybrew/laravel-shopify (v2.2.0 => v2.3.1): Loading from cache
```

The thing is after updating, when trying to view the app in my store I get:
```
Illuminate \ Database \ QueryException (HY000)
SQLSTATE[HY000]: General error: PDO::ATTR_STATEMENT_CLASS requires format array(classname, array(ctor_args)); the classname must be a string specifying an existing class (SQL: select * from `shops` where (`shopify_domain` = my-dev-store.myshopify.com) limit 1)
```

**Comment by ohmybrew** [comment]
Googling this seems to suggest people downgraded to 2.6 of Doctrine DBAL. Others say the PHP version caused the issue. So I am not sure... What's the version of Laravel and PHP you're using?

**Comment by mabrodeur** [comment]
PHP Version 7.0.12
Laravel 5.5.34

**Comment by ohmybrew** [comment]
Googling seems to say the DBAL version is incompatible with that PHP version... hmm, can you try forcing doctrine/dbal to be ^2.5.0 in your composer.json?

**Comment by mabrodeur** [comment]
I updated my PHP version to 7.1.13, updated the packages and now it works.
Maybe we should add a note in the readme saying that >= 2.3.0 version requires PHP >= 7.1.x?

**Comment by ohmybrew** [comment]
Yeah, it's more the fault of something specific in the doctrine DBAL. I may
just fix it's version to be lower. I'll think on this. But for now I'll
close and thank you for testing this.

**Comment by ohmybrew** [comment]
Based on research, I may just bump the package to 7.1 minimum. 7.0 is rather old at this point and forcing an old version of DBAL may not be ideal.

**Comment by ohmybrew** [comment]
Resolved in master, will be in next version push, thanks.
