### ISSUE TITLE
Websockets Auth

### ISSUE THREAD

**Issue by Kyon147** [ohmybrew/laravel-shopify#311]
Not sure if this has been covered but, trying to authenticate the Broadcast Channels in Laravel and by default it uses Auth:User.

As we are using a custom authentication method, trying to connect to web sockets does not work as I am trying to use the shop id to compare it with the shop id with the broadcast event but it is not working.

Is there something I am missing to get this to work with your package?

```
Broadcast::channel('shop.{id}', function ($user, $id) {
    $shop = ShopifyApp::shop();
    return (int) $shop->id === (int) $id;
});
```

**Comment by Kyon147** [comment]
After trying for 2 days, seems like it has something to do with the fact that broadcasting/auth uses the standard Auth middleware which passes $user over to the channel.

As you use a custom auth middleware and the default Auth does not do anything, we need to bind $user to the Shop model I assume for verification. Just not 100% sure if this is the right way to go.

I assume we could do something like this in AuthShop?

```
$request->merge(['user' => $user]);

$request->setUserResolver(function () use ($user) {
   return $user;
});
```

**Comment by ohmybrew** [comment]
Hey @Kyon147 

Sort of.. but Shop model needs to implement a few interfaces for it to properly work as a "user" class in laravel.

I briefly looked into it around v3 release but it turned out to be a nice bit of work that I wasn't comfortable taking on.

At the moment, I am not sure I have a suggestion for you.

**Comment by Kyon147** [comment]
@ohmybrew no worries, looking at it for a couple of days I can see it is a big bit off work and a little bit out of my skill depth if I'm honest at the moment.

I'll probably have a mess around with on a dev set up as I'm still not that confident with your package to go messing around properly. 

Look forward if you get around to doing this as it would be wicked to tie websockets into the apps by using the native broadcast service.

I'll close this for now.
