### ISSUE TITLE
Paginated REST API

### ISSUE THREAD

**Issue by fbunadi** [ohmybrew/laravel-shopify#313]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

The rest api will pass in the params as it is

## Current Behavior

The page_info that shopify received is different with the one that I pass in. 

## Failure Information

Invalid page_info value

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
Create a rest api request to Shopify. Check the header, if there's attribute 'link', get that and grab the 'next' link
2. Step 2
Extract the 'next' link, separate the order rest api url, with the params. 
You get url: '/admin/api/2019-10orders.json
Params: array('limit' => 100, 'page_info' => 'abcd')
3. Step 3
Pass all those information back to $shop->api()->rest

Here's the code:
````
$domain = $this->shop->getAttribute('shopify_domain'); //get the domain
  $the_link = preg_replace('/<https:\/\/'.$domain.'|>$/', '', trim($nextpage));
  $main_url = substr($the_link, 0, strpos($the_link, '?'));
  $params_link = substr($the_link, strpos($the_link, '?')+1);
  $keywords = preg_split("/[\s,=,&]+/", $params_link); //split the links with white space comma = and &
   $params = [];
    for($i=0; $i<sizeof($keywords); $i++) {
       $params[$keywords[$i]] = $keywords[++$i];
    }
    $api_request = $this->shop->api()->rest('GET', $main_url, $params);
````

If I dd($params), I will get 
```
array:2 [▼
  "limit" => "100"
  "page_info" => "eyJjcmVhdGVkX2F0X21pbiI6IjIwMTktMDgtMTYgMDA6MDA6MDAgVVRDIiwibGFzdF9pZCI6MTE0Nzg2MzAwNzI3OCwibGFzdF92YWx1ZSI6IjIwMTktMDgtMTcgMTA6NDU6MTgiLCJkaXJlY3Rpb24iOiJuZXh0In0%3D ◀"
]
```
If I dd($api_request), I will get
```
{#6810 ▼
  +"response": Response {#6807 ▶}
  +"errors": {#6801 ▼
    +"status": 400
    +"body": {#268 ▶}
    +"exception": ClientException {#6808 ▼
      -request: Request {#6803 ▶}
      -response: Response {#6807 ▶}
      -handlerContext: []
      #message: """
        Client error: `GET https://xxx.myshopify.com/admin/api/2019-10/orders.json?limit=100&page_info=eyJjcmVhdGVkX2F0X21pbiI6IjIwMTktMDgtMTYgMDA6MDA6MDAgVVRDIiwibGFzdF9pZCI6MTE0Nzg2MzAwNzI3OCwibGFzdF92YWx1ZSI6IjIwMTktMDgtMTcgMTA6NDU6MTgiLCJkaXJlY3Rpb24iOiJuZXh0In0%253D` resulted in a `400 Bad Request` response: ◀
        {"errors":{"page_info":"Invalid value."}}
        """
      #code: 400
      #file: "/home/theyyy/public_html/xxx/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php"
      #line: 113
      trace: {▶}
    }
  }
  +"body": ""
  +"timestamps": array:2 [▶]
}
```
Please notice how there's additional %25 (located almost at the end of the value) in the page_info from shopify's error message. This additional %25 makes the value to be invalid. 

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v7
* Laravel Version: v5.8
* PHP Version: v7.3
* Using a toolset (Docker, Laradock, Vagrant, etc.): none

**Comment by ohmybrew** [comment]
At the end of your page_info value you have %3D which is a =.

You need to decode this before sending it through the API.

The issue you're seeing is Guzzle is re-encoding the value which makes the issue.

**Comment by fbunadi** [comment]
Awesome. Thanks!
