### ISSUE TITLE
Restricting DB data to only the connected shop/user

### ISSUE THREAD

**Issue by polibou** [ohmybrew/laravel-shopify#314]
*Originally, posted this question in the wrong repo, so moving it here:*

I'm a Laravel newbie and maybe I missed it somewhere here, but how is everyone managing queries for each shop so that they only have access to their own data? Currently I'm passing a shop ID condition in to all my queries. Is there something built in that passes the shop ID or other authenticated ID to the model?

General search is suggesting that I extend the model to include the shop ID so I don't have to added it to every query. I'm still trying to figure out how to do this. However it seems like a package that is designed to handle multiple shops would have this already, so I think I'm missing something.

Reply from: ohmybrew
> I think you meant to put this into laravel-shopify, my other repo?
> 
> Either way, yes, the currently shop is authenticated and stored in session.
> The shop info is then pulled from the database (shopify_token).
> The token is used in the requests outbound which is the correct shop.

Thanks for the response.  I do understand how to get the current authenticated shop.  My question is how do you use the current authenticated shop's info to set up queries to get database data (not API request) for that particular store?  Is the model already set up to do that?

For example lets we're using this repo to build an app with a database table that stores product information.  The app is then installed by multiple stores.  When a shop accesses the app they only need to see their products.  What is the best way to accomplish this elegantly?

Right now I am doing something like:
$products = DB::table('products')->where('shop_id', $shopID);

Is it possible to to something like this:
$products = DBauthenticatedShop::table('products');

I imagine most apps having multiples tables and a bunch of queries so I would like to eliminate setting up this condition on all queries.  I do understand this is more of an architectural question, but, if we're all building apps everyone would have this issue.  Any insight appreciated,  thanks.

**Comment by Kyon147** [comment]
Hi @polibou 

Checking against the store_id column is probably the correct approach as you are tying back the data specific to that store.

You could extend the DB class to do this for you but you'd still need to the shop_id column in each table otherwise you'd have no clue how to connect the data. For this reason, you are better of for simplicity doing it the way you want.

Your other option is mult-tenancy each shop has it's own DB but again require more work.

**Comment by ohmybrew** [comment]
Yeah as @kyon147 suggested things should work fine that way. If you extend the Shop model and add your own relationship mappings it'll work out fine like this: (on phone so will be brief)

// In the new modal:
Public function products() {
  Return $this->hasMany('products');
}

// In controller or service:
$shop = ShopifyApp::shop();
$products = $shop->products;

**Comment by polibou** [comment]
@ohmybrew The relationship mapping seems like what I'm after, but it looks like it would only work with eloquent.  For now I'm avoiding eloquent as its adds to the learning curve of Laravel and it adds a performance hit from what I've researched.

I'm probably going to go the route @Kyon147 mentioned since I originally needed a shop_id column on all my tables anyways.  Thanks guys.

**Comment by Kyon147** [comment]
> @ohmybrew The relationship mapping seems like what I'm after, but it looks like it would only work with eloquent. For now I'm avoiding eloquent as its adds to the learning curve of Laravel and it adds a performance hit from what I've researched.
> 
> I'm probably going to go the route @Kyon147 mentioned since I originally needed a shop_id column on all my tables anyways. Thanks guys.

The shop_id is the way I do it if you also then index tables that use it quite heavily you can get some performance gains out of it. Just don't index everything as of course the index will be rebuilt every time an insert or update is performed.
