### ISSUE TITLE
how to remove signature with new hmac

### ISSUE THREAD

**Issue by quangta** [ohmybrew/laravel-shopify#32]
Undefined index: signature. 
My Error : signature is dereated.
MD5 signature is no longer supported since 1st June.Can u help me ? 

$signature = $query['signature' in AuthProxy.php

**Comment by quangta** [comment]
Fixed: 
<?php namespace OhMyBrew\ShopifyApp\Middleware;

use Closure;
use Illuminate\Http\Request;

class AuthProxy
{
    /**
     * Handle an incoming request to ensure it is valid
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure                 $next
     *
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        // Grab the data we need
        $query = request()->all();
        foreach($query as $param => $value) {
            if ($param != 'signature' && $param != 'hmac') {
        		$params[$param] = "{$param}={$value}";
        	    }
		}
	   asort($params);
		
		$params = implode('&', $params);
		$hmac = $_GET['hmac'];
        $shared_secret=config('shopify-app.api_secret');
		$calculatedHmac = hash_hmac('sha256', $params, $shared_secret);
        if ($hmac != $calculatedHmac || !isset($query['shop'])) {
            // Issue with HMAC or missing shop header
            abort(401, 'Invalid proxy signature');
        }
       

        // All good, process proxy request
        return $next($request);
    }
}
Now ! It's working .

**Comment by ohmybrew** [comment]
For proxy verification? [Per docs](https://help.shopify.com/api/guides/application-proxies) its still using signature.

Can you explain where you're seeing this error.

**Comment by quangta** [comment]
Thank you. I 'm wrong . Finally, it working...
Have a nice day !
