### ISSUE TITLE
ITP 2.1 (Safari not working)

### ISSUE THREAD

**Issue by andreuka** [ohmybrew/laravel-shopify#324]
Hi there!

In last versions of sarafi (12.1+) implemented ITP 2.1 which completely breaking the application.

Safari now blocks all cookies from 3rd party websites unless they didnt requested special access: https://webkit.org/blog/8613/intelligent-tracking-prevention-2-1/

Do you know about this issue and is there plans to implement ITP 2.1 support?

Thanks alot!

**Comment by bilfeldt** [comment]
duplicate issue #277

**Comment by ohmybrew** [comment]
See above, thanks!
