### ISSUE TITLE
How would I manually make an API call without being logged in?

### ISSUE THREAD

**Issue by polibou** [ohmybrew/laravel-shopify#325]
Need to access the shops during a cron jobs so the they wouldn't be logged in, but I already have their token and the rest of their info from the install.

For example to get orders I have:
$orders = ShopifyApp::shop()->api()->rest('GET', '/admin/orders.json');

How can this be modified somehow to explicitly set the shop?

Thanks

**Comment by andreuka** [comment]
Hi there!

I wrote special function for that in my app:

`function getShopApi( $shop_id ){
        $shop = \OhMyBrew\ShopifyApp\Models\Shop::where([
            ['id' , '=', $shop_id]
        ])->first();
        $shop = $shop->toArray();
        $api = new BasicShopifyAPI();
        $api->setShop($shop['shopify_domain']);
        $api->setAccessToken($shop['shopify_token']);

        return $api;
    }`

Hope that will help you as well.

**Comment by polibou** [comment]
Awesome!  Did exactly what I needed.  Thank you!
