### ISSUE TITLE
Clicking on links generated by shop_route returns Unable to verify signature exception

### ISSUE THREAD

**Issue by ronald2wing** [ohmybrew/laravel-shopify#326]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Should go to the named route.

## Current Behavior

Returns Unable to verify signature. exception.

## Failure Information

throw new Exception('Unable to verify signature.');
Exception 
…/vendor/ohmybrew/laravel-shopify/src/ShopifyApp/Middleware/AuthShop.php197

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a route. (Ex: Route::get('/', 'ArticleController@index')->middleware(['auth.shop'])->name('home');)
2. Use shop_route.
3. Click on the generated link. (Ex: https://3f08f459.ngrok.io?shop=testing.myshopify.com)

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v9.2.0
* Laravel Version: v5.8.34
* PHP Version: v7.3.0
* Using a toolset Homestead release branch.

### Failure Logs
throw new Exception('Unable to verify signature.');
Exception 
…/vendor/ohmybrew/laravel-shopify/src/ShopifyApp/Middleware/AuthShop.php197

**Comment by ohmybrew** [comment]
Closing, known issue, removed in master for next release :) as there has been PRs which make shop_route useless now :)

**Comment by ronald2wing** [comment]
@ohmybrew Can you tell me how long this issue is going to fix? Are we going to use shop_route() in the future?

**Comment by Kyon147** [comment]
There's been a lot of changes to how the app authenticates through other contributions and some of have changed how the session is generated for each store. 

The shop_route is now not needed as the authenticate method checks to see if the store requesting is the store that has a valid session. If not it will reauth and get a new session, so shop_route() should not be needed anymore as it is automatic.

**Comment by ronald2wing** [comment]
@Kyon147  Thanks you. Everything is clear now. But the documentation is kind of out of dated. Can you tell me where it mentioned the shop_route() is not needed anymore?
