### ISSUE TITLE
Unable to upgrade to Laravel 6.0

### ISSUE THREAD

**Issue by jesephan** [ohmybrew/laravel-shopify#329]
`Problem 1
    - Installation request for ohmybrew/laravel-shopify ^9.2 -> satisfiable by ohmybrew/laravel-shopify[v9.2.0].
    - Conclusion: remove laravel/framework v6.0.0
    - Conclusion: don't install laravel/framework v6.0.0`

**Comment by emiliolodigiani** [comment]
There is already PR #328 for Laravel 6 compatibility. Hoping to see it merged soon.

**Comment by ohmybrew** [comment]
Merged, in v10 release. Thanks!
