### ISSUE TITLE
how to use multiple apps?

### ISSUE THREAD

**Issue by jackkam85** [ohmybrew/laravel-shopify#332]
We need multiple apps for laravel shopify, How to use it?

**Comment by StefanNeuser** [comment]
You need help by integrating apps?

**Comment by ncpope** [comment]
@jackkam85 you will need to make use of the namespace capabilities of the Shop model

https://github.com/ohmybrew/laravel-shopify/wiki/Namespacing-Your-App

**Comment by ohmybrew** [comment]
@ncpope Is correct, any issues with it, open an issue :)
