### ISSUE TITLE
AuthShop middleware failing with bulk actions

### ISSUE THREAD

**Issue by marko-behm** [ohmybrew/laravel-shopify#336]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

AuthShop should be  able to validate requests with ids parameter which gets set when using bulk actions from Shopify (ie. selecting multiple products -> actions -> "custom bulk action")

## Current Behavior

Authentication fails because only id parameter is processed.

## Failure Information

See OhMyBrew\ShopifyApp\Middleware\AuthShop::getQueryDomain()
$id = $request->input('id') ?? null;

foreach (compact('code', 'locale', 'state', 'id') as $key => $value) {
    if ($value) {
        $verify[$key] = $value;
    }
}

fixed:
// 2019-10-01 There is ids (array) parameter when receiving request from bulk operations
$ids = $request->input('ids') ?? null;

foreach (compact('code', 'locale', 'state', 'id', 'ids') as $key => $value) {
    if ($value) {
        $verify[$key] = is_array($value) ? '["' . implode('", "', $value) . '"]' : $value;
    }
}

Same fix should be in all getXXXDomain() methods where validation occurs.

### Steps to Reproduce

1. Step 1
Add bulk action on products page
2. Step 2
select multiple products and choose your bulk action

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: 10.0
* Laravel Version: 6.0
* PHP Version: 7.2

### Failure Logs

Unable to verify signature.

**Comment by ohmybrew** [comment]
Interesting...thanks I'll adjust for this tonight

**Comment by ohmybrew** [comment]
Thank you will be in next release.
