### ISSUE TITLE
trial days not working still after reinstall

### ISSUE THREAD

**Issue by andreuka** [ohmybrew/laravel-shopify#337]
hi there!

The trial days after reinstall still starting from initial value, I found how to fix that.

https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/Services/BillingPlan.php#L247

`$pc = $this->shop->planCharge($this->plan->ID);`
to
`$pc = $this->shop->planCharge($this->plan->id);`

https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/Traits/ShopModelTrait.php#L157

`->where('plan_id', $this->plan_id)`
to
`->where('plan_id', $planID)`

_Originally posted by @andreuka in https://github.com/ohmybrew/laravel-shopify/issues/302#issuecomment-537025217_

**Comment by ohmybrew** [comment]
Thank you. Will adjust.

**Comment by ohmybrew** [comment]
In for next release.
