### ISSUE TITLE
How to post data from store's front to APP?

### ISSUE THREAD

**Issue by lyongdee** [ohmybrew/laravel-shopify#34]
How to post data from store's front to APP?

**Comment by tobiasdalhof** [comment]
Can you clarify your issue, please?

**Comment by lyongdee** [comment]
@tobiasdalhof, I'm a newbie developer of Shopify app, I want to know how to develop an APP just like [Product views](https://apps.shopify.com/product-reviews) step by step. Do u know any courses or Sample?

**Comment by ncpope** [comment]
@lyongdee You should be able to do the leg work when it comes to creating your app. This is way too broad of a question. If you have a specific question feel free to ask it here but "step by step" instructions? I don't think that's something you should be asking here.
