### ISSUE TITLE
Laravel Passport API with Laravel Shopify

### ISSUE THREAD

**Issue by benmag** [ohmybrew/laravel-shopify#341]
Really cool package, saved me so much time already!

I was wondering if there's a way to take advantage of [Laravel Passport](https://laravel.com/docs/6.x/passport) while using this package?

My ideal scenario would be to have an api route like `/v1/{shopify_domain}/campaigns` with authorization handled through passport so I can easily open up an API for my app in the future

**Comment by ohmybrew** [comment]
Hey @benmag I think I looked into this before and decided it would require essentially a whole new API backend to support passport unless things have changed... it was too much for me to take on.

**Comment by benmag** [comment]
@ohmybrew I had a quick look too and that was my impression as well but just wanted to check :)
