### ISSUE TITLE
Redirect to login form if domain not set?

### ISSUE THREAD

**Issue by tom-it** [ohmybrew/laravel-shopify#342]
Sorry if this is not the right place for this, It looks like when I go to the default route with incognito mode I just get thrown an exception "Unable to get shop domain." Wouldn't it make more sense to redirect to the /login page if no shop data has been found?

I like to have a nice / basic landing page for my apps, in case someone finds it. I'd be happy to create a pull request for this, if this is something you agree on.

**Comment by Kyon147** [comment]
What version of the package are you using? 

This was brought up and fixed in [v10.1.0](https://github.com/ohmybrew/laravel-shopify/releases/tag/v10.1.0)

**Comment by tom-it** [comment]
> What version of the package are you using?
> 
> This was brought up and fixed in [v10.1.0](https://github.com/ohmybrew/laravel-shopify/releases/tag/v10.1.0)

Hmm, looks like I'm on v10.1.0 according to my composer.json. 

could you point me to where this code would handle the redirect specifically?

**Comment by Kyon147** [comment]
An exception was added, you can view the commit here:

https://github.com/ohmybrew/laravel-shopify/commit/b6dde2f935c6ede7ee555b465c9a5f902b571cc5

**Comment by tom-it** [comment]
> An exception was added, you can view the commit here: [b6dde2f](https://github.com/ohmybrew/laravel-shopify/commit/b6dde2f935c6ede7ee555b465c9a5f902b571cc5)
> 
> Just to add:
> 
> On production, it will redirect to /login
> 
> On any other environment, the exception will be thrown which gives you the option to catch it and handle it however you like.

aah gotcha, I was looking in dev offcourse. makes sense now, thanks!
