### ISSUE TITLE
shopify-config file env api keys not get the package

### ISSUE THREAD

**Issue by kashif-sol** [ohmybrew/laravel-shopify#343]
**When I have installed shopify package for the app.**
I have updated API keys in shopify-config file in larawel but when I run app it says empty API keys.
after some troubleshooting, I have added the same API keys in the vendor package shopify-config file.
Then it does not give any error.
I think we need to add these API keys only in larawel config shopify-config.

**Comment by ohmybrew** [comment]
Running: `php artisan vendor:publish --tag=shopify-config` will put a file in `config` for you. Enter your values there or with env vars.

Please utilize our issue template as well in the future.

**Comment by kashif-sol** [comment]
I have run this command and created shopify-config file but donot pick values from this file.

**Comment by ohmybrew** [comment]
I just gave this a try on a new install and it went fine. Its an issue with your Laravel, your filesystem, permissions, or something else.

Please fill out a full bug report with our issue template if you would like us to investigate more.

**Comment by kashif-sol** [comment]
sorry for that.

**Comment by kashif-sol** [comment]
ok Let me try.
