### ISSUE TITLE
Extended trial days through link?

### ISSUE THREAD

**Issue by Kyon147** [ohmybrew/laravel-shopify#346]
I'm messing about with it at the moment but wondered if anyone know the best way to authenticate a store through a landing page /special-offer and when a store enters their store URL it goes through the Auth process and then instead of doing the on_install plan actually give them another plan that has a longer trial days set.

**Comment by Kyon147** [comment]
Sorted it.

For anyone who wants to do something similar.

1. Create your plan in the plans table and take note of the ID.
2. Created a landing page - I just copied the /login plage and replace the form action to your own controller route.
3. In the controller file.

```
    //Return to view with the install form etc
    public function index()
    {
        return view('custom_plan');
    }

    public function custom_plan(AuthShop $request){

        //Set the return route to a plan so it goes straight to your plan after auth.
        $request->session()->put('return_to', route('billing', ['plan_id' => 2]) );

        //Create a new AuthController instance so you can authenticate the store.
        $authenticate = new AuthController();

        //Return the instance so that the user is redirected to Shopify for authentication.
        return $authenticate->authenticate($request);
    }
```

This will then auth the shop through Shopify and instantly redirect them with a plan that has the custom trial days.

**Comment by ohmybrew** [comment]
Sorry I've been super busy.
Thats a good method.

I noted in another closed issue recently, that I may find a way to introduce hooks (similar to Wordpress), so people can mod things before/after an action is done... like swap out the plan dynamically instead of the on_install plan set.
