### ISSUE TITLE
Shopify POS embedded app authentication

### ISSUE THREAD

**Issue by bogdanghervan** [ohmybrew/laravel-shopify#348]
I intend to use the library with a Shopify POS embedded app. It looks like the authentication middleware (`AuthShop`) may not be compatible with such an app.

It looks as though it enters the bad session flow causing a redirect (using `fullpage_redirect.blade.php`) that doesn't seem to be supported by the POS.

What should be the correct way to go about doing the authentication in the POS?

**Comment by tealendril** [comment]
POS Authentication is done via ShopifyPOS.init (setup info can be found here https://help.shopify.com/en/api/embedded-apps/shopify-pos-app-sdk/initialization )

You would want to:
1.  remove shopify auth middleware from your POS routes
2. create a different middleware that will just grab url params and parse them to the view 
3. or simply grab the shopify domain from the url via js.

Shopify POS request will contain various url params including "shop" i.e. shopify domain

The example below should get you started:
```
     var url = new URL(window.location);
     var shop = url.searchParams.get("shop");

      if(shop) {
        ShopifyPOS.init({
          apiKey: '{{ config('shopify-app.api_key') }}',
          shopOrigin: `https://${shop}`,
          debug: true,
          forceRedirect: true
        });
      }

**Comment by ohmybrew** [comment]
Hi @bogdanghervan 

I currently have no way of testing or supporting the POS.

If its as simple as what @tealendril, I can make a new branch for you with abilities to "turn on" POS, but I won't have a way to physically test it right now.

Let me know either way.
