### ISSUE TITLE
update from 2.3 to 10.x

### ISSUE THREAD

**Issue by Enmaboya** [ohmybrew/laravel-shopify#349]
hi!
There is an application on laravel 5.6.

decided to update it.  but it uses ohmybrew / laravel-shopify version 2.3.  Is there any instruction on how to upgrade to the latest version painlessly?

**Comment by Kyon147** [comment]
v10.0.0 had changes to be in line with Laravel version 6.0 so you should have no problem on 5.6 as that is what I am currently using for one project.

You just need up update Laravel-Shopify in the composer and then download the new package changes. 

**However,** a lot of changes have happened in the last few months and the auth flow had changed quite a bit so I would test upgrading on a development site first to make sure no breaking changes have been introduced that you need to refactor your code for.

**Comment by ohmybrew** [comment]
Hey, @Kyon147 is spot on.

A lot of people have sent in PRs for new features and flows.

Best to dupe your app, follow the UPGRADE doc in the wiki all the way through for hints of breaking changes.

Thanks!
