### ISSUE TITLE
Any example to add javascript to a store?

### ISSUE THREAD

**Issue by ardnor** [ohmybrew/laravel-shopify#35]
Hi @ohmybrew or any who know this can advise me on how to add your javascript to a store?

Thank you.

**Comment by tobiasdalhof** [comment]
You mean a ScriptTag (https://help.shopify.com/api/reference/online_store/scripttag)?

Have a look at your `shopify-app.php` config

```php
    /*
    |--------------------------------------------------------------------------
    | Shopify ScriptTags
    |--------------------------------------------------------------------------
    |
    | This option is for defining scripttags.
    |
    */
    'scripttags' => [
        /*
            [
                'src' => env('SHOPIFY_SCRIPTTAG_1_SRC', 'https://some-app.com/some-controller/js-method-response'),
                'event' => env('SHOPIFY_SCRIPTTAG_1_EVENT', 'onload'),
                'display_scope' => env('SHOPIFY_SCRIPTTAG_1_DISPLAY_SCOPE', 'online_store')
            ],
            ...
        */
    ],
```

**Comment by ardnor** [comment]
@tobiasdalhof Yes, you are right. I will test it. Thank you.

**Comment by ardnor** [comment]
Is it still working in local?

**Comment by tobiasdalhof** [comment]
It works locally with a http tunnel like ngrok.io

**Comment by ardnor** [comment]
Okay, thank you. I will try to figure it out.

**Comment by ohmybrew** [comment]
@ardnor Yes, this is the correct way. List the scripts there and a job process will install them on authentication. Ngrok does some odd things, so I can not guarentee it will work but through Homestead and Valet, it is working for me via (https://localhost.local) I have setup.

I'll close for now, but if you run into a bug, feel free to make an issue :)

**Comment by ardnor** [comment]
@ohmybrew Thank you for your comment. I am using Windows machine right now.

**Comment by veed76** [comment]
Hi @ohmybrew 
I installed the app in my Shopify store and added the script tag in the shopify-app.php file, but in fronend, it won't display.

Here is my code

```
'scripttags' => [
            [
                'src' => env('APP_URL')."/js/crawlapps-cli-offer.js",
                'event' => env('SHOPIFY_SCRIPTTAG_1_EVENT', 'onload'),
                'display_scope' => env('SHOPIFY_SCRIPTTAG_1_DISPLAY_SCOPE', 'online_store')
            ],
    ],
```
Please guid me where I'm wrong.
Thank you.
