### ISSUE TITLE
default index route

### ISSUE THREAD

**Issue by muhammadasfar** [ohmybrew/laravel-shopify#351]
I have removed index route from my routes/web.php 

In v7.1.1 if there is no index route in routes/web.php or shop domain is not valid, package redirect shop or user to login page 

and now I am using **v10.2.1.**

## Expected Behavior

If shop domain is not existed or invalid or there is no index route in routes/web.php , package must show login page like v7.1.1

## Current Behavior

throwing error **Unable to get shop domain.**

## Failure Information

I think, if shop domain is not existed instead of throwing error form function named as **getShopDomain** in **src/ShopifyApp/Middleware/AuthShop.php** at line number **136** package should redirect to login route.

### Steps to Reproduce

1. Install  v10.2.1 & Laravel v5.8.x
2. Remove index route from routes/web.php
3. Call your index route by calling  https://yourdomain.com, will show error.

### Context

* Package Version: v10.2.1
* Laravel Framework 5.8.35
* PHP Version: 7.2.22
* Valet Linux

### Failure Logs

local.ERROR: Unable to get shop domain. {"exception":"[object] (OhMyBrew\\ShopifyApp\\Exceptions\\MissingShopDomainException(code: 0): Unable to get shop domain. at /mypath/myUser/Sites/myappname/vendor/ohmybrew/laravel-shopify/src/ShopifyApp/Middleware/AuthShop.php:136)

**Comment by Kyon147** [comment]
One of the changes to version 10 was a custom exception handler the MissingShopDomainException as you can see in the error log. To make the app as free as possible for all types of developers strict logic like redirecting to the login page was removed to allow developers to create their own rules for handling this stuff.

So this does not look like a bug but how the app should work. You need to capture the error yourself and handle it how you like.

**Comment by muhammadasfar** [comment]
@Kyon147  okay thanks
