### ISSUE TITLE
Clarification on use with SPAs

### ISSUE THREAD

**Issue by fourstacks** [ohmybrew/laravel-shopify#352]
Thanks very much for all the effort that's gone into this package - it's a great resource!

I have a question regarding the use of this package in an SPA context.  I'm specifically looking for some clarification on the requirements listed out in #305.  In that PR @darrynten mentions that a number of headers need to be appended to requests made by the SPA:

X-Shop-Domain - the domain of the target store
X-Shop-Signature - the signature (a.k.a. hmac)
X-Shop-Time - the timestamp used in the creation of the signature
X-Shop-Code - the code used in the creation of the signature

Like @StefanNeuser, I'm building my apps with InertiaJS.  If you're not familiar with that library then the only important thing to note is that my app largely functions like an SPA in that the majority of calls from the front end are ajax calls made using axios under the hood.

I know how to modify the instance of axios that InertiaJS uses to make calls to add an interceptor to add these additional headers to requests BUT I'm really not clear where some of the values are meant to come from.  My javascript is aware of the shop domain so I could add that header and obviously time would be easy enough but how would my JS send the code and signature headers back.

Sorry if I'm missing something super obvious (quite possible!) - any clarification on this would be really helpful.  Thanks!

**Comment by ohmybrew** [comment]
Sorry, I have not dabbled in SPA for the embedded apps yet. I'm not sure I could provide the answers you need. I can do some digging though, but I would say @darrynten would have a good answer.

**Comment by fourstacks** [comment]
Hey @ohmybrew - thanks for the reply and no problem.

@darrynten - would you be able to shed some light on the above by any chance?  Any insight greatly appreciated!

**Comment by Kyon147** [comment]
@fourstacks I've started building a SPA, so will check to see what I did to handle the requests. 

It would still be good to hear @darrynten thoughts on it as he probably has a better implementation anyway!

**Comment by fourstacks** [comment]
@Kyon147 that would be great - would be very interested to hear how you've integrated with this package!

**Comment by fourstacks** [comment]
@ohmybrew - is there a resolution to this question?  Appreciate you probably want to close inactive issues to keep things tidy but I'd still really appreciate any tips or guidance on how those headers are supposed to be used in an SPA context.  The fact they are in the package at all suggests that someone knows!

**Comment by Kyon147** [comment]
Hey @fourstacks 

Sorry for the massive delay to replying, I've only just picked up the SPA project I am working on again and wanted to give some bits a test before replying.

What issue are you facing? With the package, I am able to make calls using Axios without any additional issues. I'm using VueJS but I have a method which is tied to a button that fires this code.

**Vue component file, in the methods**

```
 axios.post('add', this.data)
                    .then(res => {
                        console.log(res);
                    }).catch(err => {
                        console.log(err);
                })
```

**web.php**

`Route::post('add', 'Controller@add_data')->name('add data test');`

This is sending and receiving data back without any issue or additional headers, as long as the csrf token is in your header so requests can be made via ajax you should be okay.

` <meta name="csrf-token" content="{{ csrf_token() }}"> `

**Comment by ptcampbell** [comment]
I haven't had to change the headers or treat my workflow differently with my SPA (React using Polaris components). All of my Shopify requests are happening through this package via PHP but through their respective resource controllers which extend this package's auth middleware.

**Comment by fourstacks** [comment]
Hi @Kyon147 and @ptcampbell 

Thanks for the replies - much appreciated.  I'm not really facing an issue per se, but I'm curious as to why those specific headers are checked in the package.  If you are embedded your application then you have to be careful not to bleed session info in situations where a store owner is logged into two different stores in two browsers.  Those headers are designed to ensure that the shop domain is always checked to make sure that things are scoped appropriately but I was curious as to how the 'code' header would be set.

To be honest I think we can probably wrap this thread up as I think we're all taking slightly different SPA approaches from the sound of things.  Also we've decided to move away from the embedded approach since I first wrote this post so a lot of these issues are not really relevant in my situation right now so I'll probably not have anything useful to add for now.

Thanks again for the responses!

**Comment by ptcampbell** [comment]
@fourstacks do you mind if I ask you why you are moving away from embedded? I am thinking of doing the same thing.

**Comment by Kyon147** [comment]
I thought about moving away from embedded but I think the user experience is better when it's in the Shopify admin. 

Some apps work not embedded when they need a more bespoke dashboard like Privy or Loyalty Lion.

**Comment by fourstacks** [comment]
Hey @ptcampbell, so we got a reasonable way with embedded but ultimately the app we're building just has a bit too much going on to cram into the limited real estate that you get when you go embedded.  There's not really a great solution for subnavigation in Polaris yet for example.  We've also found the dev experience with embedded apps to be a bit clunky and hard to debug.

We'll be watching embedded closely over the next year or so and would like to move over to it again if some of those issues are sorted but for now we're liking the increased canvas that we have to play with having chosen a non-embedded Polaris app instead

**Comment by ptcampbell** [comment]
@fourstacks thanks for sharing. I think I'm in the same boat. However as I looked more into it I discovered that the embedded `ResourcePicker` is such a high value item for me and the trade-off might just be six of one, half a dozen of the other. But the debugging is a huge pain too.
