### ISSUE TITLE
embedded app issue

### ISSUE THREAD

**Issue by NirajSavaliya** [ohmybrew/laravel-shopify#354]
When I installing the embedded app, then the first time it's opening in a new window but it should open inside Shopify.

but after installation, when I opening second time then it's opening in Shopify.

same issue I facing when first time opening in private mode of browser and second time working fine.

can you guide what will be an issue?

**Comment by ptcampbell** [comment]
It sounds like you need to enable `forceRedirect` in the ESDK / App Bridge. (#117)

**Comment by NirajSavaliya** [comment]
@ptcampbell 

Thanks, You saved my lots of hours.
