### ISSUE TITLE
Migration: Unable to locate publishable resources

### ISSUE THREAD

**Issue by ptcampbell** [ohmybrew/laravel-shopify#355]
### Expected Behavior
I wondered if I had issues upgrading but even with a fresh installation running `php artisan vendor:publish --tag=shopify-migrations` results in the error `Unable to locate publishable resources`.

### Current Behavior
Running `php artisan vendor:publish` yields the following tags (providers omitted). 

```
  [9 ] Tag: flare-config
  [10] Tag: ignition-config
  [11] Tag: laravel-errors
  [12] Tag: laravel-mail
  [13] Tag: laravel-notifications
  [14] Tag: laravel-pagination
  [15] Tag: shopify-config
  [16] Tag: shopify-jobs
  [17] Tag: shopify-views
```

Using latest version of this package (10.2) and Laravel 6. 

**Edit**: I'm updating from way back (v3 or so) and did not realise migrations were handled automatically now. Still, from the wiki it looks like this should work out of the box. Also, the comment in `shopify-config` about manual migration refers to the tag as `migrations` not `shopify-migrations`

**Comment by ohmybrew** [comment]
@ptcampbell Yup. Its because of the line `if (Config::get('shopify-app.manual_migrations')) {`.

Which is default by false.

```
    /*
    |--------------------------------------------------------------------------
    | Manual migrations
    |--------------------------------------------------------------------------
    |
    | This option option allows you to use:
    | `php artisan vendor:publish --tag=migrations` to push migrations
    | to your app's folder so you're free to modify before migrating.
    |
    */
    'manual_migrations' => (bool) env('SHOPIFY_MANUAL_MIGRATIONS', false),
```

Set to true, and the `shopify-migration` will show up. Otherwise, it does it automatically. I'll fix up the docs :) I'll close this issue now, unless there's something else? Re-open if so!

**Comment by Hujjat** [comment]
Hey @ohmybrew 

Just wanted to say Thank you :) It worked

**Comment by poppabear8883** [comment]
@osiset just wanted to state that the Wiki is still not updated and had to spend 20 minutes to find this.

**Comment by osiset** [comment]
@poppabear8883  Updated, slipped the radar, thanks
