### ISSUE TITLE
Redirect loop on app load

### ISSUE THREAD

**Issue by MarinX** [ohmybrew/laravel-shopify#356]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Redirect to Admin where app loads into iframe

## Current Behavior

It goes into redirect loop where finally fails on Shopify side asking me to enable 3rd party cookies.

## Failure Information

This is only happening if you enable AppBridge
Looking at the console log:
```javascript
index.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://xxxx.myshopify.com') does not match the recipient window's origin
```

### Steps to Reproduce

1. Clean install / latest install of laravel-shopify
2. Use AppBridge (which is by default, example app)
3. Issue will occur

### Context

I checked other apps which are on older version of laravel-shopify and issue is also there.
I dont think this is the issue from package itself, but either from Chrome or Shopify Bridge SDK.
Wanted to know if anyone else is getting this issue and how we can solve it?

* Package Version: v10.2
* Laravel Version: v6.2
* PHP Version: v7.2
* Using a toolset (Docker, Laradock, Vagrant, etc.): Laradock
* Chrome Version: 78.0.3904.97

### Failure Logs

None

**Comment by ptcampbell** [comment]
Is it on `https://`? 

Have you got `forceRedirect=true` on the AppProvider?

**Comment by MarinX** [comment]
@ptcampbell yes, its on https and I tried both with forceRedirect true/false.
Even apps that worked before now stopped working :/

**Comment by MarinX** [comment]
I tested with Safari Version 13.0.3 (14608.3.10.10.1) and Firefox 69.0.3 (64-bit) on macOS and its working.
Seems like its Chrome issue.

**Comment by MarinX** [comment]
Ok, so I found the issue.
Enabling experimental features on Chrome will block the app from loading inside iframe.
After removing that option, it works fine now.
Closing the issue...
