### ISSUE TITLE
laravel-shopify can't override the homepage route.

### ISSUE THREAD

**Issue by lyongdee** [ohmybrew/laravel-shopify#36]
[Wiki](https://github.com/ohmybrew/laravel-shopify/wiki/Overriding-and-Extending)

**Comment by tobiasdalhof** [comment]
404

**Comment by ncpope** [comment]
What is the code that you are writing? What is your expectation of what should happen? What errors are you encountering? Just linking to the wiki of the project page isn't very helpful.

**Comment by ohmybrew** [comment]
Hi @lyongdee 

Does `\OhMyBrew\ShopifyApp\ShopifyAppProvider::class,` come BEFORE or AFTER `App\Providers\RouteServiceProvider::class,` in `config/app.php`?

I believe Laravel is seeing the package's `GET /` route first and ignoring yours. So, placing the `\OhMyBrew\ShopifyApp\ShopifyAppProvider::class,` AFTER 
 `App\Providers\RouteServiceProvider::class,` should solve your issue :)

**Comment by lyongdee** [comment]
@ohmybrew Yes, that's right. 
\OhMyBrew\ShopifyApp\ShopifyAppProvider::class  must after 
App\Providers\RouteServiceProvider::class 
in app.php.
`'providers' => [
    ...
        \OhMyBrew\ShopifyApp\ShopifyAppProvider::class,
        App\Providers\RouteServiceProvider::class,
    ]`
