### ISSUE TITLE
Scripttag installler is not working.

### ISSUE THREAD

**Issue by prem-techchefs** [ohmybrew/laravel-shopify#360]
I am new to shopify app development. That's I am raising this issue.
As per given documentation I install and try to use custom scripttag. I am getting following error.

{"errors":{"script_tag":"expected Array to be a Hash"}}
 in /Applications/AMPPS/www/shopify_app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

**Comment by Kyon147** [comment]
Script tags are installed via the config file, that then runs as a job as part of the Webhook job controller I believe.

This error looks like you are trying to get a script but none exist on the store that you are trying to get it from.

Do you have your script in the config file that installed it for you?

**Comment by prem-techchefs** [comment]
Yes I have my script in config file. Let me show you what I had tried till now.
In shopify-app config file I have enabled 
`'scripttags' => [

            [
                'src' => env('APP_URL')."/js/subscription.js",
                'event' => env('SHOPIFY_SCRIPTTAG_1_EVENT', 'onload'),
                'display_scope' => env('SHOPIFY_SCRIPTTAG_1_DISPLAY_SCOPE', 'online_store')
            ],

    ],`

and after that I enabled 
`'after_authenticate_job' => [

            [
                'job' => \OhMyBrew\ShopifyApp\Jobs\ScripttagInstaller::class,
                'inline' => env('AFTER_AUTHENTICATE_JOB_INLINE', true) 
            ],

    ],`


This is how I am approaching my solution but getting failure. Please help me out.

**Comment by ohmybrew** [comment]
Please edit your original post to use the issue template.
