### ISSUE TITLE
Unable to get shop domain. 

### ISSUE THREAD

**Issue by Hujjat** [ohmybrew/laravel-shopify#362]
## Expected Behavior
When I update the `route>web.php` with example provide in doc, I get that error. It should redirect me to login page. 

 
## Current Behavior

It thro an error.

![laravel-shopify-error](https://user-images.githubusercontent.com/5115878/70144079-42b04880-16f1-11ea-993b-182aa8785866.png)

### Steps to Reproduce

1. Installed laravel app
2. ran `php artisan ui vue --auth`
3. installed the package
3. published the assets and migrate
4. updated the web.php and added the routes
5. view in browser and got error. 

### Context

* Package Version: ^10.2
* Laravel Version: 6.2
* PHP Version: 7.3
* Using a toolset (Docker, Laradock, Vagrant, etc.): laravel valet

Thanks.

**Comment by Kyon147** [comment]
Are you viewing this in the browser on your local machine, or through a Shopify Store with the app installed?

**Comment by inazeem** [comment]
Change values in your .env file. app_debug=true and APP_ENV=local to APP_ENV= production. That will sort the issue. If you are working on local machine then it is very much expected behaviour.

**Comment by ptcampbell** [comment]
In my view, even in development mode, this should still redirect to the login page. Switching to production in a development environment is not really a solution. Obviously you will need to extend the `HomeController` to include your own logic when not in production — but I am not sure why the distinction exists between environments.

**Comment by Hujjat** [comment]
Hey @Kyon147 & @inazeem 

This error shouldn't happen. When I set `APP_ENV=production`, it doesn't show the error page but the functionality is still missing. When I enter shop URL and click install, it goes to the auth page and redirects back to the login page. 

It never shows the dashboard. 

@Kyon147 I'm using Laravel valet. `valet share` to make it publicly accessible. 

Thanks.

**Comment by Kyon147** [comment]
@Hujjat have you tried updating to v10.2.1 as @ohmybrew applied a patch for a similar issue.

**Comment by Hujjat** [comment]
Hey @Kyon147 

Yes I tried.  No luck. 

If I make debug mode false in laravel, I don't get any error, But when login to store, It redirects me back to the login page every time. I can't set session.

**Comment by Hujjat** [comment]
I created a fresh laravel and installed the package again. It works now. 

This time, I didn't add the laravel auth. 

Thanks, everyone for the great package.

**Comment by fyroc** [comment]
Interestingly, I'm getting this error in my error logs. Can you re-open?

**Comment by darrynten** [comment]
I'm also experiencing this issue, am looking for a solution

**Comment by Kyon147** [comment]
I am getting this on production when heading to the route, through the browser directly i.e the login page. Going through Shopify app store seems fine though.

I'll also do some digging and have a stab at it too.

**Comment by polibou** [comment]
I've also been getting this error for a few months.  It was low priority so just starting to look at it now.  My app is not embedded so maybe it's effecting only those app since @Kyon147 mention it is fine when going through Shopify.

Did a little more digging and found that the redirect code below.  Turned of debug in env and redirected to login as expected. 

`abstract class BaseException extends Exception
{
    /**
     * Render the exception into an HTTP response.
     *
     * @param \Illuminate\Http\Request The incoming request.
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function render(Request $request)
    {
        if (!Config::get('app.debug')) {
            // If not in debug mode... show view
            return Redirect::route('login')->with('error', $this->getMessage());
        }
    }
}`

I'm not sure why it would be setup to only redirect when not in debug mode.  I agree with @ptcampbell that there shouldn't be a distinction made dev vs production or debug vs no debug.

**Comment by polibou** [comment]
Did a little more research and it looks like it is setup this way so each app can handle the error however they wish.

For those of us just looking to have it redirect to the login, I was able to do it by adding the code below to the file `/app/Exceptions/Handler.php` in your own app.

```
    public function render($request, Exception $exception)
    {
        if ($exception instanceof \OhMyBrew\ShopifyApp\Exceptions\MissingShopDomainException) {
            return redirect()->route('login');
        }

        return parent::render($request, $exception);
    }
```

**Comment by makhchan** [comment]
> idn't add the laravel auth

What you mean with this point ? what is the diff, I still face same issue.

**Comment by baberuth22** [comment]
Why does this work if embedded and error out if not embedded?   It seems like my app has to be embedded now.
