### ISSUE TITLE
406 api error

### ISSUE THREAD

**Issue by nithinnitzarya** [ohmybrew/laravel-shopify#37]
Hi,
I tried to insert a code using asset API of Shopify. but it returned a 406 error - _**Client error: `PUT https://good-time-store.myshopify.com/admin/themes/14690353211/assets.json` resulted in a `406 Not Acceptable` response**_

This is my code
$api = $shop->api();
        $asset = [
            [
                'key' => 'layout/theme.liquid',
                'value' => 'hello'
            ]];
  
        $result = $api->request(
            'PUT',
            '/admin/themes/14690353211/assets.json',
            ['asset' => $asset]
        );

**Comment by ncpope** [comment]
@nithinnitzarya  try
```php
$asset = [
    'key' => 'layout/theme.liquid',
    'value' => 'hello'
];
```

It looks like you have an unnecessary  array

**Comment by nithinnitzarya** [comment]
@ncpope 

I changed that but again got an another error  - **_Client error: `PUT https://good-time-store.myshopify.com/admin/themes/14690353211/assets.json` resulted in a `422 Unprocessable Entity` response: {"errors":{"asset":["Missing {{content_for_header}} in the head section of the template","Missing {{content_for_layout}} (truncated...)_**

**Comment by nithinnitzarya** [comment]
@ncpope @ohmybrew  Any Solution? still am getting these errors tried a lot of combinations

**Comment by brianakidd** [comment]
@nithinnitzarya keep in mind this package provides a wrapper to Guzzle for making the HTTP request.  What @ncpope recommended resolved the 406 error - have you looked specifically at the 422 error response in terms of the missing content?

The 422 is telling us that the request was processed by Shopify's API and it didn't meet the validation for updating the underlying resource.

Hope this helps.

**Comment by nithinnitzarya** [comment]
@brianakidd @ncpope Wow !!! Finally !! Validation was the issue. I was trying to write on the theme file without header and layout. 
I have added that and the error vanished ;)
Thanks a lot
