### ISSUE TITLE
BREAKING BUG: Bulk action URLs broken due to shop parameter

### ISSUE THREAD

**Issue by fyroc** [ohmybrew/laravel-shopify#372]
## Current Behavior

When clicking on a bulk action link, you are redirected to the login page with the error:

**Oops! An error has occured: Unable to verify signature.**

Example URL:
https://someapp.com/order/edit?id=786876786867&shop=vndortesting.myshopify.com

However if I pass in the follow URL, it works fine:
https://someapp.com/order/edit?id=786876786867

The problem is, Shopify creates these parameters and the shop parameter breaks everything.

* Package Version: master
* Laravel Version: v5.8
* PHP Version: v7.3
* Laravel Forge:

**Comment by ptcampbell** [comment]
Related to #359 I believe. This issue started happening for me today too, but I'm not passing any additional parameters. :/

**Comment by jasperpoppe** [comment]
+1 for me too!

**Comment by fyroc** [comment]
I also found that embedded apps work fine.

**Comment by jedimdan** [comment]
@fyroc I found that it's not consistent, so I'm guessing Shopify is progressively releasing the new parameters. We had one embedded app that was set up a few times on Shopify (production, vs various other environments etc but the same app), and some of these setups would receive the new parameter while some others didn't. Unfortunately for us, our production happened to be one of the setups that did receive the new parameters.

**Comment by MarinX** [comment]
I'am still getting the error even if I upgrade to dev-master. Some apps are affected and some of them are not. I suspect it's a same case you described @jedimdan

**Comment by jedimdan** [comment]
@MarinX this issue has been resolved in the latest release. I recommend going back to the latest version instead of using `dev-master`

**Comment by naveedmunsif09** [comment]
I am still getting this same error, my version is 17
