### ISSUE TITLE
at /Applications/MAMP/htdocs/****/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664

### ISSUE THREAD

**Issue by jhd3197** [ohmybrew/laravel-shopify#38]
![screen shot 2018-06-08 at 12 26 59 am](https://user-images.githubusercontent.com/13461850/41138952-b3eb4f0a-6ab2-11e8-8c22-917e5a8088b0.png)
![screen shot 2018-06-08 at 12 27 06 am](https://user-images.githubusercontent.com/13461850/41138953-b3fc9c1a-6ab2-11e8-842a-f255a168def4.png)

**Comment by ohmybrew** [comment]
Hey @jhd3197 
This is an issue with your configuration. It seems homstead DB doesnt exist as @brianakidd mentioned, or in a quick Google, a port may be missing in your .env or config/database.php.

[Check this SO thread](https://stackoverflow.com/questions/35394230/sqlstatehy000-2002-connection-refused-within-laravel-homestead) for more information.

I'll close as this is not repo-specific for now. Thanks!
