### ISSUE TITLE
hmac check fail ,show Unable to verify signature

### ISSUE THREAD

**Issue by jackkam85** [ohmybrew/laravel-shopify#380]
I got also a  issue by verifying the signature. I added a new parameter that comes from the shopify redirect for the hmac check. The parameter is called 'session', show fail information ."Unable to verify signature."
version:  "ohmybrew/laravel-shopify": "^10.2.1", 
https://abcdefg.com/abcdefg?hmac=07fa93730d12b2e348c27d8292abd9a64a83b2343187c5d802975b9a651cfc62&locale=en&session=6b0b108cb88203e71a365bd4d9a951a9d4f32d5711be0cb8ba8e6211b3a51b8d&shop=testshop.myshopify.com&timestamp=1580384493

**Comment by Kyon147** [comment]
There are multiple issues on this at the moment:

#359 
#277 

A fix is being worked on I believe but not sure when the release is.

**Comment by jedimdan** [comment]
Fix has just been released in v10.3.0

**Comment by ohmybrew** [comment]
@jedimdan correct.. forgot this in my release notes, oops. Yes code now takes all params rather than the few before and runs it through the hmac verification.

**Comment by jackkam85** [comment]
thank you~

**Comment by pmayet** [comment]
Same problem for me with v10.3.1 on fresh install
