### ISSUE TITLE
Laravel -> Session Driver : cookie samesite error

### ISSUE THREAD

**Issue by tzookb** [ohmybrew/laravel-shopify#388]
## Expected Behavior

Working with 10.3 should be able to support samesite cookie changes with laravel session config with "cookie" as driver.

## Current Behavior

I have "session" config driver as "cookie".
With that, the samesite is not set properly.
But when I use the "file" driver Im able to login normally on Shopify.

### Steps to Reproduce

- just use "session"."driver" as "cookie"
- go to shopify app when chrome samesite flags are on
- getting to a loop until you get the third party cookies error

### Context

I'm quite sure it's not relevant to this package.
But just wondering what you guys use for "session.driver"?

**Comment by ohmybrew** [comment]
There's a bug for some browser versions for 10.3 a PR is open for me to merge in today and release. Should fix the issue based on the comments in the PR. Chrome is cancer...

**Comment by tzookb** [comment]
😆 cant agree more

I think thats the PR:
so I'll just ref it here and close the ticket 💪🏼

https://github.com/ohmybrew/laravel-shopify/pull/386
