### ISSUE TITLE
Disabled eSDK

### ISSUE THREAD

**Issue by hakimihamdan88** [ohmybrew/laravel-shopify#39]
eSDK still not disabled when setting is SHOPIFY_ESDK_ENABLED=0 in env
any idea?

**Comment by ohmybrew** [comment]
Hey @hakimihamdan88 

Do you have it turned off in the app settings as well through the partner dashboard?

What issue are you experiencing?

**Comment by hakimihamdan88** [comment]
i dont see any setting to turn off EASDK on app setup

**Comment by brianakidd** [comment]
Go to your app in the partner portal and choose **Extensions** -> **Embedded app** -> **Manage embedded app** and on the next screen, choose **Disable**.

**Comment by ohmybrew** [comment]
^ Yup :), the ESDk setting in the package simply tells the layout to *not* load the ESDK JS, and allow your app to run outside the iframe of Shopify. I'll see about updating the wiki somewhere with this information.

@hakimihamdan88 Let us know if that works for you!

**Comment by hakimihamdan88** [comment]
<img width="1087" alt="screen shot 2018-06-08 at 10 35 01 pm" src="https://user-images.githubusercontent.com/1689992/41163801-41c452fe-6b6c-11e8-9f21-3ba43b5aa254.png">
after disabled EASDK, i cant open my installed app. any idea guys?
