### ISSUE TITLE
weird safari mixed content on authentication

### ISSUE THREAD

**Issue by tzookb** [ohmybrew/laravel-shopify#390]
##  Expected Behavior

When I "login" to the app from shopify admin, I'll see the app.

## Current Behavior

When I login through chrome everything works well.
When I do the same on safari, I get an error of mixed content.

As the console show an error:
<img width="504" alt="Screen Shot 2020-02-11 at 16 23 37" src="https://user-images.githubusercontent.com/3749973/74244958-ec601700-4cea-11ea-9530-4013dbf8a59c.png">

## Failure Information

Please help provide information about the failure if this is a bug.

### Steps to Reproduce

1. Login to my shop
2. go to apps
3. click on my app
4. see the error above

* just to note, I did enable 3rd party cookies just in case as I read this open issue:
https://github.com/ohmybrew/laravel-shopify/issues/277

## Context 

* Package Version: v10.3.1
* Laravel Version: v5.7.x
* PHP Version: v7.3
* Using a toolset Docker

**Comment by Kyon147** [comment]
This is an on-going issue in Safari as you mentioned in #277

**Comment by tzookb** [comment]
thanks @Kyon147 

I thought its related as well, but one of the comments mentions to enable cookies and it will work.

what I did do is debugged the code until the code that "redirects" to the "authenticate" route.

Even tough the request came from https, the Request "isSecured" method returned false.
Then I saw that the `$_SERVER['HTTPS']` wasn't even set and thats why it was false.

**Comment by darrynten** [comment]
Does adding `URL::forceScheme('https');` to the `boot()` method in your project `app/Providers/AppServiceProvider.php` file resolve your problem?

**Comment by tzookb** [comment]
thanks @darrynten 
that resolved it 💪🏼

**Comment by tzookb** [comment]
still not sure why laravel thinks its not https

but I good with forcing it :)
