### ISSUE TITLE
Shopify notification about SameSite=none

### ISSUE THREAD

**Issue by StefanNeuser** [ohmybrew/laravel-shopify#393]
##  Expected Behavior

Because we are using the latest release of this package, SameSite=none should be working.

## Current Behavior

Shopify notified us, that we are still setting the wrong cookie without SameSite=none .. in the chrome dev tools screenshot it is looking fine.

So my question is, did you also receive that kind of email?

<img width="1177" alt="Screenshot 2020-02-20 at 16 24 26" src="https://user-images.githubusercontent.com/2176503/74949228-c1b64280-53fd-11ea-9b2f-ebfa3c8d4440.png">

<img width="599" alt="Screenshot 2020-02-20 at 16 16 07" src="https://user-images.githubusercontent.com/2176503/74948756-07bed680-53fd-11ea-8faf-ca40fa97b1a3.png">

**Comment by ohmybrew** [comment]
Maybe it's some automated crawler that hits your main app install page. I would guess any cookies there (should be none?) wouldn't have the samesite since the config is not yet modified by the package.

**Comment by StefanNeuser** [comment]
Hi @ohmybrew , that makes sense, i will figure it out and respond soon.
