### ISSUE TITLE
Not a bug, After upgrading to v.10 Uninstall webhook stop working

### ISSUE THREAD

**Issue by muhammadasfar** [ohmybrew/laravel-shopify#394]
**Not a bug**

After debugging I have found a solution for it. 

Why uninstall webhook stop working after upgrading 
v.7 to v.10 or
v.8 to v.10 or
v.9 to v.10?

After upgrading the package in the existed database of the app a column named `expires_on` was missing in the table `charges`   

After creating this column `expires_on` in the table `charges` manually, the uninstall webhook starts working properly.

I did not find this in the [Wiki upgrading](https://github.com/ohmybrew/laravel-shopify/wiki/Upgrading#9xx--1000) doc so that's why I have opened an issue to highlight it here.

**Comment by Kyon147** [comment]
Did you run `artisan:migrate` after updating your package?

**Comment by muhammadasfar** [comment]
@Kyon147  No, I did not. I think it needs to be mentioned in [wiki upgrading](https://github.com/ohmybrew/laravel-shopify/wiki/Upgrading#9xx--1000)
