### ISSUE TITLE
Migrations don't publish

### ISSUE THREAD

**Issue by Jamesking56** [ohmybrew/laravel-shopify#399]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Migrations are published when calling `php artisan vendor:publish --tag=shopify-migrations` as per the Wiki.

## Current Behavior

`php artisan vendor:publish --tag=shopify-migrations` results in an error:

```
Unable to locate publishable resources.
```

## Failure Information

I now don't know what migrations I need to use this package.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install the latest version of this package
2. Run `php artisan vendor:publish --tag=shopify-migrations`
3. See the error

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v10.3.1
* Laravel Version: v6.12.0
* PHP Version: v7.4.3
* Using a toolset (Docker, Laradock, Vagrant, etc.): Docker

### Failure Logs

N/A

**Comment by Jamesking56** [comment]
Nevermind, didn't realise you have to set the env key for that to work.

**Comment by adrianthedev** [comment]
Which env keys are you referin to @Jamesking56? I've set up these ones and the migrations are still not publishing.

```
SHOPIFY_API_KEY
SHOPIFY_API_SECRET
SHOPIFY_APP_NAME
SHOPIFY_MANUAL_MIGRATIONS
SHOPIFY_API_SCOPES
```

**Comment by adrianthedev** [comment]
Nevermind. Got it. You have to add `SHOPIFY_MANUAL_MIGRATIONS=true`. Thank you!
