### ISSUE TITLE
No Sample Get And POST Method Example To Access Shopify API

### ISSUE THREAD

**Issue by ssinghtorinit** [ohmybrew/laravel-shopify#48]
Hello, I Have Installed The App And Now Want To Add Few Products From App API. 
I Am unable TO Find POST Method How Exactly It Will Be Done Both POST And Get Please Add At least 1 Example of Both.

Thanks

**Comment by brianakidd** [comment]
@ssinghtorinit,

Please see [Accessing API for the current shop](https://github.com/ohmybrew/laravel-shopify/wiki/Usage#accessing-api-for-the-current-shop) in the Usage section of the Wiki.

In the example, `$shop->api()` provides a `GuzzleHttp\Client` that can be used to interact with the shop's API, see [here](http://docs.guzzlephp.org/en/stable/).

You can then refer to the Shopify documentation for the [Product API](https://help.shopify.com/api/reference/products/product#create) to determine how to structure your request.

**Comment by ohmybrew** [comment]
Yup, as @brianakidd said, the API method returns an instance of [this package](https://github.com/ohmybrew/basic-shopify-api#making-requests), which internally uses Guzzle. 
You're able to make requests as REST or GraphQL.

I've updated the doc with a little example to make it more clear :) will close unless you have an issue feel free to open!
