### ISSUE TITLE
Overriding Routes

### ISSUE THREAD

**Issue by shawnhind** [ohmybrew/laravel-shopify#49]
In the [overriding documentation](https://github.com/ohmybrew/laravel-shopify/wiki/Overriding-and-Extending#controllers--routes) it mentions that: 

> If you're overriding routes, be sure to open config/app.php and move this package's provider to be after Laravel's provider. Example:
```
App\Providers\RouteServiceProvider::class,
\OhMyBrew\ShopifyApp\ShopifyAppProvider::class,
```

When I did this my overrides didn't seem to work but when I did the reverse of what this suggested (putting ShopifyAppProvider before the RouteServiceProvider) it did work.  Am I misunderstanding this or could this be a problem with the documentation?

**Comment by ohmybrew** [comment]
When you did the reverse as in this package above app's? Thats odd, ill test this, as Laravel when it sees the route (in 5.5 anyways) it would not listen to another defined route of the same path... maybe they changed this behaviour, ill check for you.

**Comment by shawnhind** [comment]
Yeah that's correct, when I defined RouteServiceProvider and then ShopifyAppProvider it still went to the default ShopifyApp controller.  When I did the reverse it went to my controller as expected.

**Comment by shawnhind** [comment]
This is with laravel 5.6.

**Comment by shawnhind** [comment]
@ncpope did you change yours because you were having the same problem that I was?

**Comment by ohmybrew** [comment]
It appears you're both correct! WIll update the wiki, sorry about that.
