### ISSUE TITLE
ShopifyAppFacade should be ShopifyApp

### ISSUE THREAD

**Issue by SilverPaladin** [ohmybrew/laravel-shopify#5]
Docs instruct you to add this line to config/app
`'ShopifyApp' => \OhMyBrew\ShopifyApp\Facades\ShopifyAppFacade::class,`

but you should use this line
`'ShopifyApp' => \OhMyBrew\ShopifyApp\Facades\ShopifyApp::class,`

because ShopifyAppFacade does not exist.

**Comment by ohmybrew** [comment]
Hey sorry... no notification came to me.

Thanks for noting this, I will fix this the weekend!
