### ISSUE TITLE
Using triple store as model

### ISSUE THREAD

**Issue by shawnhind** [ohmybrew/laravel-shopify#51]
Sorry if this isn't appropriate as an issue.

I have a use case where I need to use a triple store (graph database such as Blazegraph or Amazon Neptune) rather than a relational database.  From what I can tell laravel-shopify relies on eloquent for storing model information.

Would it be feasible to override parts of the module that use eloquent with my own read and write methods on a graph database?

**Comment by ohmybrew** [comment]
It would be a lot of work, you would have to override a lot of files. It may be worth your while to maintain your own internal fork for it.

**Comment by shawnhind** [comment]
So would it be more than just writing read and write methods in the shop model?

**Comment by ohmybrew** [comment]
Off the top of my head, it's using firstOrCreate, save, few where methods. The new version coming gets more complex in that there's ankther related model added to the mix. I'm not sure what to suggest to you though as yes, it's dependence is on eloquent.
