### ISSUE TITLE
Webhook is falling

### ISSUE THREAD

**Issue by nithinnitzarya** [ohmybrew/laravel-shopify#58]
Can anyone please help me to find a solution for this?
Why this is happening? I am getting a lot of emails like this.

Your webhook for orders/cancelled at //url is failing to return a successful response.       This webhook has been attempted 2 times.     If your webhook continues to fail, it will be removed and your application will not receive any more notifications. | Your webhook for orders/cancelled at //url is failing to return a successful response. | This webhook has been attempted 2 times.     If your webhook continues to fail, it will be removed and your application will not receive any more notifications.
-- | -- | --
Your webhook for orders/cancelled at //url cancelled is failing to return a successful response.
This webhook has been attempted 2 times.     If your webhook continues to fail, it will be removed and your application will not receive any more notifications.

**Comment by ncpope** [comment]
Have you tried the steps in the wiki? You can find the instructions here: https://github.com/ohmybrew/laravel-shopify/wiki/Creating-Webhooks

If you have, can you show the related code that you wrote such as your routes and your jobs.

Do you have a queue worker running that should be responding to this job? This wouldn't cause the error above but it's something to keep in mind.

Are you sending this to an https route? Shopify sends webhooks to publicly accessible url's. You wouldn't be able to send this to your localhost unless it's publicly accessible. If your app is not exposed to the internet and you are using Laravel valet you can try running `valet share`

Hopefully this helps

**Comment by ohmybrew** [comment]
@ncpope Thanks!

As ncpope stated, check it out. But I noticed your webhook errors have "//" for the url, I think it's not setup correctly, it has a bad url somehow possibility. You may need to use the API to kill all existing webhooks and start fresh.
