### ISSUE TITLE
Object not found when going to authenticate page

### ISSUE THREAD

**Issue by lucasvm** [ohmybrew/laravel-shopify#62]
Hello

 I have followed all the steps, my app, is under src/ShopifyApp  i have created on psr-4 the namespace like this:

 "src\\ShopifyApp\\": "src/ShopifyApp" 

 however when i try to see the site im getting object not found 

 Also i have added this and everything is ok:

 $ php artisan vendor:publish --tag=config
Copied File [\src\ShopifyApp\resources\config\shopify-app.php] To [\config\shopify-app.php]
Publishing complete.

Any ideas? im missing something? using url: http://local.shopify-app.com/authenticate, the url is on my localhost because i can see the index.html with the title.

added to My composer.json:
"psr-4": {
            "App\\": "app/",
            "src\\ShopifyApp\\": "src/ShopifyApp"
        }

**Comment by lucasvm** [comment]
Ok, i think i get it, i was able to see everything like demo, anyway when i click on Install, then it redirects to authenticate i get this error:

Oops, something went wrong.

What happened?
Oauth error invalid_request: The Shopify API application does not support oauth

**Comment by ohmybrew** [comment]
What do you have setup in your shopify-app config?

**Comment by lucasvm** [comment]
I have followed this one: https://github.com/ohmybrew/laravel-shopify/wiki/Creating-Webhooks

**Comment by ohmybrew** [comment]
@lucasvm  Yes, so long as you have a url path matching the job, example: "xxxxyyyzzzz.com/webhook/*orders-create*", the package will convert `order-create` into `App\Jobs\OrderCreateJob.php` and expect the job there. It has a built in controller for handling the webhook jobs.

It will then pass the shop domain, and webhook data to the contructor of the job, then once queue'd, the job worker will fire `handle()` of that job class.

For example data, I do not have this off-hand, however, you can find information per resource on Shopify's API docs. Example: https://help.shopify.com/en/api/reference/orders/order#show is data you would get through a webhook for an order, similar for a product update/create, etc, a singular object.

Does this solve your problem?

**Comment by lucasvm** [comment]
Yes its working great, if someone needs to get the data printed on some to check what is comming from Shopify on order creation i have done this:
`use Log; ` at the begining

Create a construct:

```
/**
     * Shop's myshopify domain
     *
     * @var string
     */
    public $shopDomain;

    /**
     * The webhook data
     *
     * @var object
     */
    public $data;

    /**
     * Create a new job instance.
     *
     * @param string $shopDomain The shop's myshopify domain
     * @param object $webhook The webhook data (JSON decoded)
     *
     * @return void
     */
    public function __construct($shopDomain, $data)
    {
        $this->shopDomain = $shopDomain;
        $this->data = $data;
    }
```

On the handle function.
`Log::info("Logging an array: " . print_r($this->data, true));`

This will print the data from Shopify on laravel.log file as Info with all the array of the order :)
