### ISSUE TITLE
charge_id column on charges table needs to be bigint

### ISSUE THREAD

**Issue by CamilleBB** [ohmybrew/laravel-shopify#65]
Hi !
When I tried to activate the app on my store, I got a database error saying the value for "charge_id" column on "charges" table is over range (int range is -2147483648 to 2147483648 if I remember well).
My charge_id was something like 2917400000

I fixed it by setting (manually) the column as BIGINT.

**Comment by ohmybrew** [comment]
Strange, I set this to be a bigint because I ran into issues as well when I created the feature... must've missed a commit :/ I'll patch in a fix for this, thanks!

**Comment by ohmybrew** [comment]
Solved with v3.0.2 in a seperate migration to move int -> bigInt.
