### ISSUE TITLE
After login, app doesn't redirect to the billing route

### ISSUE THREAD

**Issue by sbkl** [ohmybrew/laravel-shopify#66]
Hi,

In the login screen, I enter the shop name which redirect to the shopify screen to install the app. Then, I go back to the login screen instead of seeing the charge screen.

When I enter my domain with the billing route manually, then I can accept the charge.

Is this a bug or something I'm doing wrong?

Thank you.

**Comment by ohmybrew** [comment]
Do you have billing enabled and setup? I can not reproduce this :/

**Comment by ohmybrew** [comment]
No it should take you there (assuming you mean the base app route). Without knowing your full setup or database its hard to say whats up there.

**Comment by sbkl** [comment]
Understand it is not easy for you to help without more details. Below some more details about the configuration. Let me know if this helps...

**composer.json**
"ohmybrew/laravel-shopify": "^3.0"

**Providers, alias and middleware:**
followed documentation.

note:

`\OhMyBrew\ShopifyApp\ShopifyAppProvider::class,`

has been added before

`App\Providers\RouteServiceProvider::class,`

**migration:** 
I ran the following command:

`php artisan vendor:publish --tag=migrations && php artisan migrate`

As mentioned, the app installation is working properly and I can see the shop in the database once I have authorised my app in the shopify admin panel. Then, when I enter the route billing manually then the charge is showing in my database and shopify is confirming the charge (I see it in my store admin panel app directory and I receive a confirmation email from shopify).

**config:** 
I ran the following command and didn't touch anything in the shopify-app.php file

`php artisan vendor:publish --tag=config`

**.env file:**
SHOPIFY_APP_NAME="my-shopify-app"
SHOPIFY_API_KEY=myshopifyapikey
SHOPIFY_API_SECRET=myshopifyapisecret
SHOPIFY_BILLING_ENABLED=1
SHOPIFY_BILLING_TYPE=recurring
SHOPIFY_BILLING_PLAN_NAME="recurring plan"
SHOPIFY_BILLING_PRICE=10.00
SHOPIFY_BILLING_TRIAL_DAYS=14
SHOPIFY_BILLING_TEST=1

**In the shopify app setup:**

**APP URL:**
https://my-url.test/
(I ran valet secure to get the https working)

**Whitelisted redirection URL(s):** 
https://my-url.test/authenticate

**Comment by paulcanning** [comment]
I can confirm this bug also.

However, one thing I have encountered as well is the issue with the GDPR webhooks, so that doesn't help.

**Comment by paulcanning** [comment]
I think the issue is that the shopify-app config sets a default api redirect to '/authenticate' buy it should be '/billing'

**Comment by paulcanning** [comment]
AuthControllerTrait, method `authenticateWithCode()` simple redirects you to the home route after saving the shop details (line 109).

I have stepped through, and there is no reference to billing in this process. That entire trait is void of anything referencing billing, so I imagine some kind of check needs to go in there?

**Comment by paulcanning** [comment]
I found the issue, in my case at least.

I had my own Route set for the home page, following instructions from [here](https://github.com/ohmybrew/laravel-shopify/wiki/Overriding-and-Extending).

You'll notice it is missing the `billable` middleware, which is set in the default route provided by the package.

I simply removed my override, and now the billing check is in place correctly.

**Comment by sbkl** [comment]
@paulcanning Did the trick! Thank you for looking into this.

**Comment by ohmybrew** [comment]
Thanks @paulcanning, just updated the wiki for this... I don't believe I had billing at the time when I wrote it - makes sense now! I've also updated the verbiage to be more clear.
