### ISSUE TITLE
Bug: Login into store "The access scope is missing" after Shopify login

### ISSUE THREAD

**Issue by benmag** [ohmybrew/laravel-shopify#68]
I think I might have stumbled upon a bug but potentially it's just something I haven't correctly setup

When I try to login and I haven't already logged into Shopify, I'll see an "access scope is missing" error. If I'm already logged into Shopify then it works fine

Steps: 

Go to my app directly (not via embedded) and enter my development store
![screen shot 2018-08-15 at 1 41 06 am](https://user-images.githubusercontent.com/4386560/44102173-73fcafc4-a02c-11e8-8891-2a7c18c081c8.png)

Shopify asks me to login, login
<img width="511" alt="screen shot 2018-08-15 at 1 43 07 am" src="https://user-images.githubusercontent.com/4386560/44102237-9884c822-a02c-11e8-8bf7-5d3754da2e50.png">

It fails saying 
```
Oops, something went wrong.

What happened?
Oauth error invalid_scope: The access scope is missing
```

<img width="598" alt="screen shot 2018-08-15 at 1 43 39 am" src="https://user-images.githubusercontent.com/4386560/44102334-c70b556c-a02c-11e8-9b58-3ec44f1310c4.png">

The URL of this page is:
```
https://xxxxxxxx.myshopify.com/admin/oauth/authorize?amp%3Bredirect_uri=https%3A%2F%2F3531d356.ngrok.io%2Fauthenticate&amp%3Bscope=read_products%2Cwrite_products&client_id=27702e4e57453773d2a630e8cbc45xxx
```

The scope seems to be in the URL, so I'm not sure what could be going wrong or if it's just a mistake I've made somewhere

**Comment by demoskp** [comment]
I am not an expert by any stretch of the imagination but I think you forgot to add an api scope in your .env file. That's basically what you are asking shopify you want permission of for example you could have the following in your .env file:

SHOPIFY_API_SCOPES='read_products,write_product_listings'

This for examples tells shopify you want to read products as well as write product listings.

**Comment by benmag** [comment]
I've got my API scopes defined as the `SHOPIFY_API_SCOPES` and OAuth seems to correctly request those permissions **IF** I'm already logged into Shopify

The key "breaking" point is if you're not already logged into Shopify

**Comment by demoskp** [comment]
Have you run the migrations?

**Comment by benmag** [comment]
Yep

**Comment by ohmybrew** [comment]
The scope in the URL but Shopify is still saying an error... maybe its a Shopify issue? I can't see why its throwing the error when its clearly in the URL.

**Comment by ohmybrew** [comment]
@benmag  Wait a second, thats the URL in the browser? Exactly as you posted it?

Decoded, it turns into: `https://xxxxxxxx.myshopify.com/admin/oauth/authorize?amp;redirect_uri=https://3531d356.ngrok.io/authenticate&amp;scope=read_products,write_products&client_id=27702e4e57453773d2a630e8cbc45xxx`

`amp;` there in several spots, which is breaking it, I think maybe Laravel is double escaping.

**Comment by ohmybrew** [comment]
I believe this is the issue... I'll change the blade template to not escape.

**Comment by ptcampbell** [comment]
I also have this problem. Despite the access params existing in the URL string. Can expand on this if you need me to. 🙌

**Comment by ohmybrew** [comment]
I believe it's the escaping Laravel is doing in blade. I've implemented the
change, the test passes, just need to do a physical test to confirm now
it's ok.

**Comment by paulcanning** [comment]
Any update on this?

**Comment by ohmybrew** [comment]
I've simply changed {{ authUrl }} to {!! authUrl !!} Which passes fine in
the tests and doesn't escape the url, I just haven't had a chance to do a
physical test to confirm this fixes it 100%, hopefully tonigh!

**Comment by ohmybrew** [comment]
Sorry, the above is in the views/layouts/default.blade file.

**Comment by paulcanning** [comment]
Default.blade.php

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('shopify-app.app_name') }}</title>

        @yield('styles')
    </head>

    <body>
        <div class="app-wrapper">
            <div class="app-content">
                <main role="main">
                    @yield('content')
                </main>
            </div>
        </div>

        @if(config('shopify-app.esdk_enabled'))
            <script src="https://cdn.shopify.com/s/assets/external/app.js?{{ date('YmdH') }}"></script>
            <script type="text/javascript">
                ShopifyApp.init({
                    apiKey: '{{ config('shopify-app.api_key') }}',
                    shopOrigin: 'https://{{ ShopifyApp::shop()->shopify_domain }}',
                    debug: false,
                    forceRedirect: true
                });
            </script>

            @include('shopify-app::partials.flash_messages')
        @endif

        @yield('scripts')
    </body>
</html>
```

There is no `{{ authUrl }}`

**Comment by paulcanning** [comment]
Also, in my case, the auth URL is adding my site URL as `http://my-app.com` despite the URL being set to `https` in the `.env` file and being served over `https`

**Comment by ohmybrew** [comment]
Sorry currently in meetings! Brain is a bit fired today.

It's actually under auth/fullpage_redirect.blade !

**Comment by paulcanning** [comment]
Any idea why the URL would be putting in `http` and not `https`?

**Comment by ohmybrew** [comment]
It internally uses url() method of Laravel to generate the link. Laravel
does have a secure version of this method. I'll have to dig into a good way
of swapping them depending on the environment. Maybe I'll just check the
server environment vars.

**Comment by paulcanning** [comment]
Found one issue - ShopifyApp.php, line 93

`return parse_url("http://{$domain}", PHP_URL_HOST);`

Pretty sure that should be `https`.

I think you can use something like this, https://laravel.com/api/5.3/Illuminate/Routing/UrlGenerator.html#method_getScheme

**Comment by ohmybrew** [comment]
@paulcanning For the line 93, its actually not returned, its similar method to how the rails version works. It just does some cleaning to ensure we can get a myshopify domain without any paths, or protocols. The parse_url bit just puts the domain in with a protocol since I strip it originally, and grabs the host (which returns back just the myshopify domain), its tested against both http/https :)

Will await your feedback on #75 !

**Comment by ohmybrew** [comment]
With @paulcanning 's merge, and the fix to the full page redirect to not escape, it seems to be working as normal, I can confirm the redirect through a view-source "watcher" in Chrome, is now no longer encoding. Its in v3.0.2.

If unresolved, please feel free to re-open.
