### ISSUE TITLE
Links inside App redirect to my hosting

### ISSUE THREAD

**Issue by lucasvm** [ohmybrew/laravel-shopify#69]
Hi there
 
 Thank you for this great app, im creating a new one, i need to set up an internal link inside the app that links to another page, but the problem i see is that the link opens my app domain and not inside the Shopify iframe.

 My code so far

 On home.blade.php

```
 <div class="links">
                <a href="#getproducts" target="_blank">See my products</a>
            </div>
```

My routes:

```
Route::get(
        '/',
        'Controllers\HomeController@getproducts'
    )
    ->middleware(['auth.shop', 'billable'])
    ->name('getproducts');
```

and i have my function

```
public function getproducts()
    {
    }
```

I need the link to open inside the iframe, is this possible?

**Comment by ohmybrew** [comment]
You need to make sure the ESDK is loading. The base layout file in the package loads in the ESDK requirements. If you're using a custom view, you'll need to extend this built in layout.

**Comment by lucasvm** [comment]
Yes! is now working, you are the best :) I dont want just to copy and paste, but i want to learn how this work, so thanks so much!!

**Comment by ohmybrew** [comment]
No problem, if no ESDK JS is loaded, Shopify assumes its not embedable. Will close :)
