### ISSUE TITLE
Uninstall webhook not working

### ISSUE THREAD

**Issue by paulcanning** [ohmybrew/laravel-shopify#77]
I just enabled the uninstall webhook job, following the exact instructions in the wiki.

shopify-app.php

```
'webhooks' => [
        [
            'topic' => env('SHOPIFY_WEBHOOK_1_TOPIC', 'app/uninstalled'),
            'address' => env('SHOPIFY_WEBHOOK_1_ADDRESS', 'https://my-app.com/webhook/app-uninstalled')
        ],
],
```

in .env as well

```
SHOPIFY_WEBHOOK_1_TOPIC=app/uninstalled
SHOPIFY_WEBHOOK_1_ADDRESS=https://my-app.com/webhook/app-uninstalled
```

AppUninstalledJob.php is in my jobs folder too.

I deleted the app from my test store, but the charge in my DB is still active, and the shop has not been soft deleted.

EDIT - Hmm, despite the rest of my app working from my local machine, looks like webhooks needs a proper tunnel. Looking into ngrok now.

**Comment by paulcanning** [comment]
So, even with ngrok setup, I'm not getting any webhooks coming in. I've set the ngrok URL in the app settings and set my .env webhook address to the ngrok URL.

**Comment by fyroc** [comment]
@paulcanning What happened to this? I'm having a similar issue.

**Comment by ohmybrew** [comment]
I think it was a ngrok issue (ive had this issue happen)...

**Comment by paulcanning** [comment]
Correct, whilst you can use a local setup for most purposes, you have to have the tunnel for the webhooks. I tested with ngrok and it seemed to work fine.
