### ISSUE TITLE
Get Current Billing Plan From Shopify

### ISSUE THREAD

**Issue by fyroc** [ohmybrew/laravel-shopify#80]
Is there anyway to get the current billing plan from Shopify? Currently I created my own plan model and keeping up with it myself, but it would be more accurate if I could see the billing plan that Shopify is using.

**Comment by fyroc** [comment]
```
$charge = $shop->api()->request(
            'GET',
            "/admin/recurring_application_charges/" . $shop->charge_id . ".json"
        )->body->recurring_application_charge;
```

I found it. Thanks

**Comment by ohmybrew** [comment]
Yes, actually, I could add a method to the Charge model, since its attached to a shop, I could do this internally within the model. I'll explore this.

**Comment by fyroc** [comment]
@ohmybrew Did you add this? After updating to `3.0.2` my fix no longer works and I'm now receiving the error.

> `GET https://vndortesting.myshopify.com/admin/recurring_application_charges/.json` resulted in a `404

**Comment by ohmybrew** [comment]
No I didn't add this to the release. It will be in for one upcoming (possibly tonight). shop->charge_id was migrated in 3.0 to a charges table, this may be why it's not working. It was a breaking release.

**Comment by fyroc** [comment]
That did it. Sorry, I should have looked at the new Model that was created. Out of curiosity, do you mind me helping out with some of these bugs and issues I find? I don't mind submitting pull requests. Especially since I'm going to be using this package a lot.

**Comment by ohmybrew** [comment]
Yup no problem, I try to solve any issue that comes in :)

**Comment by ohmybrew** [comment]
As a note: #902363fb85917ba180ba49a5d53bb42b92b4eaa3 gives this ability to pull API data for a charge via `$charge->retrieve()` for single/recurring/credit type charges. Will be in next release.
