### ISSUE TITLE
how to get my shop domain name in my app?

### ISSUE THREAD

**Issue by sprebel** [ohmybrew/laravel-shopify#82]

**Comment by tobiasdalhof** [comment]
Hi! Have a look at the `GET /admin/shop.json` endpoint https://help.shopify.com/en/api/reference/store_properties/shop#show

In order to access the domain, you could do something like this

```php
$shopifyApi->rest('GET', '/admin/shop.json')->body->shop->domain
```

**Comment by ohmybrew** [comment]
@sprebel  Yes, the code above from @tobiasdalhof will work, you can also use the model to get the myshopify domain.

`$shop->shopify_domain`
