### ISSUE TITLE
How to use App outside vendor folder?

### ISSUE THREAD

**Issue by lucasvm** [ohmybrew/laravel-shopify#83]
Hello
 
At this moment i need to have all my resources views, controllers, traits and models inside vendor folder, is there a way to use the common Laravel folders for this? inside app/http/controllers ? for example.

**Comment by brianakidd** [comment]
No, you should never put anything inside the vendor folder.  You should be using your project's app folder.  What's making you think you need to do this?  Maybe the documentation can be clearer but generally speaking, you should not place anything in the vendor folder for this or any other package.

**Comment by ncpope** [comment]
This is the wrong way to do it. Never put your code in the vendor directory.

**Comment by lucasvm** [comment]
Yes, thats why im asking, Laravel is taking the view from vendor (ohmybrew) and not from common folder...

**Comment by brianakidd** [comment]
The framework is returning the view being asked for.  If you want to serve another view, you can do that.  If the view is extending the packages layout, then that layout will be used.

You can override the package routing per the documentation - maybe this will help:

[Overriding and Extending](https://github.com/ohmybrew/laravel-shopify/wiki/Overriding-and-Extending)

**Comment by lucasvm** [comment]
I need to use the folder this way? 
resources/views/vendor/shopify-app/layouts/default.blade.php

everything must be inside
resources/views/vendor/shopify-app
?

Because im getting Oauth error invalid_request when using the view inside resources and not inside vendor.

**Comment by brianakidd** [comment]
The layout that ships with the package has the Shopify init so in your own view you can extend the package's layout or you can create your own in your project's resource folder but it has to have the javascript for initializing the shopify app.  Have a look at the package's default layout.

**Comment by lucasvm** [comment]
Yes, i understand the concept,still getting error here:
GuzzleHttp \ Exception \ ClientException (400)
400 - Oauth error invalid_request
Im extending as documents says
my home view has the extend call
@extends('shopify-app::layouts.default')

**Comment by lucasvm** [comment]
Ok, i got it, the doc is wrong:

It needs to be this way:

```
Route::get(
    '/',
    'HomeController@index')->middleware(['auth.shop', 'billable'])->name('index');
```

**Comment by ncpope** [comment]
It sounds like you might do well with watching the intro to Laravel course on laracasts (its free). You can find it here: https://laracasts.com/series/laravel-from-scratch-2017

I would highly recommend watching the whole series before you continue with this as it will save you a lot of headache.

**Comment by lucasvm** [comment]
Great thank you, already got it working, also it was a matter of cache, doing php artisan cache:clear also worked. Thank you, i was able to work outside vendor now :)

**Comment by ohmybrew** [comment]
Sorry yes, the views are extendable, it just follows standard laravel packaging so you can define views outside the package and define your own, in the wiki link above. Will note the issue in wiki too, thanks!
