### ISSUE TITLE
Cannot Test Billing

### ISSUE THREAD

**Issue by fyroc** [ohmybrew/laravel-shopify#84]
Every time I try to change plans I am getting this error, even though app is set to test billing. 

> Your plan does not allow Shopify App Store purchases. You can upgrade your plan to enable Shopify App Store purchases.

Here is my env:

```
SHOPIFY_BILLING_ENABLED=1
SHOPIFY_BILLING_TYPE=recurring
SHOPIFY_BILLING_PLAN_NAME="Free Plan"
SHOPIFY_BILLING_PRICE=0.00
SHOPIFY_BILLING_CAPPED_AMOUNT=10000.00
SHOPIFY_BILLING_TERMS="Test stuff"
SHOPIFY_BILLING_TEST=1
```

**Comment by ohmybrew** [comment]
@fyroc Its a development shop? And by change plans what do you mean?

**Comment by fyroc** [comment]
It is a development shop. By changing plans I mean by this:

https://github.com/ohmybrew/laravel-shopify/wiki/Creating-a-Billable-App#upgrading-or-downgrading-plans-recurringone-time

**Comment by ohmybrew** [comment]
Ah setDetails part I believe overrides it all. I think you need to pass
'test' => true, directly or 'test' => config('shopify-app.billing_test').

Off the top of my head.. sorry on mobile. But it doesn't autofill values in
if you pass data in directly

**Comment by fyroc** [comment]
Ah, I didn't realize you needed to do it for each Plan. Thanks!

**Comment by ohmybrew** [comment]
Ah sorry about that! I need more time to work on the docs :(
