### ISSUE TITLE
How to Redirect on Custom Create Home Page?

### ISSUE THREAD

**Issue by sprebel** [ohmybrew/laravel-shopify#88]
How to Redirect on Custom Create Home Page after Complete App Installation process.

**Comment by paulcanning** [comment]
Are you perhaps seeing the same issue as me? See here - https://github.com/ohmybrew/laravel-shopify/issues/78

**Comment by sprebel** [comment]
I Solve this Problem.

Add this code in route/web.php

Route::group(['middleware' => ['web']], function () {
  
    Route::get(
        '/',
        'HomeController@index'
    )
    ->middleware(['auth.shop', 'billable'])
    ->name('home');  
});


Add New Controller::- HomeController
and add this return view

public function index()
    {
        return view('index');
    }
