### ISSUE TITLE
Better handling of declined billing

### ISSUE THREAD

**Issue by paulcanning** [ohmybrew/laravel-shopify#89]
Currently, if billing is declined, an `abort(403)` is returned, which spits out an Exception message.

Really, we should direct the user back to their shop, possibly to the App page?

**Comment by tobiasdalhof** [comment]
I agree. The current flow for a declined billing charge is not accepted by the Shopify QA team.

```
App submission QA from Shopify

The app does not have a redirect when a billing charge is declined. 
When a billing charge is declined, merchants should be directed to a 'Charge was declined' page, 
with details or uninstall instructions.
Currently, I'm taken to an error page with no instructions
```

How do you guys handle declined billing charges?

**Comment by ducnv89** [comment]
My way:
1. Create a new route:
Route::get(
        '/declined',
        'AppController@declined'
    )
2. Create a new controller:
//payment declined
    public function declined(){
        return view('declined');
    }
3. Create a blade template file: /declined.blade.php and put your content
4. Edit /laravel-shopify/src/ShopifyApp/Traits/BillingControllerTrait.php
return redirect()->route('declined');

**Comment by ohmybrew** [comment]
I could make a default view I guess. However, can't you make a 403 error view in Laravel and show the message? I figured this way would be more flexible for people. Either way I can change it.

**Comment by paulcanning** [comment]
A custom error blade template works quite nicely.

**Comment by ohmybrew** [comment]
> Custom HTTP Error Pages
> Laravel makes it easy to display custom error pages for various HTTP status codes. For example, if you wish to customize the error page for 404 HTTP status codes, create a  resources/views/errors/404.blade.php. This file will be served on all 404 errors generated by your application. The views within this directory should be named to match the HTTP status code they correspond to. The HttpException instance raised by the abort function will be passed to the view as an $exception variable:
> 
> <h2>{{ $exception->getMessage() }}</h2>

The message in this case would contain the message about declining the billing, maybe I should add this to the wiki or install docs?

**Comment by paulcanning** [comment]
It's a quick and easy solution 👍 

NB - if anyone is attempting to do this via a Package, currently I can't figure it out. So the custom error blade template needs to be in the main app resource folder.

**Comment by ohmybrew** [comment]
Correct yeah, has to be in the main app folder. I think I will provide a Laravel-like styled 403 page and put it in the resources of the repo so someone can easily copy it over (or even use publish to push it to the main apps folder).

**Comment by ohmybrew** [comment]
[Done](https://github.com/ohmybrew/laravel-shopify/wiki/Custom-Billing-Declined-Page). Info here for use, and a view file is in the repo that anyone can pull for boilerplate :)
