### ISSUE TITLE
"Your app does not authenticate after it is uninstalled and reinstalled on the same store"

### ISSUE THREAD

**Issue by tobiasdalhof** [ohmybrew/laravel-shopify#90]
Hey guys, my app recently got reviewed and rejected by the Shopify QA team.

I'm not able to reproduce one of the required changes and was thinking if you can help me out?

Shopify QA team says:
"Your app does not [authenticate ](https://help.shopify.com/en/api/getting-started/authentication/oauth#step-4-making-authenticated-requests) after it is [uninstalled and reinstalled on the same store](https://help.shopify.com/en/api/app-store/listing-in-the-app-store/app-requirements-and-success-criteria/app-review-checklist#errors). Apps should gracefully handle [uninstall and re-install](https://help.shopify.com/en/api/app-store/charging-for-your-app/guides/billing-for-uninstalls#overview-of-app-uninstalls). When an app is uninstalled all permissions from the store become inactive. The app will need to reauthenticate with [OAuth](https://help.shopify.com/en/api/getting-started/authentication/oauth) when a merchant reinstalls your app. Currently, when I attempt to reinstall your app, I'm taken to [this error page](https://screenshot.click/28-48-or304-p57l2.png)."

When I uninstall and reinstall my app i dont get 404...

Not sure if it's package related but I use the default auth flow (with embedded SDK) from this package, any help is much appreciated!

**Comment by ohmybrew** [comment]
Will look into this, I am unsure too. Maybe its the token in the database? I'll check in on this.

**Comment by ohmybrew** [comment]
Edit: @tobiasdalhof  I think it is the token... I'm at work so I can't fully confirm this but looking into my brain about this, heres the process:

1. App gets uninstalled
2. Webhook gets fired out to the default AppUninstalledJob I have (if enabled), and soft deletes everything

However, on reinstall, most likely they still have an active cookie session, they then try to install;

1. Attempt to install
2. The code is un-softdeleting the shop
3. Now a token still exists, plus the cookie
4. Attempts to let them in and fails somehow

I think I need to mod the uninstalled job to kill the token in the database.

**Comment by brianakidd** [comment]
Sounds like the issue I had.  Mine turned out to be related to an existing session for a shop that was deleted - It was having trouble recognizing it as a "new" shop on re-install.  If you remove the session(s), it will probably resolve it.

**Comment by ohmybrew** [comment]
@brianakidd Yup, that plus my reply above yours. We can't delete the cookie for the user obviously because uninstall happens at the admin panel level, but I think modding the job to kill the token will force it to look for a new token/re-auth. I will try this tonight.

**Comment by ohmybrew** [comment]
@tobiasdalhof Ok so I think I found the issue :)

1. On app
2. Go to apps
3. Uninstall app
4. Visit login/install page directly again to install
5. Works

Heres where it fails...

1. On app
2. Go to apps
3. Uninstall app
4. Visit home route directly
5. 404

I can confirm it is a token issue. By removing the token, it redirects to the install screen instead of 404.

I have a slight change to the authmiddleware to do, and add this process of nulling the token on appuninstall job.

Will push this in for a fix today, thanks!

**Comment by ohmybrew** [comment]
v3.1.1 will fix this issue.

AuthMiddleware moved to use `empty($shop->shopify_token)` and AppUninstalledJob added a method to remove the `shopify_token`. Tested it out, and its working, you're now redircted to the login/install page instead of 404.

**Comment by tobiasdalhof** [comment]
@ohmybrew Awesome, thank you such much

**Comment by uri3000** [comment]
What happens if the webhook fires with a delay?
