### ISSUE TITLE
Better way to store/retrieve separate Shop App installs

### ISSUE THREAD

**Issue by paulcanning** [ohmybrew/laravel-shopify#91]
Currently, this framework assumes it will be a single app.

In my use-case, my single Laravel app is serving multiple Shopify Apps.

The current way to get Shop info is to look up the shop domain in the `shops` table, but if multiple apps are logging data into that table, there is no way to differentiate.

I was considering adding an extra column that would be the apps namespace which gets added to all calls to the shop model.

Thoughts? Ideas?

**Comment by brianakidd** [comment]
Wow, this sounds brutal.  Are the different apps you are serving so similar in functionality that you can manage it within one code base?

Are there reasons why you wouldn't want one project = one app?  Hosting costs, maybe?

**Comment by paulcanning** [comment]
The apps are split into Laravel Packages. The are being served via a single Laravel application in order to maintain a small app ecosystem. Also, for fun!

**Comment by ohmybrew** [comment]
Is this something common to do? I've always done one db/setup per app sort of thing. If it something fairly common I don't pursuing it.. I think namespace on the shop table would be the best since thats the main table. If I we're to bake it in, I would probably have a env setting which could define a namespace (app handle or something), and mod the firstOrCreate method on auth to use that namespace, and a scope on the shop model which would add it to every call

**Comment by paulcanning** [comment]
I'm using package configs, rather than the global .env file, so that all app configs are separeted.

Yea, the namespace column in the shop table is the likely answer, for now.

Is it common? No idea, as I find it difficult to find anyone actively talking about Shopify app development.

**Comment by ohmybrew** [comment]
> I find it difficult to find anyone actively talking about Shopify app development
Very true.

By .env yes I meant the config PHP file. I don't mind baking this in, if its beneficial to others.

**Comment by paulcanning** [comment]
FYI - this may be premature, as I'm currently stuck on making binds work with each individual app package.

**Comment by ohmybrew** [comment]
No worries, thought I'd share my method!

**Comment by ohmybrew** [comment]
v3.2.0 release contains the namespace abilities. [Doc](https://github.com/ohmybrew/laravel-shopify/wiki/Namespacing-Your-App) on setup/usage as well.

Will close for now, unless you wish to continue discussion, thanks!
