### ISSUE TITLE
App uninstall not working

### ISSUE THREAD

**Issue by fyroc** [ohmybrew/laravel-shopify#93]
When ever I uninstall my app, it looks like the jobs are firing but the shop isn't being soft deleted.

```{"displayName":"OhMyBrew\\ShopifyApp\\Jobs\\WebhookInstaller","job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"timeout":null,"timeoutAt":null,"data":{"commandName":"OhMyBrew\\ShopifyApp\\Jobs\\WebhookInstaller","command":"O:41:\"OhMyBrew\\ShopifyApp\\Jobs\\WebhookInstaller\":9:{s:7:\"\u0000*\u0000shop\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":4:{s:5:\"class\";s:8:\"App\\Shop\";s:2:\"id\";i:1;s:9:\"relations\";a:0:{}s:10:\"connection\";s:5:\"mysql\";}s:11:\"\u0000*\u0000webhooks\";a:3:{i:0;a:2:{s:5:\"topic\";s:11:\"shop\/redact\";s:7:\"address\";s:43:\"https:\/\/app.statusy.net\/webhook\/shop-redact\";}i:1;a:2:{s:5:\"topic\";s:15:\"customers\/redac\";s:7:\"address\";s:48:\"https:\/\/app.statusy.net\/webhook\/customers-redact\";}i:2;a:2:{s:5:\"topic\";s:15:\"app\/uninstalled\";s:7:\"address\";s:47:\"https:\/\/app.statusy.net\/webhook\/app-uninstalled\";}}s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}"}}```

Do I need to add these routes?

**Comment by fyroc** [comment]
I got the jobs to run, but still not deleting.

**Comment by fyroc** [comment]
Sorry for all of the comments but I managed to track down the error:


> #37 /home/forge/app.statusy.net/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Obj$
> #38 /home/forge/app.statusy.net/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #39 /home/forge/app.statusy.net/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\O$
> #40 /home/forge/app.statusy.net/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Ou$
> #41 /home/forge/app.statusy.net/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #42 {main}
> "}
> [2018-09-01 04:20:47] production.ERROR: Client error: `GET https://vndortesting.myshopify.com/admin/webhooks.json?limit=250&fields=id%2Caddress` resulted in a `401 Unauthorized` response:
> {"errors":"[API] Invalid API key or access token (unrecognized login or wrong password)"}
>  {"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 401): Client error: `GET https://vndortesting.myshopify.com/admin/webhooks.json?limit=250&fields=id%2Caddress` resulted in a `401 Unauthorized` response:
> {\"errors\":\"[API] Invalid API key or access token (unrecognized login or wrong password)\"}
>  at /home/forge/app.statusy.net/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
> [stacktrace]
> #0 /home/forge/app.statusy.net/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Psr7\\Request), Object(GuzzleHttp\\Psr7\\Response))

**Comment by fyroc** [comment]
Is this the same issue as:
https://github.com/ohmybrew/laravel-shopify/issues/90

**Comment by ncpope** [comment]
@fyroc It looks like a different issue to me. Have you added your api key to your .env file?

**Comment by fyroc** [comment]
I have, the Shopify API itself is working fine. Just not when I try to delete

**Comment by fyroc** [comment]
UPDATE

I managed to fix the above error by uninstalling and reinstalling the Shop. Now I get this error instead:

> #37 /home/forge/app.statusy.net/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Consol$
> #38 /home/forge/app.statusy.net/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Inp$
> #39 /home/forge/app.statusy.net/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\C$
> #40 /home/forge/app.statusy.net/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Co$
> #41 /home/forge/app.statusy.net/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\$
> #42 {main}
> "}
> [2018-09-01 14:12:15] production.ERROR: Client error: `POST https://vndortesting.myshopify.com/admin/webhooks.json` resulted in a `422 Unprocessable Entity` respons$
> {"errors":{"topic":["Invalid topic specified. Topics allowed: app\/uninstalled, carts\/create, carts\/update, checkouts\ (truncated...)
>  {"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 422): Client error: `POST https://vndortesting.myshopify.com/admin/webhooks.json` resulted in $
> {\"errors\":{\"topic\":[\"Invalid topic specified. Topics allowed: app\\/uninstalled, carts\\/create, carts\\/update, checkouts\\ (truncated...)
>  at /home/forge/app.statusy.net/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
> [stacktrace]
> #0 /home/forge/app.statusy.net/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Psr7\\Request), O$
> #1 /home/forge/app.statusy.net/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Response))
> #2 /home/forge/app.statusy.net/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, Object(GuzzleHttp\\Psr7\\Response), Arr$
> #3 /home/forge/app.statusy.net/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()
> #4 /home/forge/app.statusy.net/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\\Promise\\TaskQueue->run(true)
> #5 /home/forge/app.statusy.net/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
> #6 /home/forge/app.statusy.net/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\\Promise\\Promise->waitIfPending()
>

**Comment by fyroc** [comment]
@ohmybrew Do you have any idea why the web hook installer is giving the above error?

**Comment by ohmybrew** [comment]
Ah nope I'll have to check into this.. I see topic invalid, what topic is being passed in your config?

**Comment by fyroc** [comment]
```
'webhooks' => [
        [
            'topic' => 'shop/redact',
            'address' => env('SHOPIFY_SHOP_REDACT', 'https://www.statusy.local/webhook/shop-redact')
        ],
        [
            'topic' => 'customers/redact',
            'address' => env('SHOPIFY_CUSTOMERS_REDACT', 'https://www.statusy.local/webhook/shop-redact')
        ],
        [
            'topic' => 'app/uninstalled',
            'address' => env('SHOPIFY_WEBHOOK_1_ADDRESS', 'https://www.statusy.local/webhook/app-uninstalled')
        ],
    ],

```

**Comment by ohmybrew** [comment]
Ah the GDPR webhooks dont be registered there. I just updated the webhook
command to tell people this, and the wiki entry :) they get put into the
app settings page.

**Comment by fyroc** [comment]
That was it, thanks. I'm not sure why I added the GDPR web hooks.
