### ISSUE TITLE
Receiving an duplicate content error when displaying billing declined in an embedded app

### ISSUE THREAD

**Issue by ncpope** [ohmybrew/laravel-shopify#94]
When displaying within an embedded app it will redirect which will cause the billing controller to try and create the charge more than once in the db. This causes an error like `SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1234567890' for key 'charges_charge_id_unique' `

https://github.com/ohmybrew/laravel-shopify/blob/4258693b3eb7430d426530faf1932cf70d1aa6cd/src/ShopifyApp/Traits/BillingControllerTrait.php#L51-L55

These lines could be changed to:

```php
$charge = Charge::firstOrCreate([
    "type" => $this->chargeType() === 'recurring' ? Charge::CHARGE_RECURRING : Charge::CHARGE_ONETIME,
    "charge_id" => $chargeId,
    "status" => $status,
    "shop_id" => $shop->id,
]);
```

This will prevent the error and will select the charge rather than creating a new one.

https://github.com/ohmybrew/laravel-shopify/blob/4258693b3eb7430d426530faf1932cf70d1aa6cd/src/ShopifyApp/Traits/BillingControllerTrait.php#L83-L84

This could then become:
```php
// Save the charge
$charge->save();
```

**Comment by ohmybrew** [comment]
Thank you for the note, I have adjusted this for next release.

**Comment by ncpope** [comment]
Hi, I just left a comment on the commit but I'm not exactly sure whether or not it shows since I've never done one before, so I'll just post it here as well:

https://github.com/ohmybrew/laravel-shopify/commit/82b07788218fc5dbc8699dab92d02a566050c61d#r30494464

**Comment by ohmybrew** [comment]
Present in [v4.0.0](https://github.com/ohmybrew/laravel-shopify/releases/tag/v4.0.0)
