### ISSUE TITLE
Does not have a redirect when a billing charge is declined

### ISSUE THREAD

**Issue by fyroc** [ohmybrew/laravel-shopify#96]
Part of Shopify's requirements is there needs to be clear instructions on uninstalling the aim if the billing is declined.

> If your app charges merchants, then it must include a page that is displayed when an app charge is declined. The information that appears on this page will depend on your app's pricing model, but at a minimum it should explain why the charge was not accepted, how to confirm the charge, and how to remove the app.

Can you make this some sort of view instead of just having it throw an error?

https://screenshot.click/04-02-5sqg5-cmzk0.mp4

**Comment by ducnv89** [comment]
I said this here: https://github.com/ohmybrew/laravel-shopify/issues/89#issuecomment-417249924
And I passed with Shopify QA, but nobody trust me and forget me haha.
http://prntscr.com/kqp8wi

**Comment by ohmybrew** [comment]
I think [this](https://github.com/ohmybrew/laravel-shopify/wiki/Custom-Billing-Declined-Page) is a good lightweight solution

**Comment by ohmybrew** [comment]
I have now enabled a view for the next release. Its a standard blade template which can be overwritten via standard laravel methods (commit 82b0778)

**Comment by ohmybrew** [comment]
Solved in [v4.0.0](https://github.com/ohmybrew/laravel-shopify/releases/tag/v4.0.0).

Actual view is now used and can be overwritten via standard Laravel methods.
