### ISSUE TITLE
New issue in installing the shopify app

### ISSUE THREAD

**Issue by vishalinfowind** [ohmybrew/laravel-shopify#98]
Hello,
I have implement this library but i got "redirect" error after login.
Let me know how to solve this error.

"Oauth error invalid_request: The redirect_uri is not whitelisted"
Here is the screenshot of my error:  http://prntscr.com/kr6n8v 

Please help me

**Comment by ducnv89** [comment]
Hi vishalinfowind,
I have just checked your screenshot.
Because your redirect_uri is NOT https.
Please check your App setting again.
Thanks

**Comment by ohmybrew** [comment]
HTTPS is required, you'll need to add it to your redirect_uri as per @ducnv89 said.

**Comment by vishalinfowind** [comment]
Here we share a screenshot with HTTPS
https://prnt.sc/krk6md

**Comment by ohmybrew** [comment]
@vishalinfowind  Looks correct
